pom.xml
src/main/java/sirius/biz/tenants/TenantUserManager.java

Adds a method to directly resolve a UserInfo from a known UserAccount id
Also refactors the inner workings of the user manager to better utilize the
available caches by using the same method for all access scenarios

Adds a method to directly resolve a UserInfo from a known UserAccount id

---

pom.xml
sirius-biz.iml

Updates to the latest sirius-web

Updates to the latest sirius-web

---

pom.xml
src/main/java/sirius/biz/tenants/TenantUserManager.java

Merge remote-tracking branch 'origin/master' into aha/WebUpdate

UserAccount Fixx

---

.idea/inspectionProfiles/Sirius.xml
pom.xml
sirius-biz.iml

Merge remote-tracking branch 'origin/master' into aha/db-update

VersionUpdate

---

pom.xml
sirius-biz.iml

Updates to the latest version of sirius-web

Updates to the latest version of sirius-web

---

pom.xml
sirius-biz.iml
src/main/java/sirius/biz/tenants/Tenant.java
src/main/java/sirius/biz/tenants/Tenants.java
src/main/resources/component-biz.conf

Adds some helper methods to check if a tenant has children

Adds some helper methods to check if a tenant has children

---

pom.xml
src/main/java/sirius/biz/tenants/TenantUserManager.java

With version 1.6 system tenants did not have all roles they needed.

Fix roles for system tenants

---

pom.xml
src/main/resources/default/view/tenants/user-account.html

Fixes the link to a user-account in the breadcrumbs of the user-account.html template.

Fixing link to useraccount in the user-account.html template

---

pom.xml
src/main/java/sirius/biz/tenants/UserAccountController.java

Adds a UserAccountAutocomplete function in the UserAccountController.java which can be used in templates to select an UserAccount.
Removes deprecated call of editAfterCreate on the SaveHelper.
Bumps the Version to 1.8.3.

Adds a Autocomplete function for templates in the UserAccountController + Resolves SonarLint Issues in UserAccountController

---

pom.xml
src/main/java/sirius/biz/web/PageHelper.java

Now boolean filter can be applied to a page very easy with the given method. Before this method this had to be done manually.

Adding page helper filters on boolean

---

pom.xml
src/main/resources/default/view/tenants/select-tenant.html

Removes wrong import and now uses it as an argument like it was intended.
bumps Version

Small template fix

---

pom.xml
src/main/java/sirius/biz/web/BizController.java

Implements Method to fluently specify the columns which should actually be loaded from the context.

Allows to manually set the columns which should be loaded from the context

---

pom.xml
src/main/resources/default/view/parts/infobox.html
src/main/resources/default/view/parts/infoboxElement.html

Moves the element code of the infobox template into an own template.

Adds infoboxElement Template

---

pom.xml
src/main/java/sirius/biz/web/BizController.java

Adds an assertTenant Method and an onSaveHandler to assert EntityRefs during the save process.

Moves the presaveHandler to be executed after the entity load

---

pom.xml
src/main/java/sirius/biz/model/PersonData.java
src/main/java/sirius/biz/tenants/UserAccountController.java
src/main/resources/default/mail/useraccount/password-html.vm
src/main/resources/default/mail/useraccount/password.vm

From now on, the mail contains the complete url to the login site instead of the base url. Futhermore, users with no lastname filled will be greeted by their username in the password mails as they were greetet only by their salutation if only this fields was filled.

Enhance password mails

---

src/main/java/sirius/biz/web/PageHelper.java

Creates the possibility to adjust the pageSize for rendered Pages while using the PageHelper.
Renames static PAGE_SIZE field to DEFAULT_PAGE_SIZE.

Makes pageSizes adjustable in the PageHelper

---

src/main/resources/component-biz.conf
src/main/resources/default/templates/codelists/settings-menu-code-lists.html.pasta
src/main/resources/default/templates/wondergem/menu-left-settings.html.pasta
src/main/resources/default/templates/wondergem/menu-right-user.html.pasta

Adds the menu settings dropdown menu entry

---

src/main/resources/default/taglib/w/selectObject.html.pasta

Porting selectObject to Tagliatelle

---

src/main/java/sirius/biz/web/BizContextExtender.java
src/main/resources/default/taglib/w/codelistSelect.html.pasta

Port codelistSelect to Tagliatelle

---

src/main/resources/default/templates/tenants/user-account.html.pasta

Otherwise the values are not rendered correctly.

Use correct navboxLink

---

src/main/resources/default/templates/tenants/tenant-details.html.pasta
src/main/resources/default/templates/tenants/tenant.html.pasta
src/main/resources/default/templates/tenants/user-account-details.html.pasta
src/main/resources/default/templates/tenants/user-account.html.pasta

In Sirius-Web templates- is also used so in Sirius-Biz this should be also used so it does not differ.

Rename extensions name to templates-

---

sirius-biz.iml
src/main/java/sirius/biz/locks/BasicLockManager.java
src/main/java/sirius/biz/locks/JavaLockManager.java
src/main/java/sirius/biz/locks/LockInfo.java
src/main/java/sirius/biz/locks/LockManager.java
src/main/java/sirius/biz/locks/Locks.java
src/main/java/sirius/biz/locks/LocksCommand.java
src/main/java/sirius/biz/locks/SQLLockManager.java
src/main/resources/component-biz.conf

Permits to use fst in-memory locks for single machine installations.

---

src/main/resources/default/templates/storage/objects.html.pasta

Fixes deleteLink for storage object deletion in list overview.

Fixes deleteLink for storage object deletion.

---

pom.xml
src/main/resources/default/templates/jobs/jobs.html.pasta
src/main/resources/default/templates/tenants/user-account.html.pasta

Those taglibs had some misspelling and therefore were not shown.

Fix wrong taglibs

---

src/main/java/sirius/biz/jobs/JobsController.java
src/main/resources/default/templates/jobs/job.html.pasta

Jobs can now be run and the protocols can be shown.

Fixes two uri typos in JobsController and template

---

src/main/java/sirius/biz/storage/Storage.java
src/main/java/sirius/biz/storage/StorageCleanupLoop.java
src/main/resources/component-biz.conf

Prevents excessive database queries by caching the virtual objects.

Implements caching for virtual objects

---

src/main/java/sirius/biz/storage/DownloadBuilder.java
src/main/java/sirius/biz/storage/VersionManager.java
src/main/resources/component-biz.conf

For the conversion using java only png and jpg are supported.
For the external command line all formats are supported.
Adds different handling for scaling, extending, and converting of BufferedImages depending on the imageFormat so that a png image can be transformed with transparency.

Adds the possibility to create versions of images with different imageFormats

---

pom.xml
src/main/resources/default/taglib/w/storedObjectUploader.html.pasta
src/main/resources/default/templates/storage/stored-object-uploader.html.pasta
src/main/resources/default/templates/tenants/password.html.pasta

Splits up the css classes used for styling from those classes which are used as selectors in js.
Version bump.

Splits up css classes used for styling and those used for js

---

pom.xml
src/main/java/sirius/biz/model/LoginData.java
src/main/resources/default/templates/tenants/user-account-details.html.pasta

Generate API tokens if not present and show it in the user account's detail page.

Generate API token if not present

---

pom.xml
src/main/resources/default/templates/tenants/user-account-details.html.pasta
src/main/resources/default/templates/tenants/user-account.html.pasta

This is more understandable than a readyonly text field.

Show API-Token and generated password in sidebar

---

pom.xml
src/main/resources/default/taglib/w/storedObjectUploader.html.pasta

Allows for the displaying of the StoredObjectRef Key in the storedObjectUploader tag.
Version Bump

Display ObjectRefKey in the storedObjectUploader tag

---

src/main/resources/default/templates/protocol/mail.html.pasta

The name of the fields have changed.

Read correct fields in mail logs

---

src/main/java/sirius/biz/jdbc/model/LoginData.java
src/main/resources/biz_de.properties
src/main/resources/component-biz.conf
src/main/resources/default/templates/tenants/user-accounts.html.pasta

 Hide generated passwords after x amount of time

---

src/main/resources/default/taglib/w/selectObject.html.pasta
src/main/resources/default/taglib/w/storedObjectUploader.html.pasta
src/main/resources/default/templates/storage/buckets.html.pasta
src/main/resources/default/templates/storage/objects.html.pasta

Due to some refactoring these were wrong.

Fixe some package paths

---

src/main/java/sirius/biz/importer/BaseImportHandler.java
src/main/java/sirius/biz/importer/ImportHandler.java
src/main/java/sirius/biz/importer/ImportHandlerFactory.java
src/main/java/sirius/biz/importer/Importer.java
src/main/java/sirius/biz/importer/ImporterContext.java
src/main/java/sirius/biz/importer/SQLEntityImportHandler.java
src/test/java/sirius/biz/importer/ImporterSpec.groovy

Changes for import Handler

---

src/main/java/sirius/biz/importer/ImportHandler.java
src/main/java/sirius/biz/importer/SQLEntityImportHandler.java

this allows us to commit all batched entities without closing the connections

Implements commit method for specific handler

---

src/main/resources/component-biz.conf

To avoid full storage.
Tags: versions, storage

Limit number of versions by default

---

src/main/java/sirius/biz/process/Processes.java
src/main/resources/default/templates/wondergem/menu-right-user.html.pasta

Bugfix for the fetchProcessForUser Method

---

src/main/java/sirius/biz/tenants/TenantController.java

- The user's tenant is always included in the tenants list for tenants switch
- Chosing the user's tenant on tenant switching will be handled as "going back to main"
- Going back to main tenant redirects to goto parameter or root instead of tenant list to avoid confusion
Tags: tenant, switch

Enhancements on tenants switching

---

src/main/java/sirius/biz/jobs/params/VirtualObjectParameter.java
src/main/resources/component-biz.conf
src/main/resources/default/templates/jobs/params/virtual-object-autocomplete-script.html.pasta
src/main/resources/default/templates/jobs/params/virtual-object-autocomplete.html.pasta

Contains a selection of current files and an upload link

Implements a file upload parameter

---

src/main/java/sirius/biz/storage/versions/VersionedFiles.java
src/test/java/sirius/biz/storage/VersionedFilesSpec.groovy

null-content caused an NPE here.
Tags: versioned files

Fix NPE on null content of versioned files

---

src/main/java/sirius/biz/codelists/CodeListEntry.java
src/main/java/sirius/biz/codelists/CodeLists.java

The value itself is stored trimmed in the codelist therefore the check if a value is present should also be executed with a trimmed value.
Tags: codelist

Trim code on codelist value fetch

---

src/main/java/sirius/biz/process/ProcessController.java

To reduce scrolling on this page.
Tags: process, job, log

Show more process log entries per page

---

src/main/java/sirius/biz/process/ProcessController.java
src/main/resources/default/templates/process/process.html.pasta

Processes now can be cancelled in their execution view.
Tags: job, process

Cancel button for processes

---

src/main/java/sirius/biz/codelists/CodeListController.java

To make them easier to access when needed for non system tenant users.
Tags: code lists

Remove system tenant restriction for code lists

---

src/main/java/sirius/biz/jobs/DatabaseProcessor.java

Iterates over an sql query and transforms the selected rows, so that we can handle the actual data
with a row processor (e.g. the smart line processor which can handle aliases).
This enables us to use the same import logic for csv, excel and database data
- Fixes: SE-8122

Creates a row processor which can be used with the smartLineProcessor

---

src/main/resources/component-biz.conf
src/main/resources/default/templates/codelists/code-list-details.html.pasta

- Codelists can be created
- List frameworks correctly

Small fixes

---

src/main/resources/default/templates/tenants/tenant-details.html.pasta

The naming was wrong.
Tags: tenant, ip

IP ranges for tenants can be filled again

---

src/main/resources/default/mail/useraccount/password.html.pasta

This was left on the standard mail templates moving to Sirius Web.
Tags: mail, password

Use new mail template for password mail

---

src/main/java/sirius/biz/isenguard/Isenguard.java

This is only in the default implemention the IP and can be used in a much broader sense for grouping multiple calls that should be counted towards the same limit.
For example this can and will be used to limit all API calls of the same tenant. The new name should now reflect this better.
Fixes: SIRI-55

Changes the wording of the ip/scope parameter to be more generic

---

pom.xml
src/main/java/sirius/biz/analytics/events/Event.java
src/main/java/sirius/biz/analytics/events/UserData.java
src/main/java/sirius/biz/analytics/events/WebData.java

FixedString are only sensible when the strings always have a specific length. Else a "String" with variable size is advisable.
FixedString = String with "length" annotation
String = String without "length" annotation (variable size)
https://groups.google.com/forum/#!topic/clickhouse/dEEN2TMaspk

Only use ClickHouse FixedString if sensible

---

src/main/java/sirius/biz/importer/ImportDictionary.java
src/main/java/sirius/biz/jobs/batch/file/LineBasedImportJob.java

Adds the possibility to merge a dictionary into an other one. Before now we could not read or add the aliases of a dictionary to an other one.
-Tags: Feature

Adds the possibility to merge a dictionary into an other one.

---

src/main/java/sirius/biz/model/ContactData.java

Adds the AutoImport annotation to ContactData properties so we can import them automatically with the sirius-biz import job framework.
-Tags: Feature

Adds AutoImport Annotation to ContactData fields

---

src/main/java/sirius/biz/model/LoginData.java

To determine length and avoid warning message.

Length for fingerprint

---

src/main/java/sirius/biz/codelists/CodeLists.java
src/main/java/sirius/biz/tenants/SAMLController.java
src/main/java/sirius/biz/tenants/UserAccountController.java
src/main/resources/biz_de.properties

E.g. the forgot password option for backend users

Handles some edge cases in which the current tenant is not available

---

src/main/java/sirius/biz/tenants/SAMLController.java

Run saves in the scope of the user as the save internally tries to fetch the salutation translation from a codelist.
Tags: saml, codelist

SAML Code List check

---

src/main/java/sirius/biz/codelists/CodeLists.java
src/main/java/sirius/biz/tenants/SAMLController.java
src/main/java/sirius/biz/tenants/UserAccountController.java
src/main/resources/biz_de.properties

Bugfixes for accessing code lists
Boolean parameter for jobs

Bugfixes from master 9 branch

---

src/main/java/sirius/biz/tenants/TenantUserManager.java

This enables us to create tenant specific jobs based on the permission

Adds the tenant name to the roles of the user

---

src/main/java/sirius/biz/jobs/batch/entity/EntityBatchJob.java

This job can iterate over entities and process them e.g. for changing some entities or exporting them.
Tags: job, entity

Job for iterating over entities

---

src/main/java/sirius/biz/jobs/params/PartListParameter.java

Returns correct template path for partlist job parameter

---

src/main/java/sirius/biz/jobs/params/AmountParameter.java
src/main/java/sirius/biz/jobs/params/IntParameter.java
src/main/java/sirius/biz/jobs/params/StringParameter.java
src/main/java/sirius/biz/jobs/params/TextParameter.java
src/main/resources/default/templates/biz/jobs/params/textfield.html.pasta

Parameter for using amounts in jobs.
Tags: job, parameter, amount

Parameter for accepting amounts

---

src/main/java/sirius/biz/web/BasePageHelper.java

These can be used to visualize and maintain "hidden" / special parameters once they are present.

Adds a helper method to add parameter based facets.

---

src/main/resources/default/templates/biz/tenants/tenant.html.pasta

Allows to render custom content on the right side of the tenant header

---

src/main/java/sirius/biz/tenants/AdditionalRolesProvider.java
src/main/java/sirius/biz/tenants/TenantUserManager.java

And apply the PartList to the calculated roles

Add the AdditionalRolesProvider as PartList to the UserManager

---

src/main/java/sirius/biz/tenants/TenantUserManager.java
src/main/java/sirius/biz/tenants/Tenants.java

Adds shortcuts to Tenants to get userAccounts cached in the UserManager

---

src/main/resources/default/templates/biz/tenants/tenant-details-fields.html.pasta
src/main/resources/default/templates/biz/tenants/tenant-details.html.pasta
src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta
src/main/resources/default/templates/biz/tenants/user-account-details.html.pasta

to be able to integrate them into other templates to make tenants/users editable easily.

Extracts tenant and user form fields into seperate templates

---

src/main/resources/default/templates/wondergem/menu-right-user.html.pasta

Else when an empty user was present, errors would be thrown as they could not be converted into an UserAccount

Moves title of right user menu inside 'flag-logged-in' permission block

---

src/main/resources/default/templates/biz/tenants/profile.html.pasta

This is for example needed when including post buttons that create their own form with a CSRF token for security.

Excludes sidebar from the profile form to allow including forms there

---

src/main/java/sirius/biz/protocol/AuditLog.java
src/main/java/sirius/biz/protocol/AuditLogController.java
src/main/java/sirius/biz/protocol/AuditLogEntry.java
src/main/java/sirius/biz/tenants/TenantController.java
src/main/java/sirius/biz/tenants/TenantUserManager.java
src/main/java/sirius/biz/tenants/UserAccountController.java

Especially those where the system tenant selected / became other
users / tenants.

Hides some AuditLogs from users.

---

src/main/java/sirius/biz/process/ProcessController.java
src/main/java/sirius/biz/process/logs/ProcessLog.java
src/main/java/sirius/biz/process/output/LogsProcessOutputType.java
src/main/java/sirius/biz/process/output/TableProcessOutputType.java

This seems to be a better approach than mis-using the message handler.

Permits to specify a dedicated custom message type for facet filtering.

---

src/main/java/sirius/biz/analytics/reports/Report.java
src/main/java/sirius/biz/jobs/BasicJobFactory.java
src/main/java/sirius/biz/jobs/JobFactory.java
src/main/java/sirius/biz/jobs/JobsController.java
src/main/java/sirius/biz/jobs/infos/HTMLInfo.java
src/main/java/sirius/biz/jobs/infos/HeadingInfo.java
src/main/java/sirius/biz/jobs/infos/JobInfo.java
src/main/java/sirius/biz/jobs/infos/JobInfoCollector.java
src/main/java/sirius/biz/jobs/infos/ReportInfo.java
src/main/java/sirius/biz/jobs/infos/TextInfo.java
src/main/java/sirius/biz/jobs/infos/WellInfo.java
src/main/java/sirius/biz/jobs/interactive/InteractiveJobFactory.java
src/main/resources/biz_de.properties
src/main/resources/default/templates/biz/jobs/infos.html.pasta
src/main/resources/default/templates/biz/jobs/infos/heading.html.pasta
src/main/resources/default/templates/biz/jobs/infos/html.html.pasta
src/main/resources/default/templates/biz/jobs/infos/report.html.pasta
src/main/resources/default/templates/biz/jobs/infos/text.html.pasta
src/main/resources/default/templates/biz/jobs/infos/well.html.pasta
src/main/resources/default/templates/biz/jobs/interactive-job.html.pasta
src/main/resources/default/templates/biz/jobs/job.html.pasta

Provides a tiny framework to output elaborate job docs.

Provides a tiny framework to output elaborate job documentation.

---

pom.xml
src/main/resources/default/extensions/biz-menu/menu-code-lists.html.pasta
src/main/resources/default/extensions/biz-menu/menu-jobs.html.pasta
src/main/resources/default/extensions/biz-menu/menu-protcols.html.pasta
src/main/resources/default/extensions/biz-menu/menu-system-tenant.html.pasta
src/main/resources/default/extensions/biz-menu/menu-tenants.html.pasta
src/main/resources/default/extensions/biz-menu/menu-user-logout.html.pasta
src/main/resources/default/extensions/wondergem-page-menu/menu.html.pasta

Also moves every menu section into its own extension, so that additional extensions can be freely placed using the extensions priority
Fixes OX-5263

Structures menu into settings,user and system and rearranges menu items into them

---

src/main/resources/biz_cs.properties
src/main/resources/biz_da.properties
src/main/resources/biz_de.properties
src/main/resources/biz_en.properties
src/main/resources/biz_es.properties
src/main/resources/biz_fr.properties
src/main/resources/biz_hu.properties
src/main/resources/biz_it.properties
src/main/resources/biz_nl.properties
src/main/resources/biz_pl.properties
src/main/resources/biz_se.properties

Adds translations for the word 'lithuanian'

---

pom.xml
src/main/resources/default/extensions/biz-menu/menu-protcols.html.pasta
src/main/resources/default/extensions/biz-menu/menu-system-tenant.html.pasta
src/main/resources/default/extensions/wondergem-page-menu/menu.html.pasta

As needed by newest sirius-web version

Updates sirius web & adds prefix to menu icon parameters

---

src/main/java/sirius/biz/protocol/TraceData.java

Allows to check wether a trace was changed after a point in time

---

src/main/java/sirius/biz/importer/format/ImportDictionary.java
src/main/java/sirius/biz/jobs/batch/file/LineBasedImportJob.java

Adds option to fail the import of a data row if it has too many cells

---

src/main/java/sirius/biz/tenants/deletion/CheckForMongoChildrenTask.java
src/main/java/sirius/biz/tenants/deletion/CheckForSQLChildrenTask.java
src/main/resources/biz_de.properties
src/main/resources/biz_en.properties

Child tenant should be deleted first or removed as a child

Check that the deleting tenant does not have children

---

src/main/java/sirius/biz/jobs/batch/ExportBatchProcessFactory.java
src/main/java/sirius/biz/jobs/batch/SimpleBatchProcessJobFactory.java

Adds the persistence period to two abstract jobs

---

src/main/java/sirius/biz/jdbc/DatabaseController.java

Prevents npe if the selected value is null

---

src/main/java/sirius/biz/importer/format/ImportDictionary.java

Prevents a formatting error by passing a missing param to an error msg

---

src/main/java/sirius/biz/importer/format/AmountRangeCheck.java
src/test/java/sirius/biz/importer/format/AmountRangeCheckSpec.groovy

Fixes the amount range check for FieldDefinitions

---

src/main/java/sirius/biz/jobs/params/EntityParameter.java

Smart-translates a given label of an entity parameter by calling super

---

src/main/java/sirius/biz/importer/format/ImportDictionary.java

This can be usefull for adding more in depth error handling or filtering the checked record so it only contains valid fields.
Fixes: OX-5429

Passes the name of the offending field to the problem consumer

---

src/main/java/sirius/biz/storage/VirtualObject.java

Makes sure that the path check is done after the path is normalized

---

pom.xml
src/main/java/sirius/biz/cluster/InterconnectCacheCoherence.java

To synchronize "put"-calls in multi node systems for CoherentCaches
Fixes: OX-5352
Depends on https://github.com/scireum/sirius-kernel/pull/226

Implement "signalPut" in InterconnectCacheCoherence

---

src/main/java/sirius/biz/model/PermissionData.java
src/main/java/sirius/biz/packages/PackageData.java
src/main/java/sirius/biz/tenants/TenantData.java

Otherwise we might hit the row size limit for the sqltenant table.

Stores potentially long lists as CLOBs instead of inline varchars.

---

pom.xml

Use current sirius-web

---

src/main/java/sirius/biz/analytics/reports/Cells.java

Render cells with Enums values left aligned

---

src/main/java/sirius/biz/jobs/batch/SimpleBatchProcessJobFactory.java
src/main/java/sirius/biz/jobs/batch/SimpleReportBatchJobFactory.java
src/main/java/sirius/biz/jobs/interactive/ReportJobFactory.java

Unifying icon displayed for reports

---

src/main/java/sirius/biz/jobs/BasicJobFactory.java

Enforce required parameters with default to be validated when emptied

---

src/main/java/sirius/biz/process/ProcessContext.java
src/main/java/sirius/biz/process/ProcessEnvironment.java
src/main/java/sirius/biz/process/output/TableOutput.java

Usage snippets:
```java
// Table creation
TableOutput table = process.AddTable("name", "label").withColumn("name", "label")
.withColumn("name", "label")
.withColumn("name", "label") 
.build();
// Adding rows
table.addRow().withCell(foo)
.withCell(bar)
.build();

TableOutput column and row builder

---

src/main/resources/default/extensions/biz-menu/menu-jobs.html.pasta

Changes menu link to the new storage engine

---

src/main/java/sirius/biz/jobs/batch/file/LineBasedImportJob.java

Adds support for uppercase file names / file extensions.

---

src/main/java/sirius/biz/storage/VirtualObject.java
src/main/java/sirius/biz/storage/VirtualObjectVersion.java

Adds missing classes not covered by #620

Only enables the legacy versions framework if a SQLBlobStorage is active

---

pom.xml

See https://github.com/scireum/sirius-web/pull/687

Upgrades sirius-web with fix for integers in excel

---

src/main/java/sirius/biz/importer/BaseImportHandler.java
src/main/java/sirius/biz/jobs/batch/file/EntityImportJob.java
src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountImportHandler.java

- Removes imperformant crosschecks
- Provides an additional context to all methods of EntityImportJob
- Prevents bad overwritings of the inner workings of EntityImportJob

Further improves import handling

---

src/main/java/sirius/biz/jobs/Jobs.java
src/main/resources/default/taglib/w/jobs.html.pasta

Allows filtering the 'Matching jobs'-widget by a given query

---

pom.xml
src/main/java/sirius/biz/web/BizController.java
src/test/java/sirius/biz/cluster/RedisUserMessageCacheTest.groovy

SE-9177: Increases the sirius-web version

---

src/main/java/sirius/biz/codelists/CodeLists.java
src/main/java/sirius/biz/jobs/params/CodeListEntryParameter.java
src/main/java/sirius/biz/jobs/params/DateRangeParameter.java
src/main/resources/default/templates/biz/jobs/params/codelistentry.html.pasta

Introduces new job parameter types for DateRange and CodeListEntry objects.
Fixes: OX-5522

New DateRange and CodeListEntry job parameters

---

src/main/java/sirius/biz/jobs/params/DateRangeParameter.java
src/main/resources/default/templates/biz/jobs/params/daterange.html.pasta

The constructor can now accept a variable combination of items, making it no longer hard-coded.

Revamped the DateRange Parameter

---

src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
src/main/java/sirius/biz/jobs/batch/file/EntityExportJobFactory.java

...by overriding the `setFileName()` in the target EntityJobFactory

Adds the ability to override the filename when exporting entities

---

src/main/java/sirius/biz/web/BasePageHelper.java

Useful to be used by Batch Jobs to reuse the current query/filters from a page.

Adds a method to retrieve the query from the page helper

---

src/main/java/sirius/biz/analytics/metrics/mongo/MongoMetrics.java
src/main/java/sirius/biz/model/InternationalAddressData.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java

- "blob" field conflicts with the SQL standard
- ID column of mongo metrics need a value due to a newly created key constraint.

Two minor fixes

---

pom.xml

Prevents an NPE if the requested entity doesn't exist

Updates to the latest sirius dependencies

---

src/main/java/sirius/biz/model/InternationalAddressData.java

SE-9475 Adds a getter for the translated country to InternationalAddressData

---

src/main/java/sirius/biz/tenants/jdbc/SQLUserAccount.java

re-add necessary cast

---

pom.xml

Uses the newest sirius-db version

---

src/main/java/sirius/biz/storage/layer2/Blob.java
src/main/java/sirius/biz/storage/layer2/BlobController.java
src/main/java/sirius/biz/storage/layer2/BlobHardRef.java
src/main/java/sirius/biz/storage/layer2/BlobHardRefProperty.java
src/main/java/sirius/biz/storage/layer2/URLBuilder.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
src/main/resources/default/taglib/w/blobHardRefField.html.pasta

The UI provided is a rudimentary approach (mostly copied from storedObjectUploader.html.pasta) as a harsh timeframe was given. This will need some love+work in the near future.

SIRI-96: Provides a rudimentary UI for  BlobHardRefs

---

src/main/java/sirius/biz/analytics/events/EventRecorder.java
src/main/java/sirius/biz/storage/layer2/variants/ConversionEvent.java

Adds an event for blob conversion analytics

---

src/main/java/sirius/biz/web/DisasterModeInfo.java

Displays the maintenance message as a warning in the backend

---

src/main/java/sirius/biz/storage/s3/ObjectStore.java

If a stream is uploaded to S3, we now check its size. If it is
unknown or larger than 8 MB, we force a multipart upload.
If method is way more robust than performing a single upload,
as it can load all contents of a chunk in memory and then perform
an upload with the possibility of performing a retry in case of a transient
error signaled by s3. Also, we set the buffer for the remaining stream based
uploads to 8 MB so that these also fully fit into the local buffer and provide
the same retry capabilities.

Improves the stability of stream based uploads to S3.

---

src/main/java/sirius/biz/storage/s3/ObjectStore.java

When uploading a file to S3 using a multipart upload, the number of each part needs to be specified.

SIRI-217 Fixes S3 multipart uploads

---

src/main/java/sirius/biz/storage/layer2/URLBuilder.java

Also appends the download hook when generating a virtual download URL.

---

src/main/resources/biz_cs.properties
src/main/resources/biz_de.properties
src/main/resources/biz_en.properties
src/main/resources/biz_fr.properties
src/main/resources/biz_it.properties
src/main/resources/biz_nl.properties
src/main/resources/biz_pl.properties
src/main/resources/default/templates/biz/storage/list.html.pasta

SIRI-224: Added copy path action to file drop down menu

---

src/main/java/sirius/biz/importer/BaseImportHandler.java
src/main/java/sirius/biz/importer/format/ImportDictionary.java

Corresponding aliases will be deleted too
- Fixes: SE-9717

SE-9717: Added possibility to remove fields from ImportDictionary

---

pom.xml

Refreshes the sirius web version

---

pom.xml
src/main/java/sirius/biz/tenants/TenantController.java

... when packages and/or upgrades are present in the system configuration.
Fixes: OX-5985

Jumps to the package configuration screen after creating a tenant

---

src/main/java/sirius/biz/analytics/scheduler/AnalyticsBatchExecutor.java
src/main/java/sirius/biz/analytics/scheduler/AnalyticsSchedulerExecutor.java

Would have affected the metric-computers by always returning the current date instead of in console entered date.

Fixed Value class not recognizing String values as LocalDate

---

src/main/java/sirius/biz/process/SimpleProcessCommand.java

Includes boilerplate to run the process as simulation

Provides a baseline for simple processcommands with no arguments

---

pom.xml
src/main/java/sirius/biz/web/BizController.java

There were still some problems left after the recent refactoring and also this fix is needed for other properties as well.

Fixes loading for checkboxes (again)

---

src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java

Removes support for legacy url support for blobs

---

pom.xml
src/main/java/sirius/biz/process/Process.java
src/main/java/sirius/biz/process/ProcessContext.java
src/main/java/sirius/biz/process/ProcessEnvironment.java
src/main/java/sirius/biz/process/Processes.java

Differentiate between "normal" and admin only timings

---

src/main/java/sirius/biz/jobs/batch/file/ArchiveExportJob.java
src/main/java/sirius/biz/jobs/batch/file/FileExportJobFactory.java

Restricts archive exports to zip extension.

---

src/main/java/sirius/biz/jobs/batch/file/SimpleXMLValidator.java
src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java
src/main/java/sirius/biz/jobs/batch/file/XMLImportJobFactory.java
src/main/java/sirius/biz/jobs/batch/file/XMLValidator.java
src/main/java/sirius/biz/jobs/params/Parameter.java
src/main/resources/biz_de.properties
src/main/resources/biz_en.properties

Adds ability to validate XML files against specified XSD files

---

src/main/java/sirius/biz/tenants/TenantUserManager.java

TenantUserManager getUserSettings NPE fix

---

src/main/resources/default/taglib/w/blobHardRefField.html.pasta

SE-10049: Adds a preview img tag to blobHardRefField

---

src/main/java/sirius/biz/storage/layer2/BlobController.java
src/main/java/sirius/biz/storage/layer2/BlobHardRef.java
src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java
src/main/resources/default/assets/javascript/blobreffield.js
src/main/resources/default/assets/stylesheets/biz.scss
src/main/resources/default/extensions/wondergem-page/scripts.html.pasta
src/main/resources/default/extensions/wondergem-page/storage-vfs-modals.html.pasta
src/main/resources/default/taglib/w/blobSoftRefField.html.pasta
src/main/resources/default/taglib/w/filefield.html.pasta

Implement a taglib for selecting a file for a blobSoftRef

---

pom.xml
src/main/java/sirius/biz/model/QueryController.java

Adds a max time for fetching the total count in query tool

---

src/main/java/sirius/biz/codelists/CodeLists.java
src/main/java/sirius/biz/model/PersonData.java

Since it is possible in S2 to send e-mails to several addressees in different languages, they must be addressable in their respective language.

SE-10138: Cross-lingual handling of salutations

---

pom.xml

Dependency Upgrade

---

src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java

incompatible amount of columns (4) vs columnSettings (5)

Fixes the blob_sort_by_last_modified index

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java

- and add exception details to msg as well

Fix invalid formatting syntax

---

src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java

This now matches the SQL logic ...
Fixes: OX-6382

Correctly orders by last modified date in descending order

---

src/main/java/sirius/biz/util/ArchiveExtractor.java
src/main/java/sirius/biz/util/ExtractedZipFile.java

To be able to process these files multiple times as it often is done for xml files during import jobs

Changea ExtractedZipFile inputstream to supplier

---

src/main/resources/default/extensions/biz-menu/menu-documentation.html.pasta

Add /system/tags to the menu links

---

src/main/java/sirius/biz/analytics/metrics/mongo/MongoMetrics.java
src/main/java/sirius/biz/sequences/mongo/MongoSequenceStrategy.java
src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoProcessBlobChangesLoop.java
src/main/java/sirius/biz/tenants/mongo/MongoTenantAutoSetup.java
src/test/java/sirius/biz/importer/SQLTenantImportHandler.java

Needs: https://github.com/scireum/sirius-db/pull/391

Uses the new Mongo API which prevents error prone calls.

---

pom.xml

Bumps sirius-kernel dev-19.12 -> dev-20.0, sirius-web dev-30.0-rc2 -> dev-30.0-rc3, sirius-db dev-21.4 -> dev-21.5

Upgrades sirius dependencies

---

src/main/resources/default/taglib/w/codelistMultiSelect.html.pasta
src/main/resources/default/taglib/w/codelistSelect.html.pasta

- Requests CodeLists from Injector at runtime only

Relaxes Injection

---

pom.xml

web: dev-30.1.4 -> dev-30.1.5
db: dev-22.0 -> dev-23.0

Bumps sirius dependencies

---

src/main/resources/default/assets/javascript/multiLanguageField.js
src/main/resources/default/taglib/w/multiLanguageTextField.html.pasta

Sets the value of the multi language field in the user's language

---

pom.xml

(cherry picked from commit 3b678ecd8ce2267cb6790c11bf533c09a1171cb7)

Update to the latest sirius dependencies

---

src/main/java/sirius/biz/cluster/BackgroundInfo.java
src/main/java/sirius/biz/cluster/ClusterController.java
src/main/java/sirius/biz/cluster/NeighborhoodWatch.java
src/main/resources/default/templates/biz/cluster/cluster.html.pasta

In combination with the uptime this is a good indicator if all nodes are patched and running the new version during a patch.

Displays the versions the cluster nodes are currently running

---

pom.xml
src/main/java/sirius/biz/storage/layer3/VirtualFile.java
src/main/resources/biz_de.properties

This need https://github.com/scireum/sirius-kernel/pull/317

Adds a method to VirtualFile to resolve a path from a url and directly download the url into the path

---

docker-compose.yml
src/test/resources/docker-compose.yml

> https://scireum.myjetbrains.com/youtrack/issue/SIRI-299
- Upgrades S3 Ninja to 7.0

S3 Ninja Upgrade (SIRI-299)

---

src/main/resources/default/templates/biz/model/sql.html.pasta

the provided id field was from the singleSelect instead of the chosen select item

Fix broken executions of /system/sql

---

src/main/resources/default/extensions/wondergem-page/storage-vfs-modals.html.pasta

ymo found some bugs:
- pagination was only 5 items
- search does work with enter key, but not with the button
- when clicking on breadcrumbs, a js error occurred
Furthermore, the search field was not reset when changing directory, which doesn't make much sense

VFS Modal Bugfixing

---

src/main/java/sirius/biz/util/ArchiveHelper.java
src/main/java/sirius/biz/util/Extracted7ZFile.java
src/main/java/sirius/biz/util/ExtractedFileBuffer.java
src/main/java/sirius/biz/util/LocalArchiveExtractCallback.java
src/main/java/sirius/biz/util/SevenZipAdapter.java

(non breaking)
- Fixes: OX-6679

Fixes OOM (Java Heap Space) when Unzipping by Writing to File if necessary + Refactoring

---

src/main/resources/default/taglib/w/multiLanguageTextArea.html.pasta
src/main/resources/default/taglib/w/multiLanguageTextField.html.pasta

...when editing the MultiLanguageString is not enabled.

Actually sets the supplied name for the regular text field

---

src/main/java/sirius/biz/storage/layer1/DownloadManager.java
src/main/java/sirius/biz/storage/layer1/FSObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java
src/main/java/sirius/biz/storage/s3/ObjectStore.java
src/main/java/sirius/biz/util/ZipBuilder.java

ObjectStores and the ObjectStorageSpaces now support an asynchronous API to fetch objects.
Additionaly the DownloadManager can be used to download multiple files in parallel (if possible).
Finally the ZipBuilder can be used to create a ZIP archive (or more if an upper limit is reached).

Provides an async download API, a DownloadManager and a ZipBuilder for the storage framework.

---

src/main/java/sirius/biz/storage/layer1/DownloadManager.java
src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java

but the promise is still successful
Fixes: OX-6768

Invokes the failure consumer when no file is present

---

src/main/java/sirius/biz/codelists/CodeListLookupTable.java
src/main/java/sirius/biz/codelists/CodeLists.java
src/main/java/sirius/biz/codelists/IDBLookupTable.java
src/main/java/sirius/biz/codelists/LookupTable.java
src/main/java/sirius/biz/codelists/LookupValue.java
src/main/java/sirius/biz/codelists/LookupValueExtender.java
src/main/java/sirius/biz/codelists/LookupValueProperty.java
src/main/java/sirius/biz/codelists/LookupValues.java
src/main/java/sirius/biz/codelists/LookupValuesProperty.java
src/main/java/sirius/biz/codelists/README.md
src/main/java/sirius/biz/model/InternationalAddressData.java
src/main/java/sirius/biz/model/PersonData.java
src/main/java/sirius/biz/util/Countries.java
src/main/resources/biz_de.properties
src/main/resources/component-biz.conf

LookupValue and LookupValues can be used to store string colums or
lists in database entities while verifying or normalizing them using
LookupTables.

Provides LookupValue to reference LookupTables from database entities.

---

src/main/java/sirius/biz/protocol/DelegateJournalData.java

For an owning type+id and a target class
Fixes: SIRI-298

Adds a method to easily write journal entries

---

src/main/java/sirius/biz/codelists/LookupValuesProperty.java

`StringListProperty#getValueFromField` returns unmodifiable lists, so they cannot be cast to `LookupValues` then.
Please tell me, if there is a better way to replace the usage of `StringListProperty#getValueFromField` with what its parent does in `Property#getValueFromField`. 
Or maybe we can create and return a new `LookupValues`-object here that holds the same values as the unmodifiable list?

Prevents a ClassCastException with LookupValues

---

pom.xml
src/main/resources/default/extensions/biz-tycho-menu/menu-code-lists.html.pasta
src/main/resources/default/extensions/biz-tycho-menu/menu-jobs.html.pasta
src/main/resources/default/extensions/biz-tycho-menu/menu-protcols.html.pasta
src/main/resources/default/extensions/biz-tycho-menu/menu-system-tenant.html.pasta
src/main/resources/default/extensions/biz-tycho-menu/menu-tenants.html.pasta
src/main/resources/default/extensions/biz-tycho-menu/menu-user-logout.html.pasta
src/main/resources/default/extensions/biz-tycho-menu/menu-vfs.html.pasta
src/main/resources/default/extensions/tycho-page-menu/menu.html.pasta

This contains:
https://github.com/scireum/sirius-kernel/releases/tag/dev-22.0
https://github.com/scireum/sirius-web/releases/tag/dev-34.0
which are both breaking in terms of formatting and rounding Amount values.

BREAKING CHANGE: Updates to the latest sirius dependencies and adds common menu items to the new Tycho menus.

---

src/main/resources/default/extensions/biz-tycho-menu/menu-system-tenant.html.pasta

Tycho: Replaces some icons with their new FontAwesome names

---

src/main/java/sirius/biz/util/Languages.java

Exposes the default lookup table names for languages

---

pom.xml
src/main/java/sirius/biz/cluster/BackgroundInfo.java
src/main/java/sirius/biz/cluster/ClusterController.java
src/main/java/sirius/biz/cluster/NeighborhoodWatch.java
src/main/resources/default/templates/biz/cluster/cluster.html.pasta

Displays the short version string on the cluster page for all nodes

---

src/main/java/sirius/biz/codelists/LookupValue.java
src/main/java/sirius/biz/codelists/LookupValues.java

Adds public methods to retrieve display strings for LookupValue

---

src/main/resources/default/taglib/w/lookupValueSingleSelect.html.pasta
src/main/resources/default/taglib/w/lookupValuesMultiSelect.html.pasta

Enables bootstrap field styling for token autocomplete fields

---

.drone.yml
README.md

actives a message to memoio if nightly test or build fails

---

src/main/resources/default/taglib/w/lookupValue.html.pasta
src/main/resources/default/taglib/w/lookupValues.html.pasta

Adds optional parameter to lookupValue tag & shows multi suggestion earlier

---

pom.xml
src/main/resources/default/taglib/t/lookupValue.html.pasta
src/main/resources/default/taglib/t/lookupValues.html.pasta

Adds tycho templates for lookupValues

---

src/main/java/sirius/biz/translations/MultiLanguageStringExtender.java
src/main/java/sirius/biz/translations/MultiLanguageStringHelper.java

and adds a convenience method to the MultiLanguageStringHelper
Fixes: OX-6669

Prevents an UnsupportedOperationException in the MultiLanguageStringExtender

---

pom.xml
src/main/java/sirius/biz/codelists/CodeListController.java
src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java
src/main/java/sirius/biz/model/QueryController.java
src/main/java/sirius/biz/storage/legacy/StorageController.java
src/main/java/sirius/biz/tenants/TenantController.java
src/main/java/sirius/biz/tenants/UserAccountController.java

update web to have completionLables on autocompletes

---

src/main/java/sirius/biz/process/ErrorContext.java

Fixes non HandledException to log the context twice

---

pom.xml
src/main/java/sirius/biz/tenants/TenantController.java
src/main/java/sirius/biz/tenants/UserAccountController.java
src/main/resources/default/extensions/tycho-page-menu/footer.html.pasta
src/main/resources/default/extensions/tycho-page-menu/menu.html.pasta
src/main/resources/default/extensions/tycho-page/tenant-info.html.pasta
src/main/resources/default/extensions/wondergem-page/tenant-info.html.pasta

Shows a badge if the user or tenant is switched.

---

src/main/java/sirius/biz/importer/txn/ImportTransactionData.java
src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJob.java

Includes line number in relational import errors and wont auto import transaction ID

---

src/main/java/sirius/biz/analytics/events/ClickhousePartsReportJobFactory.java

Providing a merger to keep the already added values in the map.

Fix IllegalStateException

---

develop.conf
pom.xml
src/main/java/sirius/biz/tenants/TenantController.java
src/main/resources/default/extensions/wondergem-page-menu/footer.html.pasta

- depends on https://github.com/scireum/sirius-web/pull/893
- fixes: SIRI-396

extend wondergem footer for support-links, always redirect to given link

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java

Fallback to GET if a server responds with 501 or 503 on HEAD request

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java

Falls back to GET if the server responds with 405 METHOD_NOT ALLOWED

---

src/main/resources/default/assets/styles/biz-misc.scss
src/main/resources/default/assets/styles/tycho-biz.scss
src/main/resources/default/taglib/t/tracing.html.pasta

Adds Tycho tracing tag

---

pom.xml
src/main/resources/default/assets/scripts/multiLanguageField.js
src/main/resources/default/assets/scripts/tycho-biz.js.pasta
src/main/resources/default/assets/styles/multiLanguageField.scss
src/main/resources/default/assets/styles/tycho-biz.scss
src/main/resources/default/taglib/t/multiLanguageTextField.html.pasta

Fixes: SIRI-407
textArea will happen in a seperate PR along with going through all css styles if we can omit some or change to  predefined-classes

Copies&ports multiLanguageTextField to tycho

---

pom.xml
src/main/resources/default/assets/scripts/multiLanguageField.js
src/main/resources/default/assets/styles/multiLanguageField.scss
src/main/resources/default/taglib/t/multiLanguageTextArea.html.pasta

Adds multiLanguageTextArea tycho tag

---

pom.xml
src/main/java/sirius/biz/storage/layer3/downlink/ssh/SSHServer.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpCommand.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpCommandFactory.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpFileOpener.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpSourceStreamResolver.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpTargetStreamResolver.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeFileSystemAccessor.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeSeekableByteChannel.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeSftpSubsystem.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeSftpSubsystemFactory.java
src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplinkConnectorConfig.java

Breaking: 
- Some method signatures have changed. This should not affect regular consumers of sirius-biz.

Upgrade apache sshd lib and fix SFTP read error

---

src/main/resources/default/templates/biz/model/sql.html.pasta

Fix missing entity details on system/sql for only one result

---

src/main/java/sirius/biz/tycho/smart/EmailSmartValueProvider.java
src/main/java/sirius/biz/tycho/smart/EntityResolver.java
src/main/java/sirius/biz/tycho/smart/README.md
src/main/java/sirius/biz/tycho/smart/SmartValue.java
src/main/java/sirius/biz/tycho/smart/SmartValueProvider.java
src/main/java/sirius/biz/tycho/smart/SmartValueResolver.java
src/main/java/sirius/biz/tycho/smart/SmartValuesController.java
src/main/java/sirius/biz/tycho/smart/TenantResolver.java
src/main/java/sirius/biz/tycho/smart/TenantSmartValueProvider.java
src/main/java/sirius/biz/tycho/smart/UserAccountResolver.java
src/main/java/sirius/biz/tycho/smart/UserAccountSmartValueProvider.java
src/main/resources/default/assets/scripts/smartValues.js
src/main/resources/default/assets/scripts/tycho-biz.js.pasta
src/main/resources/default/assets/styles/smartValues.scss
src/main/resources/default/assets/styles/tycho-biz.scss
src/main/resources/default/taglib/t/smartValue.html.pasta

As an example, in the Tycho Processes-UI this is used to provide some context infos for the user/tenant which owns the process:

Provides the "SmartValues" framework.

---

pom.xml
src/main/resources/default/taglib/t/createButton.html.pasta

Adds a tag for a generic create button to a single url or a dropdown

---

pom.xml
src/main/java/sirius/biz/codelists/LookupTable.java
src/main/java/sirius/biz/codelists/LookupValue.java
src/main/java/sirius/biz/translations/MultiLanguageString.java
src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
src/main/java/sirius/biz/tycho/academy/mongo/MongoOnboardingEngine.java
src/main/java/sirius/biz/tycho/academy/mongo/MongoOnboardingVideo.java
src/main/java/sirius/biz/web/BizController.java
src/main/java/sirius/biz/web/ComplexLoadProperty.java
src/main/java/sirius/biz/web/ElasticPageHelper.java
src/main/java/sirius/biz/web/SaveHelper.java
src/main/resources/default/assets/scripts/lookupTables.js
src/main/resources/default/extensions/tycho-page/lookupTables.html.pasta
src/main/resources/default/taglib/k/section.html.pasta
src/main/resources/default/taglib/t/country.html.pasta
src/main/resources/default/taglib/t/countryFlag.html.pasta
src/main/resources/default/taglib/t/kbBtn.html.pasta
src/main/resources/default/taglib/t/langFlag.html.pasta
src/main/resources/default/taglib/t/lookupValue.html.pasta
src/main/resources/default/taglib/t/lookupValues.html.pasta
src/main/resources/default/templates/biz/cluster/cluster.html.pasta
src/main/resources/default/templates/biz/process/process-logs.html.pasta
src/main/resources/default/templates/biz/process/process-output-logs.html.pasta
src/main/resources/default/templates/biz/process/process.html.pasta
src/test/java/sirius/biz/translations/MongoMultiLanguageStringPropertySpec.groovy
src/test/java/sirius/biz/translations/SQLMultiLanguageStringEntity.java
src/test/java/sirius/biz/translations/SQLMultiLanguageStringPropertySpec.groovy

* Hides the description for a lookup table if none is present.
* Marks all JavaScript marker classes with the "-js" suffix.
* BREAKING: Properly enforces an expected type for BizController.findExistingForTenant
* Permits ComplexLoad properties to decide when to perform autoloading.
* Greatly simplifies loading values into a MultiLanguageString.
* Improves / adds helper tags to render languages/countries.
* Permits to properly handle partial creations of entities.
* Repairs the base URLs for process logs.
* Properly parses mongo IDs which are strings and not longs.
* Fixes video per track lookups for the MongoDB onboarding engine.

Misc improvements and fixes

---

src/main/java/sirius/biz/process/ProcessController.java

Adds a "has warnings" filter to the processes UI.

---

src/main/java/sirius/biz/jobs/batch/file/XMLValidator.java
src/main/resources/biz_de.properties
src/main/resources/biz_en.properties

limiting them to a max of 250 entries
Fixes: OX-7331

Categorizes and limits XSD validation messages in processes

---

pom.xml
src/main/java/sirius/biz/jobs/batch/entity/EntityBatchJob.java
src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
src/main/java/sirius/biz/jupiter/IDBTable.java
src/main/java/sirius/biz/model/ResaveEntitiesJobFactory.java
src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java

Requires: https://github.com/scireum/sirius-db/pull/453

Fixes the cross-reference list of a KnowledgeBaseArticle.

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java
src/main/resources/component-biz.conf

Verifies file extension to detect if a "real" file is present or "just" a server-sided script.

---

src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
src/main/java/sirius/biz/storage/layer3/TmpRoot.java

Allows to delete temporary files

---

src/main/java/sirius/biz/codelists/CustomLookupTable.java
src/main/java/sirius/biz/codelists/IDBFilteredLookupTable.java

Custom and filtered lookup tables now fall back to title and description of their base table

---

src/main/java/sirius/biz/mongo/CustomSortValues.java
src/main/java/sirius/biz/mongo/SortField.java
src/main/java/sirius/biz/mongo/SortValue.java

We need to annotate it with @NoJournal which lives in biz.
Other PR: https://github.com/scireum/sirius-db/pull/463

Moves SortField / SortValue from sirius-db.

---

src/main/java/sirius/biz/jupiter/JupiterSync.java
src/main/java/sirius/biz/storage/layer2/L3Uplink.java
src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
src/main/java/sirius/biz/storage/layer3/MutableVirtualFile.java
src/main/java/sirius/biz/storage/layer3/VirtualFile.java
src/main/resources/component-biz.conf

Limits the frequency in which VirtualFiles are downloaded from URLs & Enhances the options for Jupiter Sync.

---

src/main/java/sirius/biz/util/ArchiveExtractor.java

This allows to extract files that are not encoded as expected.
The log of a corresponding process looks something like this then:
Fixes: OX-7613

Falls back to 7zip if extraction via Java failed.

---

src/main/java/sirius/biz/process/Process.java
src/main/java/sirius/biz/process/ProcessController.java
src/main/java/sirius/biz/process/output/ProcessOutput.java
src/main/resources/default/templates/biz/process/process.html.pasta

which is only visible to admins
Fixes: OX-7702

Allows to mark a process output as system output

---

src/main/java/sirius/biz/process/Processes.java

Tries to compute monotonically increasing sort keys for high frequency logging in ProcessLog.

---

src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
src/main/java/sirius/biz/util/SevenZipAdapter.java

Fixes errors with unpacking archives using 7ZIP

---

docker-compose.yml
src/main/java/sirius/biz/jupiter/LRUCache.java
src/test/resources/docker-compose.yml

This as been added to Jupiter in: https://github.com/scireum/jupiter/pull/10

Adds support for LRU.PUTS / LRU.REMOVES as provided by Jupiter.

---

src/main/resources/default/assets/scripts/vfs-modals.js

Improves upload error handling of vfs file modal

---

src/main/java/sirius/biz/process/ErrorContext.java

ErrorContext: Retains message key and count hints, if a handled exception was annotated

---

src/main/java/sirius/biz/storage/layer1/replication/jdbc/SQLReplicationTask.java
src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTask.java
src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java

by adjusting its indices to represent the current queries
Fixes: SIRI-485

Improves the performance of ReplicationTask

---

pom.xml
src/main/java/sirius/biz/storage/layer2/BlobController.java
src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta

Fixes: OX-7873
Needs https://github.com/scireum/sirius-web/pull/972 for proper styling

Adds a tycho tag for hardRefFields for images

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java

Loads the correct file when path was resolved via get

---

src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java

so it can be directly accessed by custom import jobs.
Fixes: SIRI-499

Changes visibility of DictionaryBasedImport to public

---

src/main/java/sirius/biz/cluster/work/DistributedTasks.java
src/main/java/sirius/biz/jdbc/DatabaseController.java
src/main/resources/default/templates/biz/model/sql.html.pasta

Properly passes the selected database to the job when exporting a query from /system/sql.

---

src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java

from https://github.com/scireum/sirius-biz/pull/1322
Fixes: SIRI-499

Reverts visibility changes

---

src/main/java/sirius/biz/storage/layer3/VirtualFileSystem.java
src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplinksRoot.java
src/main/java/sirius/biz/storage/layer3/uplink/UplinkFactory.java
src/main/java/sirius/biz/storage/layer3/uplink/cifs/CIFSUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/fs/LocalDirectoryUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplinkConnectorConfig.java
src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplinkConnectorConfig.java
src/main/java/sirius/biz/storage/layer3/uplink/util/UplinkConnector.java
src/main/java/sirius/biz/storage/layer3/uplink/util/UplinkConnectorConfig.java

This provides convenient access to FTP or SFTP servers using a known API.

Permits to create temporary Uplinks via the VirtualFileSystem.

---

pom.xml
src/main/java/sirius/biz/cluster/NeighborhoodWatch.java
src/main/java/sirius/biz/cluster/RedisUserMessageCache.java
src/main/java/sirius/biz/elastic/ReindexJobFactory.java
src/main/java/sirius/biz/isenguard/RedisLimiter.java
src/main/java/sirius/biz/storage/layer3/uplink/util/UplinkConnectorPool.java

Needs: https://github.com/scireum/sirius-db/pull/484

Improves the ReindexJobFactory to be more stable.

---

src/main/resources/component-biz.conf

Adds a few languages

---

src/main/resources/default/templates/biz/storage/list.html.pasta

Calls the correct javascript function when moving files

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java

Retries delegating a conversion if a conversion host is down but multiple are available.

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java

This enhances commit 69b93d1c0e3222d3349874d3209bf154a577e94c

Properly notes connectivyIssue on retry

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java

Properly retries delegating blob download 

---

src/main/resources/default/assets/scripts/vfs-modals.js
src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta

Correctly encodes file name when uploading files

---

src/main/java/sirius/biz/ide/Scripting.java
src/main/java/sirius/biz/process/Processes.java
src/main/java/sirius/biz/process/output/TableOutput.java
src/main/java/sirius/biz/tenants/Tenants.java
src/main/resources/default/kb/en/system/scripting.html.pasta
src/main/resources/default/taglib/k/code.html.pasta

One now can start and use a process via:
```
part(Tenants.class).runAsAdminProcess('My Process', | ps | {
log('Hello From the Other Side');
});
```

Improves /system/scripting to directly report into a Process(Context).

---

src/main/java/sirius/biz/translations/MultiLanguageString.java
src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java

MultiLanguageString: transformValueFromImport only accepts valid languages

---

src/main/resources/default/taglib/t/lookupValue.html.pasta

Add parameter "showAddon" with default value "true".

---

src/main/resources/default/taglib/t/lookupValue.html.pasta
src/main/resources/default/taglib/w/lookupValue.html.pasta

Added parameter to set allowCustomEntries in lookupValue from template

---

pom.xml
src/main/java/sirius/biz/storage/s3/ObjectStore.java
src/main/resources/default/taglib/t/inlineLang.html.pasta
src/main/resources/default/taglib/t/lang.html.pasta

This can be used in page headers or within cards.
Fixes: OX-8388

Provides an inline version of t:lang.

---

src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta

Fixes: SIRI-561
Needs
- https://github.com/scireum/sirius-web/pull/1029

Warns when unloading while a file is uploading

---

src/main/java/sirius/biz/tenants/mongo/MongoTenantGlobalMetricComputer.java

Binds global tenant metric computation to correct framework

---

src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
src/main/resources/default/templates/biz/storage/list.html.pasta

Fixes: SIRI-573
Needs
- https://github.com/scireum/sirius-web/pull/1035

Adds dropzones to blobImageField and file list

---

src/main/java/sirius/biz/storage/layer2/Directory.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer3/FileSearch.java

Searches prefix in file extension if no file extension filter is given

---

pom.xml
src/main/java/sirius/biz/cluster/ClusterController.java
src/main/java/sirius/biz/codelists/LookupTable.java
src/main/java/sirius/biz/codelists/LookupValue.java
src/main/java/sirius/biz/codelists/LookupValues.java
src/main/java/sirius/biz/jobs/batch/file/LineBasedExport.java

Swagger Annotations and Deprecation Removal

---

pom.xml
src/main/java/sirius/biz/storage/layer3/VirtualFile.java

[OX-8755](https://scireum.myjetbrains.com/youtrack/issue/OX-8755)

Properly initiates a download for VirtualFile::deliverAsDownload.

---

pom.xml
src/main/java/sirius/biz/codelists/LookupValueProperty.java
src/main/java/sirius/biz/codelists/LookupValuesProperty.java

Fixes: OX-8593
Requires:
* https://github.com/scireum/sirius-db/pull/511

Provides a proper message value for lookup value based properties.

---

src/main/resources/default/templates/biz/tycho/page-footer-help.html.pasta
src/test/resources/docker-compose.yml

Adds a drop shadow for the support widget and updates test-containers.

---

src/main/resources/default/taglib/k/link.html.pasta

Improves the versatility of the link tag

---

pom.xml
src/main/resources/default/templates/biz/jobs/job.html.pasta
src/main/resources/default/templates/biz/jobs/params/lookuptable.html.pasta
src/main/resources/default/templates/biz/jobs/params/paramSingleSelect.html.pasta

Breaking because it requires sirius-web `dev-54.0.0` or higher

SIRI 595 Migrate Sirius-Web, fix double nesting detail.detail

---

src/main/java/sirius/biz/jobs/BasicJobFactory.java
src/main/java/sirius/biz/jobs/JobFactory.java
src/main/resources/default/assets/scripts/vfs-modals.js
src/main/resources/default/taglib/t/fileField.html.pasta
src/main/resources/default/templates/biz/jobs/job.html.pasta

The bugfixes are each separated in a proper commit

SIRI-595: Tycho Jobs Bugfixes

---

src/main/resources/default/taglib/k/image.html.pasta

Fixes image width being wider than its parent container

---

src/main/java/sirius/biz/jobs/interactive/ReportJobFactory.java

Fixes: [OX-9090](https://scireum.myjetbrains.com/youtrack/issue/OX-9090)

Fixes another job icon for wondergem

---

pom.xml

https://cwe.mitre.org/data/definitions/400.html

Updates to the latest snake-yaml.

---

src/main/java/sirius/biz/jobs/params/FileParameter.java

Fixes file parameter for non existent parent

---

src/main/java/sirius/biz/jupiter/JupiterSync.java

Otherwise, if a loader is moved, it will first load the updated data and then delete itself (e.g. an IDB table).

Delays updates after deletes in a Jupiter repository.

---

pom.xml
src/main/java/sirius/biz/i5/I5MetricProvider.java
src/main/java/sirius/biz/jobs/JobsController.java
src/main/java/sirius/biz/model/QueryController.java
src/main/java/sirius/biz/process/ProcessController.java
src/main/java/sirius/biz/process/Processes.java
src/main/resources/component-biz.conf

We now properly document the service to start jobs and to check the state of processes.
We also provide an entity query API for testing purposes.
Depends on:
* https://github.com/scireum/sirius-web/pull/1106

Properly document and extends services provided by biz.

---

src/main/java/sirius/biz/model/QueryController.java
src/main/resources/component-biz.conf

Fixes: [SIRI-631](https://scireum.myjetbrains.com/youtrack/issue/SIRI-631)

Allows the query api everywhere but prod

---

pom.xml

Upgrades sirius libraries to latest versions

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLDirectory.java

Mark deletion-ignoring relations as weak

---

src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js

Recreates dropzone when opening vfs modal to allow multiple uploads

---

pom.xml
src/main/java/sirius/biz/jobs/JobsController.java

Requires:
* https://github.com/scireum/sirius-web/pull/1126

Uses the new error handling / HTTP Status code capabilities of sirius-web

---

src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js
src/main/resources/default/taglib/t/fileField.html.pasta

OX-9234: Improvements to fileparameter upload

---

src/main/resources/default/taglib/t/fileField.html.pasta

If the basePath is root, don't show upload box

---

src/main/resources/default/extensions/tycho-page-menu/footer.html.pasta
src/main/resources/default/extensions/wondergem-page-menu/footer.html.pasta

Adds proper URI encoding.

---

src/main/java/sirius/biz/jobs/interactive/TimeseriesChartJobFactory.java
src/main/java/sirius/biz/tycho/updates/UpdatesReport.java

SIRI-663 fix upper/lowercases in NLS-keys, use NLS instead of $

---

src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js
src/main/resources/default/taglib/t/fileField.html.pasta

Only allows upload if files are allowed in the file parameter

---

pom.xml
src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js

Fixes not working in safari browser
Fixes: SIRI-666

Uses sirius method to detect if drag event is leaving window

---

src/main/java/sirius/biz/codelists/CodeLists.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeSftpSubsystem.java

For
- FTP Errors
- Code list warnings

Improve log messages

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/Blob.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java

Fixes: [OX-9323](https://scireum.myjetbrains.com/youtrack/issue/OX-9323/Video-Modernisierung-Optimierung-des-Verarbeitungsjobs-Processing)

Adds the capability to create variants of a blob by a newly introduced method

---

src/main/java/sirius/biz/storage/layer2/BlobChangedHandler.java
src/main/java/sirius/biz/storage/layer2/BlobCreatedRenamedHandler.java
src/main/java/sirius/biz/storage/layer2/BlobParentChangedHandler.java

Extracts super-interface for BlobChangedHandlers

---

src/main/resources/default/templates/biz/tenants/profile.html.pasta
src/main/resources/default/templates/biz/tenants/tenant-details-fields.html.pasta
src/main/resources/default/templates/biz/tenants/tenant-details.html.pasta
src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta

fix missing refactoring in templates for #1561

---

src/main/resources/default/taglib/t/blobImage.html.pasta

Makes it easier to style the img
Fixes: [OX-9321](https://scireum.myjetbrains.com/youtrack/issue/OX-9321)

Adds the imgClass argument which allows to provide additional classes to apply to the img

---

src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
src/main/java/sirius/biz/jobs/params/ParameterBuilder.java

Hides auxillary Files Parameter if no zip file is present 

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java

Fixes: [OX-9462](https://scireum.myjetbrains.com/youtrack/issue/OX-9462)

Correctly formats the last modified millis to a local date time

---

src/main/resources/default/kb/de/user/response-codes.html.pasta
src/main/resources/default/kb/en/user/response-codes.html.pasta

(Ported from OX)
Fixes: [SIRI-705](https://scireum.myjetbrains.com/youtrack/issue/SIRI-705)

Adds KBA about API response codes.

---

src/main/java/sirius/biz/analytics/charts/explorer/EventTimeSeriesComputer.java

(If the granularity is set to MONTH. In all other cases, the events are crunched..)

Permits to use pre-computed monthly metrics in an EventTimeSeriesComputer

---

src/main/java/sirius/biz/model/QueryController.java

Outputs the counts in query tool in a more readable form

---

src/main/resources/default/taglib/t/associatedProcesses.html.pasta

Fixes: [OX-9511](https://scireum.myjetbrains.com/youtrack/issue/OX-9511)

Adds the referencedLabel argument to the associatedProcesses tag which defines the reference label for the query

---

src/main/resources/default/taglib/t/associatedProcesses.html.pasta

Fixes: [OX-9511](https://scireum.myjetbrains.com/youtrack/issue/OX-9511)

Displays the canceled date when the job has not been completed properly (and therefore completed has not been set)

---

src/main/resources/default/templates/biz/model/query-header.html.pasta

beautify system/query for small width

---

src/main/java/sirius/biz/codelists/CodeListController.java
src/main/java/sirius/biz/web/BasePageHelper.java

enable search for codelist-autocomplete, fix typo

---

src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js

SIRI-709 dropzone progress

---

src/main/resources/default/templates/biz/tycho/academy/video-card.html.pasta

Fixes: [OX-9555](https://scireum.myjetbrains.com/youtrack/issue/OX-9555/Video-Modernisierung-Offene-Punkte)

Adjusts the playtime icon for videos within the video academy to match the icon within the video content section

---

src/main/java/sirius/biz/storage/layer2/Blob.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java

Fixes: [OX-9555](https://scireum.myjetbrains.com/youtrack/issue/OX-9555/Video-Modernisierung-Offene-Punkte)

Adds a getter for the file extension of a blob

---

pom.xml
src/main/java/sirius/biz/cluster/ClusterController.java
src/main/java/sirius/biz/cluster/NeighborhoodWatch.java

Fixes: [SIRI-731](https://scireum.myjetbrains.com/youtrack/issue/SIRI-731/NLS-convertDuration-refactorn)

Bumps up sirius-kernel and fixes breaking changes

---

src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js

Fixes: [SIRI-715](https://scireum.myjetbrains.com/youtrack/issue/SIRI-715/Ruckfrage-beim-Wegnavigieren-vom-Dateiupload-fur-Dateiimporte-z.B.-Videos)

Adds a warning popup when someone tries to leave the page while a file is uploaded

---

src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
src/main/resources/default/templates/biz/storage/list.html.pasta

use required, because input-required isn´t present in tycho and set placeholder

---

src/main/resources/default/templates/biz/cluster/cluster.html.pasta
src/main/resources/default/templates/biz/model/schema.html.pasta
src/main/resources/default/templates/biz/protocol/errors.html.pasta
src/main/resources/default/templates/biz/protocol/protocol.html.pasta
src/main/resources/default/templates/biz/storage/list.html.pasta

use text-muted for tycho-templates as muted isn´t present anymore

---

src/main/resources/default/templates/biz/model/sql.html.pasta

this avoid errors in browser-log for `data.rows.length is not defined`

add check for undefined result if result is empty

---

src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java

similar to https://github.com/scireum/sirius-web/pull/1146
Fixes: [SIRI-726](https://scireum.myjetbrains.com/youtrack/issue/SIRI-726)

Ignores ClosedChannelException.

---

src/main/resources/default/templates/biz/tenants/saml-complete.html.pasta
src/main/resources/default/templates/biz/tenants/saml.html.pasta

bring /saml to tycho without jquery

---

src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/util/ListUplinkConnectorsCommand.java

Fixes: [OX-9618](https://scireum.myjetbrains.com/youtrack/issue/OX-9618)

FTP Uplink: Return borrowed uplink even when error occurs

---

src/main/resources/default/taglib/t/chartsBtn.html.pasta

Permits to provide a custom button class for t:chartsBtn

---

src/main/java/sirius/biz/cluster/BackgroundInfo.java
src/main/java/sirius/biz/cluster/ClusterController.java
src/main/resources/default/templates/biz/cluster/cluster.html.pasta

Allows to open node-pinned URLs on cluster page

---

src/main/resources/default/templates/biz/cluster/cluster.html.pasta

Fixes: [SIRI-754](https://scireum.myjetbrains.com/youtrack/issue/SIRI-754)

Adds dropdown item to node card with new node-pinned link

---

src/main/java/sirius/biz/analytics/events/EventRecorder.java

Adds a helper-method commonly used when computing metrics.

---

src/main/resources/default/taglib/t/createButton.html.pasta
src/main/resources/default/templates/biz/jobs/scheduler/entries.html.pasta
src/main/resources/default/templates/biz/jobs/scheduler/entry.html.pasta
src/main/resources/default/templates/biz/storage/list.html.pasta

tycho enhancements

---

src/main/resources/default/taglib/t/createButton.html.pasta

SIRI-769 add missing classes for t:createButton

---

src/main/resources/default/templates/biz/jobs/scheduler/entry.html.pasta
src/main/resources/default/templates/biz/process/process.html.pasta

also see https://github.com/scireum/sirius-web/pull/1198
- fixes: SIRi-769

Adds classes for better look

---

src/main/resources/default/templates/biz/codelists/code-list-details.html.pasta
src/main/resources/default/templates/biz/codelists/code-list-entries.html.pasta
src/main/resources/default/templates/biz/codelists/code-list-entry.html.pasta
src/main/resources/default/templates/biz/codelists/code-list.html.pasta
src/main/resources/default/templates/biz/codelists/code-lists.html.pasta

Overview
new List
List-Details
List-Entries
New Entry
Entry details
- fixes: SIRI-773

Brings UI for Code-lists to Tycho

---

src/main/resources/default/templates/biz/model/query-header.html.pasta

Simplifies copying a query link to share with others or to adjust for comparison in another tab.

/system/query: Appends query parameters to the URL on submit

---

src/main/java/sirius/biz/codelists/LookupTableParameter.java

> https://scireum.myjetbrains.com/youtrack/issue/OX-9797
In certain scenarios, custom properties may not be advertised, and are thus not auto-completable. A user can be enabled to manually select them as a parameter if the new option is set.

Custom Values in Lookup Table Parameter

---

src/main/java/sirius/biz/web/BizController.java
src/main/resources/component-biz.conf

Config.
``` yaml
complex-deletes {
poolSize = 2
queueLength = 200
}
```
Fixes: [SIRI-778](https://scireum.myjetbrains.com/youtrack/issue/SIRI-778)

Spawn complex-delete processes in its own executor

---

src/main/java/sirius/biz/storage/s3/ObjectStore.java

Fixes a format string

---

src/main/java/sirius/biz/tycho/UserAssistant.java

Properly checks if a setting is present, before reading it.

---

src/main/resources/biz_de.properties
src/main/resources/default/taglib/t/videoAcademyBtn.html.pasta
src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta

**Assistant Buttons before:**
**Assistant Buttons after:**

Minor Fixes

---

src/main/java/sirius/biz/process/logs/ProcessLog.java
src/main/java/sirius/biz/protocol/JournalData.java

See https://github.com/scireum/sirius-biz/pull/1686 for a description.
Fixes: [SIRI-786](https://scireum.myjetbrains.com/youtrack/issue/SIRI-786)

Temporarily reduces more ES message fields

---

src/main/java/sirius/biz/jobs/JobsController.java
src/main/resources/biz_de.properties

SIRI-772 display message and don´t log calls to not-existing job

---

src/main/java/sirius/biz/analytics/events/EventRecorder.java

Provides possibility to count distinct values of a given field in queried events.
This is useful to e.g. determine the number of distinct entities that triggered certain events.
Fixes: [OX-9910](https://scireum.myjetbrains.com/youtrack/issue/OX-9910)

EventRecorder: Allows counting distinct event field values

---

src/main/java/sirius/biz/storage/layer3/FileQuickActionProvider.java
src/main/java/sirius/biz/storage/layer3/JobFileQuickActionProvider.java
src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
src/main/resources/default/templates/biz/storage/list.html.pasta

Also makes use of the newly added mechanism to add file based job quick actions to the list (to each addition action of each file).
Fixes: [OX-9929](https://scireum.myjetbrains.com/youtrack/issue/OX-9929/Umsetzung-Arbeitsverzeichnis-mit-Kontext-Option-Inhalt-anlegen-erweitern)

Adds an mechanism to add custom quick actions to the vfs (media pool) list

---

src/main/java/sirius/biz/analytics/reports/ListCellFormat.java
src/main/java/sirius/biz/codelists/LookupTable.java
src/main/java/sirius/biz/translations/MultiLanguageString.java
src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java

Fixes: [SIRI-736](https://scireum.myjetbrains.com/youtrack/issue/SIRI-736)

Small improvements/fixes to JSON handling via Jackson

---

src/main/java/sirius/biz/analytics/reports/Cells.java
src/main/java/sirius/biz/jobs/JobConfigData.java

Functionality that was affected:
* Applying Job Templates did not work correctly (" artefacts, selection paramss got cleared)
* Parameter descriptions in the job documentation were not rendered
Fixes: [SIRI-736](https://scireum.myjetbrains.com/youtrack/issue/SIRI-736)

Jackson: Fixes Small Bugs in Job Framework

---

docker-compose.yml
src/test/resources/docker-compose.yml

Fixes: [OX-9994](https://scireum.myjetbrains.com/youtrack/issue/OX-9994)

Upgrades ClickHouse Container to 23.4.2.11

---

src/main/java/sirius/biz/codelists/LookupTableEntry.java

**Before:**
**After:**
Fixes: [SIRI-736](https://scireum.myjetbrains.com/youtrack/issue/SIRI-736)

Correctly converts the entry source from JSON to YAML for display in modal

---

src/main/java/sirius/biz/tenants/BaseTenantAutoSetup.java
src/main/java/sirius/biz/tenants/TenantData.java
src/main/java/sirius/biz/tenants/UserAccount.java
src/main/java/sirius/biz/tenants/UserAccountData.java
src/main/java/sirius/biz/tenants/jdbc/SQLTenantUserManager.java
src/main/java/sirius/biz/tenants/jdbc/SQLUserAccount.java
src/main/java/sirius/biz/tenants/mongo/MongoTenantUserManager.java
src/main/java/sirius/biz/tenants/mongo/MongoUserAccount.java
src/main/resources/component-biz.conf

Adds support for user-preferences and fixes a caching bug in the TenantUserManager and extends tenant auto-setup

---

src/main/java/sirius/biz/analytics/metrics/ComputeParameters.java
src/main/java/sirius/biz/analytics/metrics/DailyMetricComputer.java
src/main/java/sirius/biz/analytics/metrics/MetricComputerContext.java
src/main/java/sirius/biz/analytics/metrics/MonthlyLargeMetricComputer.java
src/main/java/sirius/biz/analytics/metrics/MonthlyMetricComputer.java
src/main/java/sirius/biz/analytics/metrics/jdbc/SQLDailyGlobalMetricComputer.java
src/main/java/sirius/biz/analytics/metrics/jdbc/SQLMonthlyGlobalMetricComputer.java
src/main/java/sirius/biz/analytics/metrics/mongo/MongoDailyGlobalMetricComputer.java
src/main/java/sirius/biz/analytics/metrics/mongo/MongoMonthlyGlobalMetricComputer.java
src/main/java/sirius/biz/process/ProcessesDailyMetrics.java
src/main/java/sirius/biz/process/ProcessesMonthlyMetrics.java
src/main/java/sirius/biz/tenants/jdbc/SQLTenantGlobalMetricComputer.java
src/main/java/sirius/biz/tenants/metrics/computers/TenantMetricComputer.java
src/main/java/sirius/biz/tenants/metrics/computers/UserAccountAcademyMetricComputer.java
src/main/java/sirius/biz/tenants/metrics/computers/UserAccountActivityMetricComputer.java
src/main/java/sirius/biz/tenants/mongo/MongoTenantGlobalMetricComputer.java

> https://scireum.myjetbrains.com/youtrack/issue/SIRI-795

Analytics: Scheduling Fixes

---

src/main/java/sirius/biz/process/logs/ProcessLog.java
src/main/java/sirius/biz/protocol/JournalData.java
src/main/java/sirius/biz/protocol/Protocols.java
src/main/resources/component-biz.conf

These workarounds are no longer needed after upgrading ES to 8.7.1
See:
- https://github.com/scireum/sirius-biz/pull/1724
Fixes: [SIRI-793](https://scireum.myjetbrains.com/youtrack/issue/SIRI-793)

ES Upgrade - Removes TODOs

---

src/main/java/sirius/biz/jobs/batch/file/XMLExportJobFactory.java

Changes the accepted file extension for XML-Exports to "zip"

---

src/main/resources/default/templates/biz/tycho/academy/tracks.html.pasta

Displays proper message if there are no video academy tracks

---

src/main/resources/default/templates/biz/model/query-results.html.pasta

Fixes query tool when framework `biz.tenants` is disabled.

Query Tool Fix

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java

When downloading files, we check if the `content-type` is `text/html`. This is a strong indication we got no binary (an image, video, document or the like) but landed in a regular HTML page, and we do not want that HTML page saved as payload of the download attempt.
Fixes: [OX-9757](https://scireum.myjetbrains.com/youtrack/issue/OX-9757)

Checks the content-type received in VirtualFile.loadFromOutcall

---

pom.xml
src/main/java/sirius/biz/tenants/mongo/MongoTenantController.java

Requires:
* https://github.com/scireum/sirius-web/pull/1233
Fixes: SIRI-828

Hides deprecated additional features for which no translations exists.

---

src/main/java/sirius/biz/tenants/TenantController.java
src/main/resources/default/taglib/t/tracing.html.pasta
src/main/resources/default/templates/biz/packages/packages-and-upgrades.html.pasta
src/main/resources/default/templates/biz/tenants/select-tenant.html.pasta
src/main/resources/default/templates/biz/tenants/select-user-account.html.pasta
src/main/resources/default/templates/biz/tenants/tenant.html.pasta
src/main/resources/default/templates/biz/tenants/tenants-list.html.pasta
src/main/resources/default/templates/biz/tenants/tenants.html.pasta
src/main/resources/default/templates/biz/tenants/user-account.html.pasta
src/main/resources/default/templates/biz/tenants/user-accounts-list.html.pasta
src/main/resources/default/templates/biz/tenants/user-accounts.html.pasta

Addresses several requests from initial feedback to the new tenant/user UI.
See individual commits for further details.
Fixes: [SIRI-606](https://scireum.myjetbrains.com/youtrack/issue/SIRI-606)
Note: empty addresses are merely an edge-case in prod environments

Tycho Tenant/User UI Feedback

---

src/main/resources/default/templates/biz/storage/list.html.pasta

Before:
After:
Fixes: [SIRI-833](https://scireum.myjetbrains.com/youtrack/issue/SIRI-833/Quick-Actions-in-fs-umstrukturieren)

Changes the position of the quick action and adds sections to add divider

---

src/main/java/sirius/biz/elastic/ElasticIndexSizeReportJobFactory.java

Reads index json from proper fieldname

Fixes ES Index Health Job

---

src/main/resources/biz_de.properties
src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
src/main/resources/default/templates/biz/tenants/user-accounts.html.pasta

Fixes: [OX-10131](https://scireum.myjetbrains.com/youtrack/issue/OX-10131)
Also fixes a wrong URL in filters for user-accounts

Tycho: Displays save hint after changes to a blobHardRefField

---

src/main/java/sirius/biz/tenants/Tenant.java
src/main/java/sirius/biz/tenants/flags/CustomizationFlag.java
src/main/java/sirius/biz/tenants/flags/CustomizationFlags.java
src/main/java/sirius/biz/tenants/flags/README.md
src/main/java/sirius/biz/tenants/jdbc/SQLTenant.java
src/main/java/sirius/biz/tenants/mongo/MongoTenant.java
src/main/resources/default/kb/en/admin/customization-flags.html.pasta

This has been ported from OXOMI were we used it to accommodate several migrations / modernization projects.

Provides a framework to check customization flags.

---

src/main/resources/biz_de.properties
src/main/resources/default/templates/biz/tenants/tenants-list.html.pasta
src/main/resources/default/templates/biz/tenants/user-account.html.pasta
src/main/resources/default/templates/biz/tenants/user-accounts-list.html.pasta

Improves the UIs for tenants and user-accounts

---

src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java

- use smart method checking if MLSD or LIST is to be used
Fixes: SIRI-835

Use proper method for ftp access when checking for readonly

---

src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java

- the assumption is, that the user should be able to do at least "something" on given files/directories
- if this is not the case, we assume the permissions are missing and allow everything for the user
Fixes: SE-835

Fixes permissions check for FTP servers not delivering any information

---

src/main/java/sirius/biz/tenants/mongo/MongoTenantExportJobFactory.java

Fixes: [OX-10040](https://scireum.myjetbrains.com/youtrack/issue/OX-10040)

Executes the tenant export job in the original tenant while spying another user

---

src/main/resources/default/templates/biz/tenants/user-account.html.pasta
src/main/resources/default/templates/biz/tenants/user-accounts-list.html.pasta

Makes sure that the delete button is only rendered when the user has the associated permission

---

src/main/java/sirius/biz/analytics/events/EventRecorder.java

Fixes: [OX-10252](https://scireum.myjetbrains.com/youtrack/issue/OX-10252/LogWatch-Portal-Inhalte-Exporte-werfen-Fehler-beim-Export-von-Statistiken)

Adds three helper methods for counting events in the last month, last year and last 12 months

---

pom.xml
src/main/java/sirius/biz/analytics/events/EventRecorder.java
src/main/resources/default/templates/biz/tenants/user-account.html.pasta
src/main/resources/default/templates/biz/tenants/user-accounts-list.html.pasta

Merge hotfix into develop

---

pom.xml
src/main/resources/default/templates/biz/tenants/tenant-config.html.pasta
src/main/resources/default/templates/biz/tenants/user-account-config.html.pasta

unify config-editor and use t:codeEditor including css-height-fixes from sirius-web

---

pom.xml
src/main/java/sirius/biz/importer/format/ImportDictionary.java
src/main/java/sirius/biz/mongo/SortField.java
src/main/java/sirius/biz/storage/layer2/URLBuilder.java
src/main/java/sirius/biz/storage/legacy/Storage.java

Fixes: [SIRI-580](https://scireum.myjetbrains.com/youtrack/issue/SIRI-580)

Sirius Upgrade + Deprecation Replacement

---

src/main/resources/default/templates/biz/tenants/tenant-config.html.pasta
src/main/resources/default/templates/biz/tenants/user-account-config.html.pasta

after the .then()-block it wouldn´t be called correctly and has no effect on the page

move editor.resize() to proper location

---

pom.xml
src/main/java/sirius/biz/analytics/reports/CSSCellFormat.java
src/main/java/sirius/biz/analytics/reports/Cells.java
src/main/java/sirius/biz/analytics/reports/LinkCellFormat.java
src/main/java/sirius/biz/analytics/reports/ListCellFormat.java
src/main/java/sirius/biz/analytics/reports/TrendCellFormat.java
src/main/java/sirius/biz/tycho/search/OpenSearchResult.java

- Reacts to breaking changes from https://github.com/scireum/sirius-web/pull/1262

Replaces usages of ContentHelper with equivalents from StringCleanup

---

src/main/java/sirius/biz/analytics/events/EventRecorder.java

Adds a method which counts the number of events which have occurred in the given calendar month based on the given queryTuner

---

pom.xml
src/main/java/sirius/biz/ide/Scripting.java
src/main/java/sirius/biz/jdbc/DatabaseController.java
src/main/resources/default/templates/biz/model/sql.html.pasta

**SQL Query Tool:**
**Logging output:**

SQL: Switches query input field to textarea

---

src/main/java/sirius/biz/web/BasePageHelper.java

For a coherent view in different Tycho card pages the limit is adjusted
fixes: SIRI-802

Reduces elements per page from 25 to 24

---

src/main/java/sirius/biz/analytics/metrics/BasicMetrics.java
src/main/java/sirius/biz/analytics/metrics/Metrics.java

Adds a convenient method to the Metrics framework which fetches the metric values of the last 12 months for the given entity

---

src/main/resources/default/assets/javascript/multiLanguageField.js
src/main/resources/default/assets/scripts/multi-language-field.js

This makes working with such fields a bit easier as it reduces required mouse movement and number of clicks.
https://github.com/scireum/sirius-biz/assets/2427877/1daf1048-3741-4e69-8dc4-7928576a2b78

Focuses first field im MLS modal when it is opened

---

src/main/java/sirius/biz/tycho/kb/KnowledgeBase.java
src/main/java/sirius/biz/tycho/kb/README.md
src/main/resources/component-biz.conf

BREAKING: KBA - Remodels the fallback language mechanism for the knowledgebase system in order to support multiple fallback languages

---

src/main/java/sirius/biz/tycho/kb/KnowledgeBase.java
src/main/resources/default/kb/00000.html.pasta

Fixes a missing method reference which was caused when changing the default language selection

---

pom.xml
src/main/java/sirius/biz/web/SaveHelper.java

Allows to optionally suppress the `bizController.showSavedMessage()` call.

Save Helper: Optional Suppression of Save Message

---

src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta

For example:
Fixes: https://scireum.myjetbrains.com/youtrack/issue/SIRI-861

SIRI-861: Adds support of displaying an appropriate Icon as Preview to Upload Fields 

---

pom.xml
src/main/java/sirius/biz/model/ContactData.java

Means the field only gets validated when it's value has changed
Fixes: SIRI-869
See: https://github.com/scireum/sirius-db/pull/591

Changes ContactData phonenumber validation to non-strict

---

src/main/resources/default/assets/scripts/blob-upload-url-popover.js
src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta

Fixes updating the preview for URLs by utilizing a callback function (implemented in a non breaking way).

SIRI-861: Minor Blob Upload Fix

---

src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta

The history handling hat two major issues with these settings:
- They introduced a duplicate history state when changed
- The default value was not properly restored
Fixes: [SIRI-791](https://scireum.myjetbrains.com/youtrack/issue/SIRI-791)

Data Explorer: Properly handles range and period in history

---

src/main/java/sirius/biz/jobs/params/MultiSelectParameter.java
src/main/java/sirius/biz/jobs/params/MultiSelectStringParameter.java
src/main/java/sirius/biz/jobs/presets/JobPresetsController.java
src/main/resources/default/templates/biz/jobs/job-parameters-logic.html.pasta
src/main/resources/default/templates/biz/jobs/job.html.pasta
src/main/resources/default/templates/biz/jobs/params/selectMultiString.html.pasta

This fixes various issues of multi-select parameters:
- Storing a preset with multiple selected values
- Loading a preset with multiple selected values
- Updating other parameters based on the selected values of a multi-select parameter
To limit changing the fundamental logic, e.g. the framework relies on a Map<String, String> as the context for the most part, where required lists will be transformed to strings separated by the pipe-character. This results in the commits being non-breaking.
Fixes: [SIRI-873](https://scireum.myjetbrains.com/youtrack/issue/SIRI-873)

SIRI-873: Multi-Select Job Parameter Fixes

---

pom.xml
src/main/java/sirius/biz/tycho/smart/TenantSmartValueProvider.java

Tycho: Adds option to edit a smart value tenant

---

pom.xml
src/main/resources/default/assets/scripts/smart-values.js
src/main/resources/default/extensions/tycho-page-menu/footer.html.pasta
src/main/resources/default/taglib/k/section.html.pasta
src/main/resources/default/templates/biz/storage/list.html.pasta

Fixes: [SIRI-880](https://scireum.myjetbrains.com/youtrack/issue/SIRI-880)

BREAKING: Uses new sirius JS clipboard helper

---

develop.conf

We don't have access to our full blown codelists when starting biz standalone so we provide some values for testing.

Provides some codelist values for local testing

---

src/main/java/sirius/biz/codelists/LookupTable.java

- This PR fixes or works on following ticket(s): [SIRI-857](https://scireum.myjetbrains.com/youtrack/issue/SIRI-857)

Permits sorting lookup values by a given field.

---

.drone.yml
pom.xml
src/main/java/sirius/biz/ide/Scripting.java
src/main/java/sirius/biz/jobs/batch/file/XMLValidator.java
src/main/java/sirius/biz/locks/Locks.java
src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/s3/ObjectStores.java
src/main/java/sirius/biz/tycho/updates/UpdatesReport.java

Ensure JDK 21 (e. g. temurin-21) is installed on the system

Switch project to Java 21

---

src/main/java/sirius/biz/web/BizController.java

We often have the combination of an overview page `/entities` and respective details pages like `/entity/123`. In Tycho, we may want to provide certain actions that need to work from both locations, for instance archiving or unarchiving. The respective routes for such actions need to redirect smartly to wherever the call came from.
This PR adds convenience methods that redirect back to the referer, maintaining possible query parameters, after having checked the location.
https://github.com/scireum/memoio/pull/2552

Redirect to Safe Referers

---

pom.xml

...because of unknown issues with the current versions.
Change logs:
- Version 2.9.2 to 2.10.0: https://github.com/apache/mina-sshd/blob/master/docs/changes/2.10.0.md
- Version 2.10.0 to 2.11.0: https://github.com/apache/mina-sshd/blob/master/docs/changes/2.11.0.md
(no ticket)
- This PR fixes or works on following ticket(s):  (no ticket)
- This PR is related to PR: #1779

Upgrades Apache MINA SSHD 

---

src/main/java/sirius/biz/codelists/LookupValue.java
src/main/resources/default/assets/javascript/blobreffield.js
src/main/resources/default/assets/scripts/multi-language-field.js
src/main/resources/default/assets/scripts/smart-values.js
src/main/resources/default/taglib/t/actions.html.pasta
src/main/resources/default/taglib/t/lookupValue.html.pasta
src/main/resources/default/taglib/t/multiLanguageTextField.html.pasta
src/main/resources/default/taglib/t/tracing.html.pasta
src/main/resources/default/templates/biz/model/query-header.html.pasta
src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta

- This PR fixes or works on following ticket(s): [SIRI-900](https://scireum.myjetbrains.com/youtrack/issue/SIRI-900)
- This PR is related to PR: https://github.com/scireum/sirius-web/pull/1315 and https://github.com/scireum/token-autocomplete/pull/69

Some small enhancements for tab-focus and around

---

src/main/resources/default/templates/biz/tenants/tenant-details-fields.html.pasta
src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta

- fixes: SIRI-900
- This PR fixes or works on following ticket(s): [SIRI-900](https://scireum.myjetbrains.com/youtrack/issue/SIRI-900)

do not allow customEntries in tenant-country + user-salutation

---

src/main/java/sirius/biz/storage/layer2/BlobHardRefProperty.java

Avoids an NPE cascade deleting blobs

---

src/main/resources/default/templates/biz/tenants/tenant.html.pasta
src/main/resources/default/templates/biz/tenants/user-account.html.pasta

without this, a tenant-delete job or a rate-limit overview with id "new"  will be linked which is useless
No ticket

don't link jobs of tenants and user-accounts on new entities

---

src/main/resources/default/taglib/k/tocLink.html.pasta

- This PR fixes or works on following ticket(s): [SIRI-890](https://scireum.myjetbrains.com/youtrack/issue/SIRI-890)

Adds an icon to a tocLink to make the entry look less "empty"

---

src/main/resources/default/kb/de/user/ftp-import.html.pasta
src/main/resources/default/kb/en/system/cluster.html.pasta
src/main/resources/default/kb/en/system/customization-flags.html.pasta
src/main/resources/default/kb/en/system/health.html.pasta
src/main/resources/default/kb/en/system/kb.html.pasta
src/main/resources/default/kb/en/system/permissions.html.pasta
src/main/resources/default/kb/en/system/troubleshooting.html.pasta
src/main/resources/default/kb/en/user/noodle.html.pasta
src/main/resources/default/kb/en/user/tagliatelle.html.pasta

- This PR fixes or works on following ticket(s): [SIRI-890](https://scireum.myjetbrains.com/youtrack/issue/SIRI-890)

KB - Adds a toc to multiple articles of the knowledgebase

---

src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgePath.java

Previous fix was not correct. Due to this it failed on subdirectories 
- This PR fixes or works on following ticket(s): [SIRI-913](https://scireum.myjetbrains.com/youtrack/issue/SIRI-913)

Properly calculates parent hierarchy

---

src/main/java/sirius/biz/analytics/explorer/TimeSeries.java
src/main/java/sirius/biz/analytics/metrics/MetricQuery.java
src/main/java/sirius/biz/codelists/LookupTableController.java
src/main/java/sirius/biz/ide/Scripting.java
src/main/java/sirius/biz/ide/ScriptingController.java
src/main/java/sirius/biz/importer/format/AllInListCheck.java
src/main/java/sirius/biz/storage/layer2/L3Uplink.java
src/main/java/sirius/biz/storage/layer3/VirtualFile.java
src/main/java/sirius/biz/tenants/UserAccountController.java
src/main/java/sirius/biz/tycho/academy/OnboardingEngine.java
src/main/java/sirius/biz/tycho/kb/KnowledgeBase.java
src/main/java/sirius/biz/tycho/kb/KnowledgeBaseArticle.java
src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java
src/main/java/sirius/biz/web/BasePageHelper.java

No manual code change, just running the matching IntelliJ inspection and applying the suggestion for all.
More details: https://openjdk.org/jeps/431

Simplifies code by utilizing sequenced collection helpers

---

src/main/java/sirius/biz/process/output/ChartProcessOutputType.java
src/main/java/sirius/biz/process/output/LogsProcessOutputType.java
src/main/java/sirius/biz/process/output/TableProcessOutputType.java
src/main/java/sirius/biz/protocol/AuditLogController.java
src/main/java/sirius/biz/protocol/IncidentController.java
src/main/java/sirius/biz/protocol/JournalController.java
src/main/java/sirius/biz/protocol/LogController.java
src/main/java/sirius/biz/protocol/MailController.java

Before:
After:
- This PR fixes or works on following ticket(s): [OX-9905](https://scireum.myjetbrains.com/youtrack/issue/OX-9905)

Implementation of PageHelper::withTotalCount()

---

src/main/java/sirius/biz/importer/txn/ImportTransactionHelper.java

Respecting the current transaction context (sync source and sync mode).
This method is especially useful for nested entities supporting import transactions.
- This PR fixes or works on following ticket(s): [OX-10612](https://scireum.myjetbrains.com/youtrack/issue/OX-10612)

Permits to check if a transactional entity can be deleted

---

src/main/resources/default/templates/biz/tenants/tenant-config.html.pasta
src/main/resources/default/templates/biz/tenants/user-account-config.html.pasta

- This PR fixes or works on following ticket(s): [OX-10647](https://scireum.myjetbrains.com/youtrack/issue/OX-10647)

Added missing scroll method call for tenant and user config

---

src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java

- This PR fixes or works on following ticket(s): [SIRI-820](https://scireum.myjetbrains.com/youtrack/issue/SIRI-820)

Fixed unnecessary systemwide logging for BMEcat XML import job

---

src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java
src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java

Logs to job-only
- This PR fixes or works on following ticket(s): [SIRI-820](https://scireum.myjetbrains.com/youtrack/issue/SIRI-820)

Improves error logging in BMEcat import + archive extract jobs

---

pom.xml
src/main/java/sirius/biz/storage/layer3/uplink/util/UplinkConnectorPool.java
src/main/java/sirius/biz/util/ExtractedFileBuffer.java

see commits
- This PR fixes or works on following ticket(s): [SIRI-920](https://scireum.myjetbrains.com/youtrack/issue/SIRI-920)
- This PR is related to PRs: 
- https://github.com/scireum/sirius-parent/pull/38
- https://github.com/scireum/sirius-kernel/pull/512
- https://github.com/scireum/sirius-web/pull/1348
- https://github.com/scireum/sirius-db/pull/603

Update some dependencies

---

src/main/java/sirius/biz/cluster/NeighborhoodWatch.java
src/main/java/sirius/biz/cluster/work/DistributedTasks.java
src/main/java/sirius/biz/cluster/work/WorkLoaderLoop.java
src/main/resources/default/templates/biz/process/process.html.pasta
src/main/resources/default/templates/biz/process/processes.html.pasta

- Adds icons to additional actions (drop-down menu) of a single process (`/ps/…`)
- Adds additional actions to cards shown in processes overview (`/ps`)

Processes UI

---

pom.xml
src/main/java/sirius/biz/jobs/interactive/DoughnutChartJobFactory.java
src/main/resources/default/templates/biz/jobs/doughnutchart.html.pasta
src/main/resources/default/templates/biz/process/process-output-chart.html.pasta

Adapts doughnut charts to changes up-stream.

Doughnut Charts Fix

---

src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java

We get messages regarding deleted empty chapters during every sync, as some chapters are just empty in general or on some systems /languages.
To reduce this and highlight actually removed chapters that previously contained articles we now log only those that existed before the current sync.

Only reports removal of previously filled chapters

---

src/main/resources/default/templates/biz/packages/additional-and-revoked-permissions.html.pasta
src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta

BS5: Fixes alignment of permission checkbox help texts

---

src/main/resources/default/assets/scripts/blob-upload-url-popover.js
src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta

Also add indicator for unsaved changes

BS5 make blobImageSoftRefField work again

---

src/main/java/sirius/biz/importer/BaseImportHandler.java
src/main/java/sirius/biz/importer/ImportHandler.java

Fixes: [OX-10805](https://scireum.myjetbrains.com/youtrack/issue/OX-10805)

Exposes the ImportHandler.newEntity as public callable method

---

pom.xml

including Bootstrap 5, events-aggregations and pdf-generation
https://github.com/scireum/sirius-web/compare/dev-76.0.0...dev-76.1.3
NO Ticket

update sirius-web version for newest fixes

---

pom.xml
src/main/resources/default/templates/biz/disaster.html.pasta
src/main/resources/default/templates/biz/jobs/params/datefield.html.pasta

- fixes: SIRI-938
Update to new web-version and fix breakage from https://github.com/scireum/sirius-web/pull/1386
- This PR fixes or works on following ticket(s): [SIRI-938](https://scireum.myjetbrains.com/youtrack/issue/SIRI-938)
- This PR is related to PR: https://github.com/scireum/sirius-web/pull/1386

fix breakages for t:datefield and update to new sirius-web-version

---

src/main/java/sirius/biz/importer/txn/ImportTransactionHelper.java

Should only be used for rare cases, therefore directly deprecate it.
- This PR fixes or works on following ticket(s): [SE-13357](https://scireum.myjetbrains.com/youtrack/issue/SE-13357)

Provide a temporary useful setter.

---

src/main/java/sirius/biz/scripting/ScriptableEventDispatcherRepository.java
src/main/java/sirius/biz/scripting/mongo/MongoCustomEventDispatcherRepository.java
src/main/java/sirius/biz/tenants/Tenants.java

Allowing scripts to be defined at parent tenants.
- This PR fixes or works on following ticket(s): [OX-10898](https://scireum.myjetbrains.com/youtrack/issue/OX-10898)

Fetches tenant scripts from all tenants in the hierarchy

---

docker-compose.yml
pom.xml
src/test/kotlin/sirius/biz/jupiter/JupiterTest.kt
src/test/resources/docker-compose.yml

Upgrades maria db driver and some additional version upgrades/improvements.  
- This PR fixes or works on following ticket(s): [SE-13671](https://scireum.myjetbrains.com/youtrack/issue/SE-13671)

MariaDb driver upgrade

---

pom.xml

Resolves startup issues caused by the related PR.
Downgrading the server-version is not necessary.
- This PR fixes or works on following ticket(s): [SIRI-888](https://scireum.myjetbrains.com/youtrack/issue/SIRI-888)
- This PR is related to PR: https://github.com/scireum/sirius-db/pull/569

Resolves startup issues caused by upgrading the Clickhouse dependencies

---

src/main/java/sirius/biz/tycho/kb/KnowledgeBaseSearchProvider.java

Before:
After:
- This PR fixes or works on following ticket(s): [OX-10941](https://scireum.myjetbrains.com/youtrack/issue/OX-10941)

Open Search: Adds tags to results of Knowledgebase articles for easier differentiation

---

src/main/java/sirius/biz/tenants/mongo/MongoTenantSearchProvider.java

- This PR fixes or works on following ticket(s): [OX-10941](https://scireum.myjetbrains.com/youtrack/issue/OX-10941)

OpenSearch: Permits to find tenants with their exact ID

---

src/main/java/sirius/biz/storage/layer3/DeleteFilesJob.java

- This PR fixes or works on following ticket(s): [SIRI-973](https://scireum.myjetbrains.com/youtrack/issue/SIRI-973)

VFS - DeleteFilesJob: Fixes job skipping files while iterating over all files when job is not set to simulation

---

src/main/java/sirius/biz/util/ArchiveExtractor.java

In very rare cases customers upload archives with ISO-8859-1 encoding (probably created with some windows tools). We now try to use the Java logic with the secondary encoding before switching to 7ZIP (which also fails in that case).
- This PR fixes or works on following ticket(s): [OX-10856](https://scireum.myjetbrains.com/youtrack/issue/OX-10856)

ZIP Handling - Fall back to ISO-8859-1 when UTF8 wxtraction fails

---

src/main/resources/default/taglib/k/article.html.pasta
src/main/resources/default/taglib/k/base.html.pasta

- This PR fixes or works on following ticket(s): [OX-11038](https://scireum.myjetbrains.com/youtrack/issue/OX-11038)

KB - Adds a head block which allows to extend the contents of the pages head

---

src/main/resources/default/templates/biz/cluster/background-jobs.html.pasta

add class to not break layout on small screen or few space

---

src/main/java/sirius/biz/translations/MultiLanguageStringHelper.java

We need to read the texts set via withFallback / withText.
Also applies some grammar suggestions.
- This PR fixes or works on following ticket(s): [OX-11188](https://scireum.myjetbrains.com/youtrack/issue/OX-11188)

Adds a few getters to the MultiLanguageStringHelper

---

docker-compose.yml
pom.xml
src/main/java/sirius/biz/storage/s3/ObjectStore.java
src/test/resources/docker-compose.yml

Some library and docker image version upgrades. 
Out of scope databases: MongoDB and ES
- This PR fixes or works on following ticket(s): [SE-13995](https://scireum.myjetbrains.com/youtrack/issue/SE-13995)

Version upgrades

---

docker-compose.yml
pom.xml
src/test/resources/docker-compose.yml

Upgrade ES docker versions
- This PR fixes or works on following ticket(s): [SIRI-1026](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1026)
- This PR is related to https://github.com/scireum/sirius-db/pull/664

Upgrade ES docker versions

---

src/main/resources/default/templates/biz/password/change-password-script.html.pasta

If the settings require letters AND digits, false must be returned if either of the conditions are not fulfilled. Same goes of upper and lower case requirements.
- This PR fixes or works on following ticket(s): [SE-14149](https://scireum.myjetbrains.com/youtrack/issue/SE-14149)
- This PR is related to PR: #2046

SE-14149: Fixes client side password checks.

---

src/main/java/sirius/biz/password/PasswordSettings.java

This allows implementations on pages that users are allowed to customize.
- This PR fixes or works on following ticket(s): [SE-14215](https://scireum.myjetbrains.com/youtrack/issue/SE-14215)
- This PR is related to PR: #2046

SE-14215: Grants sandbox access to the user password settings.

---

pom.xml
src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java
src/main/java/sirius/biz/storage/legacy/StoredObjectRef.java

the isFilled/isEmpty check is included there.
Also updated sirius-web version for css-design-system and newest functionalities
Includes https://github.com/scireum/sirius-web/pull/1469 "breaking"
- This PR fixes or works on following ticket(s): No ticket, use method from kernel
- This PR is related to PR:  https://github.com/scireum/sirius-kernel/pull/540

use new isHttpUrl() method from kernel#Strings

---

.drone.yml
pom.xml

- This PR fixes or works on following ticket(s): [SIRI-1030](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1030)

Switch project to Java 23

---

src/main/java/sirius/biz/analytics/events/EventRecorder.java
src/main/java/sirius/biz/analytics/events/EventSpliterator.java
src/main/java/sirius/biz/analytics/events/PageImpressionEvent.java
src/main/java/sirius/biz/analytics/events/UserActivityEvent.java
src/main/java/sirius/biz/analytics/events/UserEvent.java
src/main/java/sirius/biz/tycho/updates/UpdateClickEvent.java
src/main/java/sirius/biz/util/SOAPCallEvent.java

Cherry picks all commits of https://github.com/scireum/sirius-biz/pull/2061 for Hotfix version 107.4.0.
- This PR fixes or works on following ticket(s): [SE-14230](https://scireum.myjetbrains.com/youtrack/issue/SE-14230)
- This PR is related to PR: #2061

SE-14230: Cherry Picks Event Streaming for Hotfix

---

src/main/java/sirius/biz/isenguard/Isenguard.java

Exposes a method for creating rate limiting exceptions, as depending on the setting, it makes sense to throw such an exception externally after checking the limit and performing cleanup.
- This PR fixes or works on following ticket(s): [MIO-6376](https://scireum.myjetbrains.com/youtrack/issue/MIO-6376)

Rate Limiting: Exposed Exception Building

---

src/main/resources/component-070-biz.conf

Some may need the method in .pasta-files in exposed scope
- This PR fixes or works on following ticket(s): [SIRI-1039](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1039)

Allow fetchCachedValue() for sandbox as fetchValue() was before

---

src/main/resources/default/taglib/t/actions.html.pasta

Renders raw HTML from action descriptions

---

src/main/java/sirius/biz/cluster/ClusterController.java
src/main/resources/default/templates/biz/cluster/caches.html.pasta
src/main/resources/default/templates/biz/cluster/cluster.html.pasta

With some stats and the option to clear all or a single cache.
- This PR fixes or works on following ticket(s): [SIRI-1048](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1048)

Cluster Caches Overview

---

src/main/java/sirius/biz/jobs/JobsSearchProvider.java
src/main/java/sirius/biz/tycho/search/OpenSearchResult.java

Show HTML formatted job descriptions in OpenSearch

---

src/main/resources/biz_de.properties

This may be used by auto-generated error messages.

Add missing translation key

---

src/main/resources/default/taglib/k/previewImage.html.pasta

Before:
After:
https://github.com/user-attachments/assets/73ad06e2-9f0f-45c5-ae59-209cb5794740
- This PR fixes or works on following ticket(s): [SIRI-1024](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1024)

KBA - Implements the previewImage template to display a preview for an image in form of a card

---

src/main/resources/default/taglib/k/previewImage.html.pasta

Before:
After:
- This PR fixes or works on following ticket(s): [SIRI-1024](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1024)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/2097

KBA - previewImage - Changes appearance of the preview image, also adapts the overlay to center and contain the entire image

---

docker-compose.yml
src/test/resources/docker-compose.yml

clickhouse will be updated separately in https://scireum.myjetbrains.com/youtrack/issue/SIRI-1086
elasticsearch will follow in https://scireum.myjetbrains.com/youtrack/issue/DO-353/Elasticsearch-Upgrade-auf-8.17.2
- This PR fixes or works on following ticket(s): [SIRI-1076](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1076)
- This PR is related to PR:  https://github.com/scireum/sirius-db/pull/676

SIRI-1076 update docker image versions to newer ones

---

pom.xml

Updates maven parent and sirius dependencies
- This PR fixes or works on following ticket(s): [SIRI-1059](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1059)

Updates sirius parent and libs

---

src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta

**Before:**
**After:**
- This PR fixes or works on following ticket(s): [OX-11820](https://scireum.myjetbrains.com/youtrack/issue/OX-11820)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/2109

Data Explorer - Fixes issues overlapping filter elements not breaking into lines correctly

---

src/main/java/sirius/biz/scripting/mongo/MongoCustomScriptController.java
src/main/resources/default/templates/biz/scripting/mongo-script.html.pasta
src/main/resources/default/templates/biz/scripting/mongo-scripts.html.pasta

Before:
After:
- This PR fixes or works on following ticket(s): [SIRI-1096](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1096)

Custom Scripting - Adds buttons to allow the deletion of custom scripts

---

docker-compose.yml
pom.xml
src/test/resources/docker-compose.yml

- This PR fixes or works on following ticket(s): [SIRI-1061](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1061)
- This PR fixes or works on following ticket(s): [DO-279](https://scireum.myjetbrains.com/youtrack/issue/DO-279)
- This PR is related to PR: https://github.com/scireum/sirius-db/pull/680

Uses newest mongo db driver and upgrades to Mongo 8

---

docker-compose.yml
src/test/resources/docker-compose.yml

Upgrades mongodb to 8.0.8

---

pom.xml
src/main/java/sirius/biz/web/BizController.java

Enables the use of HTML in entity validation warnings.
- This PR fixes or works on following ticket(s): [OX-11996](https://scireum.myjetbrains.com/youtrack/issue/OX-11996)

HTML Validation Warnings

---

src/main/resources/default/taglib/w/charts.html.pasta

After:
- This PR fixes or works on following ticket(s): [OX-12013](https://scireum.myjetbrains.com/youtrack/issue/OX-12013)

Wondergem - Implements a t:charts equivalent for Wondergem to apply in OX portal settings

---

src/main/java/sirius/biz/web/BizController.java

Displays all validation warnings, not just the first. (And fixes the spelling of "ID".)
- This PR fixes or works on following ticket(s): [OX-11996](https://scireum.myjetbrains.com/youtrack/issue/OX-11996)

Multiple Validation Warnings

---

src/main/java/sirius/biz/importer/AfterCreateOrUpdateEvent.java
src/main/java/sirius/biz/importer/BeforeCreateOrUpdateEvent.java
src/main/java/sirius/biz/importer/MongoEntityImportHandler.java
src/main/java/sirius/biz/importer/SQLEntityImportHandler.java

- This PR fixes or works on following ticket(s): [SIRI-1116](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1116)

Permits to write tenant scripts triggered AFTER entities have been saved

---

src/main/java/sirius/biz/process/ProcessContext.java
src/main/java/sirius/biz/process/ProcessEnvironment.java
src/main/java/sirius/biz/process/ProcessLink.java
src/main/java/sirius/biz/process/Processes.java

Provides methods to clear the external links attached to a process, and to only add a link if it is not yet present. Also fixes a potential NPE.

Utility Methods for Process Links

---

.drone.yml
pom.xml
src/main/java/sirius/biz/analytics/events/ClickhousePartsReportJobFactory.java
src/main/java/sirius/biz/analytics/reports/LinesCellFormat.java
src/main/java/sirius/biz/cluster/RedisUserMessageCache.java
src/main/java/sirius/biz/codelists/LookupTable.java
src/main/java/sirius/biz/jobs/BasicJobFactory.java
src/main/java/sirius/biz/jobs/JobConfigData.java
src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java
src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java
src/main/java/sirius/biz/storage/layer2/URLBuilder.java
src/main/java/sirius/biz/storage/layer3/VFSSearchProvider.java
src/main/java/sirius/biz/storage/legacy/Storage.java
src/main/java/sirius/biz/storage/legacy/StoredObjectRef.java
src/main/java/sirius/biz/tenants/HttpsUrlValidator.java
src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java
src/main/java/sirius/biz/tycho/smart/EmailSmartValueProvider.java
src/main/java/sirius/biz/tycho/updates/UpdatesController.java
src/main/java/sirius/biz/tycho/updates/UpdatesReport.java
src/main/java/sirius/biz/util/ReportUnusedNLSKeysJob.java

Breaking due to Java24 upgrade. 
Minor 3rd party lib upgrades. 
Fix deprecated method usages
- This PR fixes or works on following ticket(s): [SIRI-1072](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1072)

Java24 and libs

---

docker-compose.yml
pom.xml
src/test/resources/docker-compose.yml

- This PR fixes or works on following ticket(s): [SIRI-1119](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1119)

Upgrades elasticsearch to 8.18.3

---

src/main/java/sirius/biz/scripting/mongo/MongoCustomEventDispatcherRepository.java

as we would add `null` as items to the dispatcher's list.

Avoids an NPE if a script would not compile

---

src/main/java/sirius/biz/jobs/presets/JobPreset.java
src/main/java/sirius/biz/jobs/presets/jdbc/SQLJobPreset.java
src/main/java/sirius/biz/jobs/presets/mongo/MongoJobPreset.java

After:
- This PR fixes or works on following ticket(s): [SIRI-1121](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1121)

Job-Templates - Extends JobPresets with `Journaled` to allow the logging of changes to the change protocol
