pom.xml
sirius-biz.iml
src/main/java/sirius/biz/tenants/TenantController.java

Fixes the query for possible tenants for /tenants/select
When determining of the parent tenant can be accessed, we have to check
the value set for the child - not the parent

Fixes the query for possible tenants for /tenants/select

---

pom.xml
src/main/java/sirius/biz/tenants/TenantController.java

Removed unnecessary query on tenant switching which caused switching was only possible on tenants whose parent was the system tenant.

Fixxed tenant select on switching tenant

---

pom.xml
src/main/java/sirius/biz/tenants/TenantUserManager.java

Values for userAccountCache and configCache are inserted by unique name of objects so flushing them for those needs the same property in order to remove the corresponding element.

Flush UserAccount caches correctly

---

pom.xml
src/main/java/sirius/biz/tenants/Tenant.java

Tenants were not editable because they missed the field country which was required in the templates.

Make tenants editable again

---

pom.xml
sirius-biz.iml
src/main/java/sirius/biz/web/PageHelper.java

In Sirius-Biz pages have a default size of 50 items per page. However, in Sirius-Web the default size is 25. The page size in Sirius-Web was not set by Sirius-Biz so the pagination showed 50 items per page but calculated next and previous page items with 25. By setting the page size in Sirius-Web this should be fixed.

Fixing wrong page size in pagination

---

pom.xml
src/main/java/sirius/biz/web/BizController.java

Changes the logic of the saveHelper.saveEntity() function in order to keep it more in line with the desired effect.
Deprecates the editAfterCreate function since it is no longer necassary to set a flag for editAfterCreate.
Removes the editAfterCreate boolean since it is no longer needed.
Changes the JavaDoc to reflect the Changes made.
Bump version to 1.8.2

Update SaveHelper with a bit of new logic.

---

pom.xml
sirius-biz.iml
src/main/java/sirius/biz/model/BizEntity.java
src/main/java/sirius/biz/web/BizController.java

Is moved to Entity in sirius-db to allow BizController to handle Entities without the tracing functionality.

Deletes getIdAsString from BizEntity

---

pom.xml
src/test/java/sirius/biz/tenants/TenantsHelper.java

Adds the Possibility in TenantsHelper to get the private TestUserAccount or the private TestTenant.
Splits up the old setupTestTenant() into setupTestTenant() and setupTestUser().
Replaces all direct accessors of the testTenant and testUser fields with the new getters.
Bumps Version to 1.9.3

Changes in TenantsHelper so Tests are able to get TestTenant and TestUserAccount

---

pom.xml
src/test/java/sirius/biz/tenants/TenantsHelper.java

This got mixed up somewhere. For tenant id the id from database is used. However, for user ids the unique name is used. The wrong assignment caused some tests to fail because test user accounts were different from user accounts in production.

Set correct value of tenant id for tests

---

pom.xml
src/main/resources/default/view/parts/infoboxElement.html

In order to break to long strings in value column to avoid overflowing content

Uses word-wrap in Infobox' value column

---

pom.xml
src/main/java/sirius/biz/web/PageHelper.java

Otherwise the default filter value would be false instead of fetching all entries
no matter if true or false

Won't apply the filter query, if no filter value is set

---

pom.xml
src/main/resources/default/mail/useraccount/password-html.vm
src/main/resources/default/mail/useraccount/password.vm

If the url was not set in the config, the url variable appeared in the mail. However, this is not desired. So therefore the url is completely hidden in this case.

Fix url in password mail

---

src/main/java/sirius/biz/storage/VirtualObject.java

These'll have their reference filled later, therefore we must suppress
the check.

Disables the uniqueness check for paths for temporary objects.

---

src/main/resources/default/templates/tenants/tenant-details.html.pasta
src/main/resources/default/templates/tenants/tenant.html.pasta
src/main/resources/default/templates/tenants/user-account.html.pasta

Extensions do live in the i space, not the w space as the tag does not directly references a template.

Use proper tag for extensions

---

src/main/java/sirius/biz/storage/StoredObjectRef.java

If a StoredObjectRef was filled the first time it was not marked as changed and therefore the referenced file was not marked as persistent but as temporary and got deleted on the next cleanup job run.

Make sure newly created StoredObjectRef are stored

---

src/main/resources/default/templates/protocol/mails.html.pasta

The base url for paging has to be absolute.

Fix paging on mails site

---

src/main/resources/default/templates/protocol/logs.html.pasta
src/main/resources/default/templates/protocol/protocol.html.pasta

Pagination urls have to start with a slash.

Fix pagination url for logs and protocols

---

pom.xml
src/main/resources/default/taglib/w/selectObject.html.pasta

The strings for label and help are already translated so they do not need to be translated a second time.

Remove double translation in selectObject

---

src/main/java/sirius/biz/storage/VersionManager.java
src/main/resources/component-biz.conf

When using the CLI, a temporary source file and a destination file are created. The source file was not filled with the image data.

Fixes conversion of images using CLI

---

src/main/java/sirius/biz/storage/VersionManager.java

The JPEG writer screws up the channels when an alpha channel exists. Instead of creating a BufferedImage with an alpha channel and then relying on the JPEG writer to deal with it, now we always make it a RGB image and fill the background with white when drawing the original image.

Fixes scaling of images with alpha channel with Java

---

src/main/java/sirius/biz/storage/DownloadBuilder.java
src/main/java/sirius/biz/storage/VersionManager.java
src/main/resources/component-biz.conf

The version string of VersionManager now supports the specification of a minimum size. The new syntax is a comma separated string of key-value pairs in the form of `key:value`. The available keys are `size` for the requested maximum size, and `min` for the minimum size. The value is the size in the format `<width>x<height>`.
Example: The version `size:500x500,min:100x100` would scale an image with 1000x800 pixels to 500x400. An image with 1000x150 would be scaled to 500x75 and then extended with a white border to 500x100. An image with 400x50 pixels would not be scaled but extended to 400x100.

Implements a minimum size for image versions

---

src/main/java/sirius/biz/storage/VersionManager.java

The image was not converted to RGB when the image was smaller then the requested size. Also, the image was not scaled down, when one of the dimensions was smaller then the requested size.

Fixes the image conversion

---

src/main/java/sirius/biz/storage/vfs/VirtualFile.java

This must not be an empty string or the apache server will throw an error when listing files.

Change name of FTP root node

---

src/main/java/sirius/biz/tenants/UserAccountController.java

Before it was possible to read out user accounts without being logged in.

Check for login on autocompleting user accounts

---

pom.xml
src/main/resources/default/taglib/w/selectObject.html.pasta

The dropdown for selecting a file from the storage engine has now a flag to indicate to the user that the field is required to fill.

required flag for selectObject

---

pom.xml
src/main/java/sirius/biz/storage/StoredObject.java
src/main/java/sirius/biz/storage/VirtualObject.java

The path of StoredObject is now accessible and can be used e.g. for filtering files based on their path.

Expose path of StoredObject

---

pom.xml
src/main/resources/default/taglib/w/storedObjectUploader.html.pasta

Updates the word-wrap style to break-word since objektrefkeys can be  long.
.word-wrap cant be used since we dont want to use hyphons here.
Version-Bump

Small word wrap css fix

---

pom.xml
src/main/java/sirius/biz/storage/Storage.java
src/main/java/sirius/biz/storage/VersionManager.java
src/main/java/sirius/biz/storage/VirtualObject.java
src/main/java/sirius/biz/storage/VirtualObjectVersion.java

When a virtual object was updated the versions where only removed from the database, but not the cache. This lead to outdated URLs and therefore broken images.

 Clears the object version cache when removing versions

---

pom.xml
src/main/resources/default/templates/password/password.html.pasta

It might be confusing for the user to see the message "weak password" after loading the page.
- Fixes: SE-4166

Prevents marking an empty input field as a weak password

---

pom.xml
src/main/java/sirius/biz/jdbc/codelists/CodeListController.java
src/main/java/sirius/biz/jdbc/jobs/JobsController.java
src/main/java/sirius/biz/jdbc/tenants/ProfileController.java
src/main/java/sirius/biz/jdbc/tenants/UserAccountController.java
src/main/java/sirius/biz/web/BizController.java

This is because we want to provide feedback to the user if the token is invalid e.g. because of token lifetime
instead of silently skipping deletion/modification.

Uses ensureSafePOST() instead of isSafePOST()

---

src/main/java/sirius/biz/jdbc/storage/StorageController.java

Autocompletes for the storage engine should search with wildcard at the end for easier autocompletion. Only the first part of an stored object is now needed instead of the complete query. This is also used in the list for the objects.
Tags: storage, autocomplete

Autocomplete in storage always with wildcard

---

src/main/java/sirius/biz/sequences/SmartSequenceStrategy.java

The delegate field was null until tryGenerateId was called. Now the delegate field is initialized on every call if needed.
Tags: sequences

Avoid NPE for Smart Squences

---

src/main/java/sirius/biz/importer/ImportContext.java
src/test/java/sirius/biz/importer/ImporterSpec.groovy

Easy way to allow Entity Mappings as keys as well as strings without needing to rewrite everything
within the import handler.
This Context allows as to write e.g. Tenant.NAME instead of Tenant.NAME.getName()

Implements ImportContext which handles mappings as keys as well

---

src/main/java/sirius/biz/codelists/CodeLists.java

If a codelist was set to autofill false in CodeLists::getValues a non present value would be added with no regard of the setting.
Tags: codelist

Respect codelist autofill settings

---

src/main/java/sirius/biz/web/BizController.java

Backend users of the tenant should not always the the product url but
their own url
- Fixes: SE-4956

Allows to set the base url per tenant instead of only once per product

---

src/main/java/sirius/biz/codelists/CodeListEntry.java
src/main/java/sirius/biz/codelists/CodeLists.java
src/main/java/sirius/biz/model/PersonData.java
src/main/resources/default/taglib/w/codelistSelect.html.pasta

Some systems have several languages in place. In order to use the same entries for salutations the codelist entries can now be translated for those systems.
Tags: codelist, translation, nls

Make CodeListEntries translatable

---

src/main/java/sirius/biz/cluster/InterconnectClusterManager.java

This is necessary so interconnect cluster calls are successful when the default http port is changed (e.g. in development environments)

Includes the port within the local address broadcasted to the cluster

---

src/main/java/sirius/biz/cluster/ClusterController.java
src/main/java/sirius/biz/cluster/InterconnectClusterManager.java
src/main/java/sirius/biz/cluster/NeighborhoodWatch.java
src/main/resources/default/templates/cluster/cluster.html.pasta

As most probably each node reports all jobs, we only need to use
the first description as (if all nodes run the same software version)
the descriptions would be the same anyway.

Adds a de-duplication when collecting descriptions for cluster jobs.

---

src/main/java/sirius/biz/mongo/PrefixSearchableEntity.java
src/test/java/sirius/biz/mongo/PrefixSearchableEntitySpec.groovy

input | searchPrefixes
------|-------
`"a.b@c.de"` | `[a.b@c.de"]`
`"a24@x.de"` | `["a", "", "@x.de"]`
`"xyz–test.blubb"` | `["xyz", "test.blubb"]` 
input | searchPrefixes
------|-------
`"a.b@c.de"` | `["a.b@c.de", "a.b", "a", "b", "c.de", "c", "de"]`
`"a24@x.de"` | `["a24@x.de", "a24", "a", "x.de", "x", "de"]`
`"xyz–test.blubb"` | `["xyz-test.blubb", "xyz", "test", "blubb"]`

Fills the searchPrefixes field with more subtokens

---

src/main/java/sirius/biz/storage/versions/VersionedFiles.java
src/test/java/sirius/biz/storage/VersionedFilesSpec.groovy

storage.getData() is nonnull so therefore for a null content versioned file getContent would throw an Exception.
Tags: versioned files

Fix Exception on reading null content versioned files

---

src/main/java/sirius/biz/protocol/TraceData.java

As LoginData allows an username of 150 characters the TraceData should be able to store this length, too.
Tags: tracing

Increase lengths for by fields in TraceData

---

src/main/java/sirius/biz/vfs/ftp/FTPBridge.java
src/main/resources/component-biz.conf

This is important as we need to limit the range of possible ports for dockerization.

Allow to set the ports to use in FTP passive mode

---

src/main/java/sirius/biz/vfs/ftp/FTPBridge.java
src/main/resources/component-biz.conf

This is needed for dockerization as the FTP server has to announce the correct address in passive mode for clients to connect to.

Allow to set the external address to announce in FTP passive mode

---

src/main/java/sirius/biz/model/AddressData.java
src/main/java/sirius/biz/model/InternationalAddressData.java

Sometimes an AddressData is used outside of its regular context. In this case it should be possible to customize the shown error messages. Therefore a temporary field label is introduced.
Tags: address

Temporary field labels for showing contextual messages

---

src/main/java/sirius/biz/tenants/TenantUserManager.java
src/main/java/sirius/biz/tenants/UserAccountData.java

Calculates the interval to the last external login correctly. Until now this function always returned true.
-Fixes: SIRI-46

SIRI-46 Calculates the interval to the last external login correctly.

---

src/main/java/sirius/biz/storage/StoredObjectRef.java

Currently they are only valid for a limited timeframe. Now it is possible to generate a eternally valid url.
Tags: storage

Downloads via StoredObjectRef can be marked as eternally valid

---

src/main/resources/default/taglib/w/selectObject.html.pasta

The id is no longer assigned to the original select. So we have to use the name to select the select.

Fixes the selectObject Taglib

---

src/main/java/sirius/biz/jobs/params/EntityParameter.java
src/main/resources/biz_de.properties

This makes it possible to overwrite it in order to also allow selection of entities belonging to the parent tenant.
Gives the VirtualObjectParameter a label

 Moves the tenant check for job parameters into it's own method

---

src/main/java/sirius/biz/importer/BaseImportHandler.java

Use orElseGet when loading or creating an Entity. Before with orElse() we always tried to create and update a new  entity with the given data even when we had already found an entity with the findquery. When we violated unique constraints this led to an error.
-Tags: Bug

Fix orElse Findquery Fail

---

src/main/java/sirius/biz/importer/ImportDictionary.java

Since the withAliases functionen reverses the field and alias from keys to values we have to take care of this behaviour in the merge function.
-Tags: Bug

Switch key value when merging dictionaries

---

src/main/java/sirius/biz/importer/SQLEntityImportHandler.java

we add values to the entity which are not AutoImported because we don't want them
to be changed through an import file.
E.g. the transactionId of a featureValue is manually set and we also need to check this property

Provides an extra method to override to check if a property has changed

---

src/main/java/sirius/biz/process/ProcessController.java

the process.toString() method does not return the processId. We were redirecting to a
non existant page

Corrects the redirect after canceling a process

---

src/main/java/sirius/biz/jobs/params/EntityParameter.java

This assignment is not needed as getDescriptor does the assignment later and is only called once.
Tags: job, parameter

Remove unused assignment

---

src/main/java/sirius/biz/jobs/params/PartListParameter.java
src/main/resources/default/templates/biz/jobs/params/part-list.html.pasta

This allows to select from a list of classes that implement and register a common superclass when starting a job.
As a label for the single select toString of the classes is called.
The job is provided with the registered implementation object of the selected part.
Fixes: SIRI-69

Allows for a singleselect job parameter based on a list of parts

---

src/main/resources/default/templates/biz/process/process-details.html.pasta

It can be quite confusing if there is an action which is only present when viewing the process in the log view. Therefore the actions are now also shown in the details view.
Tags: processes

Show log actions in details

---

src/main/java/sirius/biz/cluster/BackgroundInfo.java
src/main/java/sirius/biz/cluster/ClusterController.java
src/main/java/sirius/biz/cluster/NeighborhoodWatch.java
src/main/java/sirius/biz/cluster/work/DistributedTasks.java
src/main/java/sirius/biz/cluster/work/WorkLoaderLoop.java
src/main/resources/component-biz.conf
src/main/resources/default/templates/biz/cluster/cluster.html.pasta
src/test/java/sirius/biz/s3/ObjectStoresSpec.groovy
src/test/resources/docker-biz.yml

Improves rolling cluster upgrades by implementing a proper health check and support bleeding out a node before restarting it.
Using /system/cluster/ready as health check (in the load balancer) a node is only considered healthy when fully started up
(and not yet bleeding out).
Bleeding out can be started via the cluster UI or an API call (which should be the common case). This will
drop the node out of load balancing (via said health check) and also prevent the node from picking up
further background work (mainly distributed task), so that it can be restarted in a save way.
Additionally /system/cluster/halted can be invoked to determine if the node is already fully bled
out (not executing any distributed tasks anymore). Note that this implies that all long running
work is represented as …

Improved health checks and support for bleeding out cluster members

---

src/main/java/sirius/biz/process/ProcessContext.java
src/main/java/sirius/biz/process/ProcessEnvironment.java

This can be useful e.g. when starting a async task from within a process context which should log into
the same process.

Allows to fetch the process id from a process context

---

src/main/java/sirius/biz/process/Processes.java

Standby processes should only be created once and can be used for grouped logging from this point on. It should
not be possible to terminate such a process from within an application (conscious or not).

Don't mark standby processes as terminated when calling markCompleted()

---

src/main/java/sirius/biz/jobs/batch/file/LineBasedImportJob.java

No longer import empty rows from a import import file. When no data is contained in a row we do not handle the row.

No longer import empty rows from a linebased import file

---

src/main/java/sirius/biz/i5/Transform.java
src/main/java/sirius/biz/i5/Transformer.java

This is required if the "Java side" is updated before the i5 side as most probably the
left over byte buffer is uninitialized and will crash data conversions. The application
has to ensure itself that this data is never used up until it is populated correctly.
Also this feature is turned off by default for obvious reasons.

Permits to ignore i5 data conversion errors.

---

src/main/java/sirius/biz/i5/Transformer.java

Otherwise the exception is thrown even though the transformation was succsessful.
Tags: i5

Returns the index back every time

---

src/main/java/sirius/biz/i5/I5Connection.java
src/main/java/sirius/biz/i5/Transformable.java
src/main/java/sirius/biz/i5/Transformer.java

The AS400 object itself holds the correct encoding to use to parse an AS400Text. Therefore this information is used to parse the text as the system locale might be different than the AS400's locale and therefore its used encoding.
Tags: i5, as400

Parse AS400Text with correct encoding

---

src/main/java/sirius/biz/tenants/mongo/MongoUserAccount.java

As it tries to assign the Mixin first to the UserAccountData which fails with an exception and therefore no other assignment is tried.
See SQLUserAccount#tryAs 48b8c462d98577ce2cc83d9f036a44bff3f82b4e

Prevent exception when Mixin targets MongoUserAccount

---

src/main/java/sirius/biz/tenants/UserAccountController.java
src/main/java/sirius/biz/tenants/jdbc/SQLTenantController.java
src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountController.java
src/main/java/sirius/biz/tenants/mongo/MongoTenantController.java
src/main/java/sirius/biz/tenants/mongo/MongoUserAccountController.java
src/main/java/sirius/biz/web/BizController.java

As only accounts of the system tenant with the permission `user-administrator` get the `flag-syste-tenant` this was too restrictive for some use cases, e.g. when normal `administrator`s should also be able to support other users by switching to their tenant or account.
To enable this we check if the account is originaly from the system tenant when filtering the users/tenants and selecting them.

Fixes tenant/user switching for accounts of the system tenant

---

src/main/java/sirius/biz/tenants/Tenants.java

Don't use the uniqueName of the ref Object, as the string method already prefixes the id

Prevents duplicate typename prefix when fetching user accounts

---

src/main/resources/default/templates/biz/tenants/select-tenant.html.pasta
src/main/resources/default/templates/biz/tenants/tenants.html.pasta
src/main/resources/default/templates/biz/tenants/user-accounts.html.pasta

To keep their font sizes big, even if an extension inserted table cells in front of the name

Adds 'title' css-class to tenant/user table first rows

---

src/test/java/sirius/biz/tenants/TenantsHelper.java

The session fingerprint is missing. Instead of setting all these session values by hand we now let the UserManager do the work.

Fixes installing the user for tests

---

src/main/java/sirius/biz/jobs/params/PartListParameter.java
src/main/java/sirius/biz/jobs/params/PriorizedPartListParameter.java

This allows to select from a list of classes that implement and register a common superclass when starting a job.
The list of provided select options is sorted by the priority of the parts.
As a label for the single select toString of the classes is called.
The job is provided with the registered implementation object of the selected part.

Allows for a job parameter based on a list of priorized parts

---

src/main/java/sirius/biz/tenants/Tenant.java
src/main/java/sirius/biz/tenants/TenantController.java
src/main/java/sirius/biz/tenants/TenantUserManager.java
src/main/java/sirius/biz/tenants/UserAccountController.java

Previously, this was only done for 'flag-system-administrator', but there might be other user profiles that are attached to 'flag-system-tenant'

 Correctly keeps 'flag-system-tenant' when switching to another tenant

---

src/main/java/sirius/biz/importer/format/ValueInListCheck.java

Therefore this check can now be configured to also accept empty values.

Permits the ValueInListCheck to handle optional field lists.

---

src/main/java/sirius/biz/tenants/jdbc/DeleteSQLUserAccountsTask.java
src/main/java/sirius/biz/tenants/mongo/DeleteMongoUserAccountTask.java

So entities referencing UserAccounts can be deleted beforehand with the default priority

Delete UserAccounts later in the DeleteTenantJob

---

src/main/java/sirius/biz/analytics/events/EventRecorder.java

First of all we're not expecting any exception here, as "invokeChecks" is set to false
(the checks are executed when recording the event).
Second, if a database error occurs (like clickhouse being down), we'll
also receive a handled exception from "insert" and should abort right here. This
will let the loop sleep for another 5 minutes and will give clickhouse enough time
to startup...

We must not ignore handled exceptions here.

---

src/main/java/sirius/biz/tenants/TenantData.java

No matter if 'journal.hasJournaledChanges()' is true or not.
The code before resulted in the following problem:
- When deleting a child-tenant the "tenants.flushTenantChildrenCache();" code was not triggered, because journal.hasJournaledChanges() was false.
- Therefore the parent-tenant could not be deleted, because "tenants.hasChildTenants(id)" still returned true in the "CheckForMongoChildrenTask"

Flush cashes when a Tenant is deleted

---

src/main/java/sirius/biz/jobs/params/EntityParameter.java
src/main/resources/biz_de.properties

The inputfield allows to enter values that are not present in the autocomplete suggestions which currently leads to a null parameter value. Which is fine for mandatory parameters, as this catches the invalid input. But for optional parameters this results in an error while executing the job and not in an error message when trying to start the job - which is desired.
Fixes: OX-5335

Prevents the user from entering a non existent Entity as parameter

---

src/main/java/sirius/biz/web/BasePageHelper.java

As the total count is not often used, and may require a second DB query, the flag has to be explicitly set. But if total count <= pagesize it is always filled, as it is already known.

Adds the Ability to fetch the total count when using the PageHelpers

---

src/main/java/sirius/biz/model/AddressData.java

Because the correct language may not yet been set to the CallContext when calling the constructor
Fixes: OX-5421

Nullckeck "fieldLabel"-field lazily

---

src/main/java/sirius/biz/importer/format/ImportDictionary.java
src/test/java/sirius/biz/importer/ImportDictionarySpec.groovy

If a column doesn't match but can be associated by using the aliases, a warning will be emitted but no real error
will be reported.

Permits to utilize aliases when verifying the column headings.

---

src/main/java/sirius/biz/jobs/BasicJobFactory.java
src/main/java/sirius/biz/jobs/JobFactory.java
src/main/java/sirius/biz/jobs/batch/BatchProcessJobFactory.java

This allows us to inspect the parameters of a job instead of asking the executor of the job
which is a little bit error prone
- Fixes: SIRI-86

Outputs all parameters of the batch job

---

src/main/java/sirius/biz/importer/format/AmountRangeCheck.java
src/test/java/sirius/biz/importer/format/AmountRangeCheckSpec.groovy

(cherry picked from commit d28cc62a69476c00f5f80351eae3afe7db68ebe8)

Ignores empty amounts (Amount.NOTHING) in range checks.

---

pom.xml
src/main/java/sirius/biz/protocol/Protocols.java
src/main/resources/component-biz.conf

Due to a bug and excessive logging, we've observed a node going down
in the AutoBatchLoop when trying to bulk insert a large amount of large log messages.

Adds an upper limit to the log message length.

---

src/main/java/sirius/biz/importer/format/DateTimeFormatCheck.java
src/test/java/sirius/biz/importer/format/DateTimeFormatCheckSpec.groovy
src/test/java/sirius/biz/importer/format/ValueCheckSpec.groovy

This detects wrong dates like the 31.09.2019 (September only has 30 days).
The trade off to this solution is, that years have to be declared with 'u' in pattern instead of 'y'.
The other option one could achieve strict parsing with is the 'SimpleDateFormat'-class, but it comes with its own set of problems, also it is legacy java.
Additional reading from StackOverflow:
DateTimeFormatter:
`uuuu` versus `yyyy`: https://stackoverflow.com/questions/41177442/uuuu-versus-yyyy-in-datetimeformatter-formatting-pattern-codes-in-java
Issues with `yyyy` isntead of `uuuu`: https://stackoverflow.com/questions/41103603/issue-with-datetimeparseexception-when-using-strict-resolver-style
SimpleDateFormat:
Ignores additional/missing characters in pattern: …

Make the parsing of dates strict in DateTimeFormatCheck

---

pom.xml
src/test/java/sirius/biz/importer/ImporterSpec.groovy

Otherwise the newly added use-after-close check will trigger.

Uses the proper method to flush a BatchContext / ImporterContext.

---

src/main/java/sirius/biz/storage/layer3/downlink/ftp/BridgeFile.java
src/main/java/sirius/biz/storage/layer3/downlink/ftp/BridgeFileSystemView.java

The current logic will create a placeholder object and returns it with findChild.
Because of that we cannot just do a null check. We also need to check the exists method of the child
- Fixes: SE-8975

Fixes the logic to allow the creation of new folders via ftp

---

pom.xml
src/main/java/sirius/biz/tenants/Tenants.java

Using a method reference can lead to a LambdaMetaFactory validate exception:
When trying to apply a map() using a Function over a multi-bounded intersection generic type, the JRE fails with error message
Caused by: java.lang.invoke.LambdaConversionException: Type mismatch for lambda argument 0: interface B is not convertible to interface A
see https://bugs.openjdk.java.net/browse/JDK-8058112

Uses a lambda instead of a method reference to prevent a jdk Bug

---

src/main/java/sirius/biz/web/BasePageHelper.java

result.getEnd() is not yet filled and therefore is always 0
Fixes: OX-5521

Uses the items.size to fill the total size on single-page-Pages

---

src/main/java/sirius/biz/process/Process.java
src/main/java/sirius/biz/process/Processes.java

The retry-loop which was previously implemented is pretty useless for two reasons.
1) The entity wasn't marked as Versioned - therefore no optimistic locking was enabled
2) The loop didn't refresh the entity before re-trying.
Fixes: OX-5352 (hopefully)

Repairs an update loop which is based on optimistic locking.

---

src/main/java/sirius/biz/tenants/UserAccountController.java

Previously, a browser reload would have triggered the action again
Fixes: OX-5364

Prevents multiple user actions by redirecting instead of invoking the main route

---

src/main/java/sirius/biz/storage/layer2/L3Uplink.java

The layer3 must be usable even if the layer2 is completely shut off.

Prevents an NPE if no layer2 framework is active.

---

src/main/java/sirius/biz/model/AddressData.java

As correctness of the zip is not checked or enforced here anyway, we might as well support more input values.
Also, full U.S. zips use 9 digits and a dash(length 10) and country codes may be prefixed.

Increases zip length to support more formats

---

src/main/java/sirius/biz/jobs/batch/file/EntityImportJob.java

Adds the context to the EntityImportJob::createOrUpdate method, since we no longer want to override the now extended EntityImportJob::handleRow logic. instead we override it in the createOrUpdate method if the user really wants to change data.
Code-Format.

Adds Context to EntityImportJob::createOrUpdate method

---

src/main/java/sirius/biz/tenants/TenantUserManager.java

the personData.beforeSave logic requires a codelist check. This requires a tenant
During the rehashing process we don't yet have access to getCurrentUser which is required.

Sets the user to run the rehashing logic to ensure that a tenant is set

---

src/main/java/sirius/biz/tenants/jdbc/SQLTenant.java
src/main/java/sirius/biz/tenants/mongo/MongoTenant.java

@AfterSave on JournalData.onSave() was being registered (and triggered) twice.
Fixes: OX-5566

Avoids logging duplicated journal entries via TenantData and main entity

---

src/main/java/sirius/biz/importer/Importer.java
src/main/java/sirius/biz/jobs/batch/file/EntityImportJob.java

Otherwise "unique" checks might fail (at the database level) as the inserts are queued in the batch
and therefore not enforced by the framework. This adds too much trouble for outweight the performance improvements
of a batched insert.
If an entity is known to not have any unique constraints / such conflicts - which is probably very rare - this method
can be overwritten and changed back to a batched insert.

Uses createNowOrUpdateInBatch as default way of updating entities.

---

src/main/java/sirius/biz/web/BasePageHelper.java
src/main/java/sirius/biz/web/ElasticPageHelper.java
src/main/java/sirius/biz/web/MongoPageHelper.java

While this is not really the purpose of these helpers, this prevents a lot of duplicate code when building processes that are linked to page views, for example export processes.
Fixes: SIRI-146

Adds some methods to re-use PageHelpers in processes to iterate over total items

---

src/main/java/sirius/biz/jobs/params/BooleanParameter.java
src/main/resources/default/templates/biz/jobs/params/selectBoolean.html.pasta

There are cases where we need to know if the parameter is selected at all and not always default to false.
Default value is false unless markNullable is used.
Fixes: OX-5522

Allows for a BooleanParameter to be nullable/optional

---

src/main/java/sirius/biz/jobs/params/BooleanParameter.java
src/main/java/sirius/biz/jobs/params/SingleSelectParameter.java
src/main/java/sirius/biz/jobs/params/StringListParameter.java
src/main/java/sirius/biz/jobs/params/StringParameter.java
src/main/resources/default/templates/biz/jobs/params/selectString.html.pasta

- Adds the ability for StringParameters to be nullable
- Adds a new StringList Parameter which can be used to render a single select of key-value string pairs

Job parameter enhancements

---

src/main/java/sirius/biz/importer/format/FieldDefinition.java

Very useful when building custom import/export dictionaries.
- stringField without length
- numericField without precision or scale
- dateField without format

Adds constructors to create fields without checks or formats

---

src/main/java/sirius/biz/importer/Importer.java
src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
src/main/java/sirius/biz/jobs/batch/file/EntityExportJobFactory.java
src/main/java/sirius/biz/jobs/batch/file/EntityImportJob.java
src/main/java/sirius/biz/jobs/batch/file/EntityImportJobFactory.java

Enhances the Importer to receive the job factory name used to initialize it
This opens the door for multiple ImportHandlers to be defined for the same target Entity.
Although in most cases only a single handler would exist for a given entity, there are some needs where a custom handler must be created for specific import or export tasks. In this case the handler can validate if its being used under the context of a specific factory in its accept method by using context.getImporter().getFactoryName().
Note that when using this feature, the **default mappings and dictionary must be defined exclusively by the job factory**, making the handler sort of exclusive to the factories.

Enhances the Importer to receive the job factory name used to initialize it

---

src/main/resources/default/templates/biz/tenants/tenant.html.pasta

And hands over the same parameter to all points of the tenant extension to prevent errors if no default value is set.

Adds an additional extension point to the tenant backend page

---

src/main/java/sirius/biz/analytics/events/UserData.java

This reverts commit 6cdf803d
As the user_id for users created by MongoTenantUserManager has a length of 43 this composite did not work.
This composite should provide a more loose length for ids and not restrict it as its has no connection to a specific UserManager Implementation and therefore should handle a variety of sensible lengths for ids.

Revert "Set length of tennantId and userId to 26"

---

src/main/java/sirius/biz/mongo/PrefixSearchableEntity.java
src/main/java/sirius/biz/tenants/mongo/MongoTenant.java
src/main/java/sirius/biz/tenants/mongo/MongoTenantAware.java
src/main/java/sirius/biz/tenants/mongo/MongoUserAccount.java

Which will be created for all MongoTenantAware entities.
⚠️ **MongoTenantAware entities must be checked for indexes including tenant and either dropped (to be recreated by this class) or have the creation suppressed by defining an index without columns.**
Fixes: SIRI-184

Defines a default Index including  the tenant and searchPrefixes

---

src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java

As there is no implicit return, we have to perform this manually here
(in contrast to all other operations).
Fixes: SIRI-185

Completes the list operation after a successful attempt.

---

src/main/java/sirius/biz/analytics/indicators/IndicatorData.java
src/test/java/sirius/biz/analytics/indicators/CheckValueIndicator.java
src/test/java/sirius/biz/analytics/indicators/IndicatorSpec.groovy
src/test/java/sirius/biz/analytics/indicators/IndicatorTestEntity.java

Fixes indicator composites so they can be persisted to the DB.
Also includes a simple test case to show how non-batch test cases work.

Properly persists indicators

---

src/main/java/sirius/biz/storage/layer3/uplink/fs/LocalDirectoryUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplinkConnectorConfig.java
src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplink.java

Remove local file exists check when creating OutputStreams for S/FTP
Set FTP FileType to Binary instead of default ASCII
Fixes: SIRI-194

Fix FTP Filetype and Upload bug

---

src/main/resources/component-biz.conf

The s3 code resides in the storage package but the config is directly loaded from s3.stores.xxx

Moves the S3 default config into the proper place.

---

src/main/java/sirius/biz/web/SaveHelper.java

This permits to directly invoke the helper using a List rather
than have to perform an ugly toArray call.

Adds a utility method for the SaveHelper.

---

src/main/java/sirius/biz/analytics/indicators/IndicatorData.java
src/main/java/sirius/biz/analytics/scheduler/MongoAnalyticalTaskScheduler.java

Indicators could be stored more than once for an entity
Batch indicators weren't validating properly against the target entity
Fixes: OX-5734

Fixes to Indicators

---

src/main/java/sirius/biz/storage/layer3/uplink/util/UplinkConnectorConfig.java
src/main/resources/component-biz.conf

By default we chose quite a low idle timeout which seems to be
in conflict with the keepalive implementation in the apache ssh client.
We now use the default idle timeout of 10m, which is still a reasonable value.

Improves the default timeout settings for ftp/sftp uplinks.

---

src/main/java/sirius/biz/importer/BaseImportHandler.java
src/main/java/sirius/biz/protocol/JournalData.java

Under heavy load, updating the journal becomes quite an overhead.
Therefore this change permits to enable batch inserts of journal entries,
if requested.
By default the BaseImportHandler will enable this when updating or
deleting Journaled entities.

Optimizes journal entries in import jobs.

---

src/main/java/sirius/biz/jobs/batch/BatchProcessJobFactory.java
src/main/java/sirius/biz/jobs/batch/SimpleBatchProcessJobFactory.java

This function proved to be very useful when talking with our customers. It also helps to
recreate an error in case a job failed.
- Fixes: SE-9020

Will also log the parameters for a simpleBatchProcessJobFactory

---

src/main/java/sirius/biz/tenants/UserAccountController.java

The getSelectableUsersAsPage() was accidentally selected in a previous
refactoring. In this case, we only want to suggest users from the same
tenant, this is also reflected in the JavaDoc comment.

Uses a proper getter to decide which users to show in an autocomplete.

---

src/main/java/sirius/biz/model/ResaveEntitiesJobFactory.java

Otherwise we cannot use this job to rebuild the search prefixes since a single update might not change any field and therefore skip the computation when not forced.

Force updating search prefixes on entity resave job

---

src/main/java/sirius/biz/model/PermissionData.java
src/main/java/sirius/biz/tenants/TenantData.java
src/main/java/sirius/biz/tenants/TenantUserManager.java

The use of getConfig always requires a null-check. This is quite cumbersome and easily forgotten. This adds a second getter that will return an empty config instead.

Adds non-null getters to PermissionData and TenantData for the config

---

src/main/java/sirius/biz/process/Processes.java

... when a process is modified so the change will be reflected on all nodes.
Fixes: SIRI-234

Flushes the coherent process cache on all nodes

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java

The `findOrCreateByPath` method was skipping the file creation if a previous find was issued which did not find any file (leaving the cache with `null` for the desired key).
This caused subsequent calls to the cache to deliver null instead of try calling the ValueComputer in order to create a new file.
Fixes: OX-5973

Fix an issue creating files in the storage

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java

Removing from the coherent cache does not mean that it's deleted right away.
Fixes: OX-5973

Returns the raw object instead of cache contents

---

pom.xml
src/main/java/sirius/biz/web/BizController.java

If the property is a boolean one, it will most probably handled
by a checkbox. As an unchecked checkbox will not submit any value
we therefore add a hidden field which is signals the presence of the
checkbox. The field is named "property"_marker.

Uses the presence marker fields for checkboxes provided in sirius-web.

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java

Paths were being delivered from the web-server's cache. This caused the effect that updated blob contents weren't being transmitted in the response.
Another nasty effect was to deliver contents belonging to other tenants if a similar path were found in the cache.

Delivers downloads not cached

---

src/main/java/sirius/biz/translations/TranslationData.java

These are required for string mappings.

Adds Length and Lob annotations to TranslationData

---

src/main/java/sirius/biz/web/BizController.java

We dont want to reset a field to null when no parameter is given in the request that matches the field.
We also use `get` instead of `getParameters` here as it takes the `WebContext::attributes` into account which allows to semi-inject parameters before loading (e.g. for providing a default value when no parameter is given).
Fixes: OX-6055

BREAKING: Only loads fields from requests when matching param is given

---

src/main/java/sirius/biz/mongo/PrefixSearchableEntity.java
src/main/java/sirius/biz/mongo/PrefixTokenizer.java

...as MongoFilterFactory#prefix filters out most special characters from the search query before comparing them to the search prefixes.
Also simplifies null-check.
-Fixes: OX-6081

Normalizes Search Prefixes

---

src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java

LineBasedProcessor for instance needs to know the actual file extension, but the file referenced by the filehandle is a temporary file with ".tmp" as extension.

Fixes file name in FileImportJob

---

src/main/java/sirius/biz/jobs/batch/file/ExportCSV.java

So export jobs have access to define things like separator, quotation etc.
Fixes: OX-6169

Exposes the CSVWriter in ExportCSV

---

src/main/java/sirius/biz/jobs/batch/BatchProcessJobFactory.java

...as an empty field after ': ' might look like a bug
- Fixes: OX-6144

Logs null parameters as '-'

---

src/main/java/sirius/biz/jobs/batch/file/ArchiveExportJob.java

Scenario is a non archive export job such as .xlsx, which is aborted due to export errors thus having no export file to pack in a zip archive.
Fixes: OX-6189

Fixes a NPE trying to close a never opened stream

---

src/main/java/sirius/biz/codelists/CodeListController.java
src/main/java/sirius/biz/codelists/CodeListData.java
src/main/java/sirius/biz/codelists/CodeListEntryData.java
src/main/java/sirius/biz/codelists/jdbc/SQLCodeListController.java
src/main/java/sirius/biz/codelists/mongo/MongoCodeListController.java
src/main/java/sirius/biz/codelists/mongo/MongoCodeListEntry.java

Error: `Ein unerwarteter Fehler ist aufgetreten: MongoQueryCompiler only supports either a search in the FULLTEXT_FIELD or an equals or prefix search in a string field (java.lang.IllegalArgumentException)`
Note: Re-Save entities is needed for MongoCodeList and MongoCodeListEntry in order to update the search prefixes.
FIXES: SIRI-264

Fixes backend search for Mongo codelists + codelist entries

---

src/main/java/sirius/biz/storage/s3/ObjectStore.java
src/test/java/sirius/biz/translations/MongoTranslatableTestEntity.java
src/test/java/sirius/biz/translations/SQLTranslatableTestEntity.java

We need this so that our bucket names are covered by the S3 wildcard certificate.

No longer enforces a "." at the start of a bucketSuffix.

---

pom.xml
src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgeFileSystemProvider.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgePosixFileAttributes.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgePosixFileAttributesView.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/SSHServer.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpFileOpener.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/scp/BridgeScpSourceStreamResolver.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeFileSystemAccessor.java

The update should fix massive performace problems
(brought in [2.5.0](https://issues.apache.org/jira/browse/SSHD-979)) as sshd now supports pipelining :)

Repairs creating directories and files via SFTP and also updates sshd.

---

src/main/java/sirius/biz/storage/layer2/BlobSoftRefProperty.java

BlobSoftRef extends from BlobHardRef and adds logic for external URLs. If a URL is set #isFilled returns true but #getBlob returns null. This leads to a NPE.

Prevent a NPE

---

src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java

BlobHardRef#getPath calls #getBlob which clears the key if the blob can't be resolved. As URLs are not real blob keys, calling #getPath on a BlobSoftRef with a referenced URL would clear the URL.

Prevent BlobSoftRef#getPath from clearing the URL

---

src/main/java/sirius/biz/storage/layer2/URLBuilder.java

If a variant is given in the URLBuilder, it's configured file extension is now always used instead of the original file's extension.

Use the the variant's file extension in the generated URLs

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java

This will speed up the unique check when saving blobs and more importantly accessing blobs via the key.

Add an unique index to the blob key

---

src/main/java/sirius/biz/tenants/TenantUserManager.java

When calculating the UserInfo this was already the case, but when calculating the tenant permission this was only done before additional roles have been calculated but we need to do this 2 times.

Applies profiles and revoked permissions after AdditionalRolesProvider

---

src/main/java/sirius/biz/jobs/JobsRoot.java

- due to sftp changes jobsroot get now also gets supplied with empty files
- those get ignored
- reusage of blobs not desired here, as jobsroot isn't a regular filesystem with regards to uniqueness of filenames
Fixes: SE-10139

Only handle upload as job file if it is not empty

---

src/main/java/sirius/biz/jobs/batch/file/VirtualFileExtractionJob.java

Removes the deletion of the archive file as the "link" is still present and will point on a not present file and we want to keep the file after extraction.
- Fixes: SE-10129

SE-10129: VirtualFileExtractionJob - Remove deletion of file

---

src/main/java/sirius/biz/jobs/params/Parameter.java

Attaches all superclasses for the delegate to ensure that subclasses of parameters are also handled correctly.
This fixes issues when rendering templates for jobs with such parameters (e.g. extending from SelectStringParameter).

Ensures that subclasses of parameters are also handled correctly

---

src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java

As we need to access an injected field to properly create the parameter
we cannot perform this in the constructor. We therefore resort to a lazy
initialization pattern.

Lazily initializes a parameter.

---

src/main/java/sirius/biz/jobs/batch/file/FileImportJobFactory.java
src/main/java/sirius/biz/jobs/batch/file/XMLExportJob.java
src/main/java/sirius/biz/jobs/batch/file/XMLExportJobFactory.java
src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java
src/main/java/sirius/biz/jobs/batch/file/XMLImportJobFactory.java
src/main/java/sirius/biz/jobs/params/ParameterBuilder.java
src/main/java/sirius/biz/jobs/params/SelectStringParameter.java

Fixes some bugs found with the breaking changes introduced with https://github.com/scireum/sirius-biz/pull/904
- FileImportJob considers archives
- XSD validation re-enabled in XML exports+imports
- Enhancement: ability to run more than one pass over an XML file with a different set of handlers
Fixes: OX-6341

Fixes for Jobs and Parameters

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java

BasicBlobStorageSpace#findVariant would only return completed variants,
which lead to BasicBlobStorageSpace#attemptToFindOrCreateVariant never
actually retrying the conversion if it failed before.

Fix the retry mechanism of variants

---

src/main/java/sirius/biz/web/BasePageHelper.java

When using Page.withTotalCount(), the last page will not show the amount of items in the query but the remaining items of the page.
Fixes: OX-6224

Properly returns the item count in a query when paginating

---

src/main/java/sirius/biz/storage/layer2/BlobCreatedRenamedHandler.java
src/main/java/sirius/biz/storage/layer2/BlobParentChangedHandler.java
src/main/java/sirius/biz/storage/layer2/ProcessBlobChangesLoop.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLDirectory.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoDirectory.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoProcessBlobChangesLoop.java

- Moving a blob to another folder triggers a new handler which can be implemented to process a parent change
- Renaming a directory marks all child blobs as parent changes and propagates it to child directories
Fixes: OX-6076

Handles additional actions to blobs and directories

---

src/main/java/sirius/biz/model/PersonData.java

This is necessary for auto-generated mails using the recipient's language (such as password mails for portal users).
Fixes: OX-6361

Adds getter for addressable name in a specific language

---

src/main/java/sirius/biz/process/Processes.java
src/main/java/sirius/biz/storage/layer1/replication/jdbc/SQLReplicationTaskStorage.java
src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java
src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
src/main/resources/component-biz.conf

* The replication task storages now properly compute the executable tasks.
* The conversion engine runs more tasks in parallel and also measures the actual conversion performance properly.
* Some cleanup in the default configs.
* If a Process get terminated due to a system restart, we now mark it as erroneous.
Fixes: SIRI-294

Misc Fixes: Replication, Conversion Engine, Processes

---

src/main/java/sirius/biz/importer/BaseImportHandler.java
src/main/java/sirius/biz/importer/format/FieldDefinition.java

Adds all defined translations as possible field aliases. This way, defining a single key in the configuration is enough to cope with various headings. Typical scenario: user front end language = de, file to import uses 'en' headers.
Example: this configuration
```
code: [ "$Product.code", "item number", "Nummer", "Article number" ]
```
with keys:
```
de: Product.code = Artikelnummer
en: Product.code = Article number
pl: Product.code = Numer przedmiotu 
```
resolves to (front end = 'de'):
**Note:** the `Article number` in the sample configuration doesn't cause any harm, but can be removed since a translation for it exists.
Fixes: OX-6355

Import Handler: smartGet over languages

---

src/main/java/sirius/biz/analytics/scheduler/BaseEntityBatchEmitter.java
src/main/java/sirius/biz/storage/layer1/replication/jdbc/SQLReplicationTaskStorage.java
src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java

As a single batch is most probably a "small" and manageable
we prefer this. Otherwise iterateAll might keep a cursor open
(e.g. when targeting MongoDB) which in turn might time out
when our processing takes too long.

Uses a list query in favor of an iterateAll.

---

src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImportJob.java

When loading multiple sheets of an Excel file or multiple CSV files from an archive, only the first sheet/file was actually being used in order to map headers into fields. Without much rework of the underlying classes, this rather simple fix forces the mappings to be reset upon processing the first row.

Fixes header mapping when importing multiple Excel sheets / CSV files

---

src/main/java/sirius/biz/jobs/params/SelectStringParameter.java

Selecting no value at all was actually delivering an Optional of a blank string and so isPresent() would always return true.

Fixes the output of a not required SelectStringParameter

---

src/main/java/sirius/biz/storage/layer3/VFSController.java

The JSON response of /fs/list is limited to 32k characters, which equates to around 150 files. Anything bigger than this leads to a broken modal. The proper fix for this would be to introduce paging and a search bar. As a quick fix we now limit the number of files to 100.

Fix the vfs modal when querying big directories

---

src/main/java/sirius/biz/storage/layer2/BlobSoftRefProperty.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java

Every BlobSoftRef adds a cascade delete handler to the Blob entity. If a blob is deleted every handler is executed, disregarding whether the blobRefs and the blobs spaces match. This leads to excessive lookups in the DB.

SIRI-315 Prevent lookups in too many entities when a blob is deleted

---

src/main/java/sirius/biz/cluster/InterconnectClusterManager.java

This change ensures a constant sorting (as in it doesnt change on every refresh of the page) for the /system/state page, making it much easier to skim by eye.

Displays the node state infos sorted by node name

---

src/main/java/sirius/biz/jdbc/DatabaseController.java
src/main/java/sirius/biz/jdbc/ExportQueryResultJobFactory.java
src/main/java/sirius/biz/jobs/BasicJobFactory.java
src/main/java/sirius/biz/jobs/batch/file/ExportXLSX.java
src/main/resources/biz_de.properties
src/main/resources/default/templates/biz/model/sql.html.pasta

If previously a job had a parameter with a default value, we would not pik this up, but rather complain and crash.
Even worse, if a scheduled job exists and is supplied with an addition parameter - for which a default value is provied - the scheduled job still stops working as the value was not picked up.
This has now been fixed.

Adds an export button for /system/sql AND fixes a bug concrening default values for jobs.

---

pom.xml
src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/BlobStorageSpace.java
src/main/java/sirius/biz/web/BlobPdfReplaceHandler.java

This can be used instead of referencing the blobs via http in case the server is having problems resolving its own domain.

Implement a handler to replace blob:// URIs in PDFs

---

src/main/java/sirius/biz/importer/format/FieldDefinition.java
src/main/java/sirius/biz/importer/format/ImportDictionary.java

This is an urgent HotFix for OXOMI and will be tagged as 29.4.3.1.
The HotFix branch will be merged into develop after approval.

Fixes handling of FieldDefinition aliases with non-latin alphabet

---

src/main/resources/default/assets/javascript/multiLanguageField.js
src/main/resources/default/assets/stylesheets/multiLanguageField.scss

The modal now opens with a fixed height, which could fit 5 input fields:
The selection menu only uses the available space:
And it renders without the need to scroll when possible:
Fixes: SIRI-334

Multilanguage field modal: Adjusts the height of the modal and the language options

---

src/main/java/sirius/biz/web/MongoPageHelper.java

Force failing a query can be done to simplify logic that should not present a query result in some conditions. Facets can not be executed on a failed query and doing so results in an exception. When using the PageHelper to transforming a query into a Page for displaying it in a template we therefore should skip executing the facets when the query is marked as force failed.
Fixes: OX-6685

Prevents error when transforming force failed query to page

---

src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
src/main/resources/default/taglib/w/codelistMultiSelect.html.pasta
src/main/resources/default/taglib/w/codelistSelect.html.pasta
src/main/resources/default/templates/biz/jobs/params/codelistentry.html.pasta

to prevent list entries like `$Country.de`
Fixes: OX-6731

Outputs the translated value for CodeListEntries again

---

src/main/java/sirius/biz/cluster/work/DistributedTasks.java
src/main/java/sirius/biz/cluster/work/WorkLoaderLoop.java
src/main/java/sirius/biz/process/Processes.java
src/main/resources/component-biz.conf

The language was being initialized once inside a thread of the thread-pool's context and further used by future tasks running on it.
Fixes: OX-6752

Fixes context and language initialization

---

src/main/java/sirius/biz/codelists/jdbc/SQLCodeListEntryImportHandler.java
src/main/java/sirius/biz/codelists/jdbc/SQLCodeListExportJobFactory.java
src/main/java/sirius/biz/codelists/jdbc/SQLCodeListImportJobFactory.java
src/main/java/sirius/biz/codelists/mongo/MongoCodeListEntryImportHandler.java
src/main/java/sirius/biz/codelists/mongo/MongoCodeListExportJobFactory.java
src/main/java/sirius/biz/codelists/mongo/MongoCodeListImportJobFactory.java
src/main/java/sirius/biz/translations/MultiLanguageString.java
src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java

- Fixes some errors induced by existing MongoCodeLists
- Exports only the fallback of value and additionalValue instead of dumping the entire MultiLanguageString, so we output `value` in the export instead of `{"fallback" : "value"}`.
-> we should probably revisit supporting multiple languages soon (see #881)
Fixes: OX-6731

Fixes Im- and Export of CodeLists

---

pom.xml
src/main/java/sirius/biz/ide/JobTaskContextAdapter.java
src/main/java/sirius/biz/jupiter/JupiterSync.java
src/main/java/sirius/biz/process/ExportLogsAsFileTaskExecutor.java
src/main/java/sirius/biz/process/ProcessContext.java
src/main/java/sirius/biz/process/ProcessEnvironment.java
src/main/java/sirius/biz/process/Processes.java
src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
src/main/java/sirius/biz/storage/s3/ObjectStore.java
src/main/java/sirius/biz/tycho/search/OpenSearchController.java
src/main/resources/biz_de.properties
src/main/resources/component-biz.conf

Processes can now provides side tasks and execute them in a "work stealing" fashion.
Also the calls to setCurrentStateMessage / setState have been refactored to
"updateStateMessage" and "forceStateMessage" to better reflect their intentions.
Also ProcessContext is now made thread safe by using ConcurrentHashMaps for timings.

Improves the API of ProcessContext and updates to the latest sirius-kernel.

---

src/main/java/sirius/biz/tenants/TenantUserManager.java

This method is sometimes used in other authenticating places (e.g. the FTP or SSH bridge) where previously a authentication would create an audit log entry but would not count towards the last login / number of logins of the account. This is now coupled more directly by moving the recordLogin call within the findUserByCredentials function where also the audit logs are written.
Fixes: SIRI-342

Ensures the login is recorded everytime findUserByCredentials is called

---

src/main/java/sirius/biz/protocol/DelegateJournalData.java
src/main/java/sirius/biz/protocol/JournalData.java
src/main/java/sirius/biz/protocol/JournalEntry.java
src/main/resources/default/templates/biz/protocol/protocol.html.pasta

This class should be used instead of JournalData when there is a need to record changes under another entity (usually the parent entity), like recording changes to product's features under the product itself instead of logging such changes directly at the child entity.
It can be constructed using an entity ref (of the entity which shall own the record) or using the id + type.
Fixes: SIRI-298

Introduces the DelegateJournalData

---

src/main/resources/default/taglib/w/multiLanguageTextArea.html.pasta
src/main/resources/default/taglib/w/multiLanguageTextField.html.pasta

If " is used inside one of the translations, it is correctly escaped using `\`. But JSON.parse expects `\` itself to be escaped (`\\"`).

Escapes the JSON in the multiLanguageStringField to allow " in the translations

---

src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java

In some cases a file must be processed from the archive more than one time.
This is typical in table-based files such as CSV, where more passes are needed in order to build hierarchies between data residing in different rows.

Allows the same file to be loaded multiple times

---

src/main/java/sirius/biz/codelists/CodeListLookupTable.java
src/main/java/sirius/biz/codelists/CustomLookupTable.java
src/main/java/sirius/biz/codelists/IDBFilteredLookupTable.java
src/main/java/sirius/biz/codelists/IDBLookupTable.java
src/main/java/sirius/biz/codelists/LookupTable.java
src/main/java/sirius/biz/codelists/LookupValue.java

These are common methods and thus factored out here as otherwise
one had to repeat "value.fetchName(value.getValue)" all the time.

Provides a toString and forceName for LookupValue.

---

src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java

Alternative If too much overkill: just make `handleFile` protected!
A dedicated method has the charm that no one messes up with the internal logic of handleFile...

Adds a method for post processing purposes

---

src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java

Extract and handle auxiliary files before files actually handled by the job
- they might be prerequisites, so its better to extract them first

Extract auxiliary files first

---

src/main/java/sirius/biz/jupiter/IDBTable.java

If a searchPath is given, but the searchValue is empty, we now
automatically return an empty result. (Previously this failed with an
IllegalArgumentException.)
We still fail, if a searchValue is present but no searchPath is
specified.

Permit an empty search in IDBTables.

---

src/main/java/sirius/biz/jobs/batch/file/ArchiveImportJob.java

Since this class overrides its parent execute() method, the variables needed to handle auxiliary files were not initialized

Initializes variables

---

src/main/java/sirius/biz/codelists/LookupTable.java

This interprets 1 as true in case the underlying table doesn't know booleans and instead store integers.

Add a method to fetch a field as a boolean

---

src/main/resources/component-biz.conf

The API kind of relies on the fact that the
"main" thread of the process is blocked if no
workers are available for work stealing.
With the previous config, we had and UNBOUNDED queue
which grew pretty quick and violently consumed
all heap.

Prohibit a queue for process side tasks.

---

src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java
src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImportJob.java
src/main/resources/biz_de.properties

This is beneficial when importing data from many files as then one row doesn't equal another.
Therefore we also log the name of each file being imported.

Permit to specify a custom name for the "Row" timing/counter.

---

src/main/java/sirius/biz/importer/BaseImportHandler.java

If the value already contains the target type, there is no need to use complex parsing.
This also fixes a bug where the `parseComplexProperty` of `SQLUserAccount` would throw an exception when the tenant is supplied as tenant-object and not as account-number-string

Simplify the parsing of complex properties inside Import Handlers

---

src/main/java/sirius/biz/process/Process.java

... by formatting them with thousands grouping symbols.
Before:
After:

Makes the process counters more readable

---

src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java
src/main/resources/biz_de.properties

only in case of an error we query the processes framework, as we want to be as quick as possible for successful conversions
Fixes: OX-6843

Logs empty conversion results as errors in a tenant specific standby process

---

src/main/java/sirius/biz/importer/ImporterContext.java

ConcurrentModificationException might occur since Java 16
update from computeIfAbsent in case the mappingFunction modifies
the map which happens when ImportHandler get resolved by lookupHandler
in other ImportHandler constructors

Resolve handlers without ConcurrentModificationException

---

src/main/java/sirius/biz/codelists/CodeLists.java

- here we have real concurrent access causing problems, no self induced change
due to mapping like with previous fixes

Fix concurrent access breaking hashmaps computeIf

---

src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
src/main/resources/biz_de.properties
src/main/resources/biz_en.properties

```
unzip -v archive.zip
Archive:  archive.zip
Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
21599  Defl:N     8665  60% 06-29-2021 08:47 8ba3606f  12130.1k4.jpg
28037  Defl:N    18916  33% 06-29-2021 08:47 70129347  99770ak3.jpg
7760705  Defl:N   509247  93% 06-29-2021 08:47 a7173782  haproxy.log.3
0  Stored        0   0% 06-29-2021 11:48 00000000  dummy.txt
--------          -------  ---                            -------
7810341           536828  93%                            4 files
```
Fixes: SIRI-373

Logs and skips 0-byte file when extracting archives

---

pom.xml
src/main/java/sirius/biz/codelists/CodeListEntryData.java
src/main/java/sirius/biz/importer/format/FieldDefinition.java
src/main/java/sirius/biz/jupiter/IDBTable.java
src/main/java/sirius/biz/tenants/TenantUserManager.java
src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java
src/main/java/sirius/biz/util/Languages.java
src/main/resources/component-biz.conf

Based on https://github.com/scireum/sirius-web/pull/864:
- Defines the default, fallback, and available languages for the default scope. Note: this provides more selectable languages to the user by default, since the previous setting (`nls.languages`) only included `de` and `en`.
- Replaces usages of the now deprecated `NLS.getSupportedLanguages`.
Fixes: SIRI-368

Language configuration via Scopes

---

src/main/java/sirius/biz/util/SevenZipAdapter.java

PropID.LAST_MODIFICATION_TIME returns a Date (or null) which can't be parsed as Long.
Therefore we use getTime or assume the Instant.now in the unlikely event where the modification date isn't present in the archive
Fixes: SIRI-373

Resolves cast error parsing 7-zip entries

---

src/main/resources/biz_de.properties
src/main/resources/default/extensions/tycho-page-menu/footer.html.pasta
src/main/resources/default/extensions/tycho-script/tycho-script.html.pasta

We now include the user/tenant name and a deep-link to be sent to support agents. This will perform the proper tenant selection and then redirect to the page the user is currently visiting.

Improves the footer of Tycho templates.

---

src/main/resources/default/templates/biz/process/process-details.html.pasta
src/main/resources/default/templates/biz/process/process-logs.html.pasta
src/main/resources/default/templates/biz/process/process-output-logs.html.pasta
src/main/resources/default/templates/biz/protocol/audit_logs.html.pasta
src/main/resources/default/templates/biz/protocol/entity_protocol.html.pasta
src/main/resources/default/templates/biz/protocol/errors.html.pasta
src/main/resources/default/templates/biz/protocol/logs.html.pasta
src/main/resources/default/templates/biz/protocol/protocol.html.pasta

| Before | After |
|:----:|:------|
| <img width="1222" alt="grafik" src="https://user-images.githubusercontent.com/3729858/124439554-d9376680-dd79-11eb-8f98-a19bcf6c5ac6.png"> | <img width="1222" alt="grafik" src="https://user-images.githubusercontent.com/3729858/124439464-bd33c500-dd79-11eb-902b-7a0e90af9ae6.png"> |
| <img width="1222" alt="grafik" src="https://user-images.githubusercontent.com/3729858/124439620-ea807300-dd79-11eb-9e97-20ba44b1b96a.png"> | <img width="1222" alt="grafik" src="https://user-images.githubusercontent.com/3729858/124439664-f9672580-dd79-11eb-916f-aa2d485f1ada.png"> |
Links to the examples:
https://webshop-test.unielektro.de/ps/Q3VG09KL8LBBU9HHPBAI908BBO/logs?type=WARNING&query=%21price+group+%21ELEKTRO+intern+data+sued-ost …

Fix whitespace wrapping for job logs in chrome

---

src/main/java/sirius/biz/analytics/events/ClickhouseSizeChartJobFactory.java

Previously, the sql engine issued an error about a "forgotten" parameter, which - in this case - is left out on purpose.

Bugfix: Avoid false-positive SQL warning on a clickhouse evaluation

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java

Example:
```
Blob blob = blobStorage.getSpace("attachments").findOrCreateByPath("file.ext");
blob.getPath() -> "/attachments/file.ext"
blob.updateContent(null, file);
ERROR: blob.getPath() -> "/attachments/null"
EXPECTED: blob.getPath() -> "/attachments/file.ext"
```
Fixes: OX-7005

Fixes calls to Blob.getFilename / Blob.getPath after updating the blob contents without providing a file name

---

src/main/java/sirius/biz/codelists/CodeListLookupTable.java
src/main/java/sirius/biz/codelists/CustomLookupTable.java
src/main/java/sirius/biz/codelists/IDBFilteredLookupTable.java
src/main/java/sirius/biz/codelists/IDBLookupTable.java
src/main/java/sirius/biz/codelists/LookupTable.java

Previously there were only ways to easily either get all entries of a table or lookup a single entry.
Fixes: OX-6913

Adds a way to retrieve all entries matching a lookup of idb tables

---

src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java
src/main/java/sirius/biz/process/ErrorContext.java
src/main/resources/biz_de.properties
src/main/resources/biz_en.properties

The DictionaryBasedArchiveImportJob parses multiple files (eg. CSV) from an archive, so we identify the current file and row being processed.
Logs errors messages (also in ProcessContext) instead of throwing them and avoiding abrupt stop (eg. when looping XML nodes)
Permits to suppress the file name when printing error messages, useful in single file operations.
Fixes: OX-7060

Enhances the ErrorContext

---

src/main/java/sirius/biz/process/ErrorContext.java

as sometimes we want to return something (like a new entity created) instead of a just executing a UnitOfWork
Fixes: OX-7060

Adds a performAndGet which invokes a producer

---

src/main/java/sirius/biz/codelists/IDBLookupTable.java

When performing a reverse-lookup we don't want any prefix matches but
only full field matched. Note that as "name" has a fulltext index, we
can lowercase the search value and make the whole operation
case-insensitive.

Uses IDB.LOOKUP in favor of IDB.SEARCH.

---

src/main/java/sirius/biz/storage/layer2/ProcessBlobChangesLoop.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoProcessBlobChangesLoop.java

As we renamed a protected method, this is technically a breaking change, but most probably without any action required.

Renames method to better reflect what it does

---

src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java

Without this boolean, the content-disposition of the tunneled response would always win. But if we've already set a name, we want to use our own Content-Disposition header.
Previously even blobs delivered via /cvd/ and given a proper filename are delivered with the original S3 content dispostion header like 
`inline;filename="EOGQNK2LS6O77P1GIGHH57SUAO";filename*=UTF-8''EOGQNK2LS6O77P1GIGHH57SUAO`
after this they will be delivered by the content disposition set in the response object, so for downloads it wil be 
`attachment;filename="test_drawing_druck_medium.jpg";filename*=UTF-8''test_drawing_druck_medium.jpg`

Correctly applies content disposition set by BlobDispatcher

---

src/main/java/sirius/biz/jobs/BasicJobFactory.java
src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountExportJobFactory.java
src/main/java/sirius/biz/tenants/jdbc/SQLUserAccountImportJobFactory.java
src/main/java/sirius/biz/tenants/mongo/MongoUserAccountExportJobFactory.java
src/main/java/sirius/biz/tenants/mongo/MongoUserAccountImportJobFactory.java

SIRI 364
This makes sure that `checkPermissions` always works consistently with `getRequiredPermissions`. Previously this was not always the case, which lead to bad user experience: The user account import did override the check, which prevented the user from executing it, but left it visible in the jobs overview.
Migration:
If you have existing overrides, refactor them to override `getRequiredPermissions` instead. You may return complex permission expressions, if required; see `Permissions#hasPermission`.

Make BasicJobFactory#checkPermissions final

---

src/main/java/sirius/biz/storage/layer1/replication/jdbc/SQLReplicationTaskStorage.java
src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java

Otherwise these tasks will never be re-scheduled.
Fixes: SIRI-397

Properly clears the transaction id for failed replication tasks.

---

src/main/java/sirius/biz/importer/BaseImportHandler.java

This was already fixed in https://github.com/scireum/sirius-biz/pull/1171, but reoccurred after merging master into develop
Fixes: OX-7173

No longer removes hidden AutoImport fields from the import.

---

src/main/java/sirius/biz/protocol/JournalEntry.java
src/main/resources/default/templates/biz/protocol/protocol.html.pasta

This change links the journal entry target identifier to the matching result page in the db query tool for system administrators.
All other users without the permission see the old plain text as before.

Provides a clickable administrator link to the query tool in journal entries.

---

src/main/java/sirius/biz/translations/MultiLanguageString.java
src/test/java/sirius/biz/translations/MultiLanguageStringSpec.groovy

Keys were already expected to be Nonnull, but empty keys could still be added forcefully. This produced fatal errors like persisted MultiLanguageStrings throwing NPEs when being loaded back from the database. Empty keys will now trigger an IllegalArgumentException and thus no longer be accepted! Missing translations should instead be handled via MultiLanguageStrings with fallback enabled.
Fixes: SIRI-375

Ensures that language keys in MultiLanguageStrings cannot be empty

---

src/main/java/sirius/biz/jobs/params/SelectStringParameter.java

They were initialized already translated and not on display, causing values to be displayed in default language
Fixes: OX-6996

Correctly translates entries from a SelectStringParameter

---

src/main/java/sirius/biz/importer/txn/ImportTransactionData.java

Otherwise this field wouldn't be considered as changed and will not be updated upon processing an already existing record. This will have a nasty side effect as calling ImportTransactionHelper.deleteUnmarked will unwillingly remove existing records.
We mark it as hidden, as we don't want it to appear in job documentation as a field which can be set by end users.
Fixes: OX-6996

Marks the txnId with AutoImport

---

src/main/java/sirius/biz/storage/layer3/uplink/fs/LocalDirectoryUplink.java

Will fix java.nio.file.DirectoryNotEmptyException which was thrown by deletion of locally mounted directories.

Differentiation between deletion of files and whole directories

---

src/main/java/sirius/biz/web/DisasterModeInfo.java
src/main/resources/component-biz.conf

See the description in component-biz.conf of
'product.defaultMaintenanceMessage' for an in-depth explanation of
what is achieved with this change.
Fixes: SIRI-413

Permits to enable the system maintenance mode by default.

---

src/main/java/sirius/biz/jobs/batch/ImportJob.java

This is useful for configuring helpers/handlers during the job creation in a job factory.
Fixes: OX-7263

Allows to access the importer of an import job externally

---

src/main/java/sirius/biz/web/BasePageHelper.java

If we don't know the total size, we don't want to supply a total item count to the page. This bug was introduced while trying to fix another bug, where fetchTotalItems wasn't applied for non-full pages that weren't at start=0.
This change keeps this fix so total items will only be filled when
**withTotalCount is enforced**
**In all other cases the totalItems will not be supplied to the Page at all.**
This behavior/bug was introduced with https://github.com/scireum/sirius-biz/pull/923
This filled totalItems produces the following error in the UI:

No longer always fills the total items with the current items

---

src/main/java/sirius/biz/process/ErrorContext.java

These methods supports the need of this very often pattern call:
``` java
ErrorContext.withContext(A, B);
ErrorContext.perform(() -> task);
ErrorContext.removeContext(A);
```
Basically similar to inContext, but logs the exceptions executed by the given task and guarantee that a context is removed after the call, successfull or not.
Fixes: SIRI-410

Adds performInContext variants

---

pom.xml
src/main/java/sirius/biz/process/ErrorContext.java
src/main/java/sirius/biz/process/ProcessEnvironment.java
src/main/java/sirius/biz/process/logs/ProcessLog.java

Permits to "build" ProcessLog entries out of an existing Exception.
If the Exception is a HandledException, automatically parses the `messageType` and `messageCount` hints if set.
Fixes: OX-7331

Improves creating ProcessLog entries out of Exceptions

---

pom.xml
src/main/java/sirius/biz/importer/BaseImportHandler.java
src/main/java/sirius/biz/importer/MongoEntityImportHandler.java
src/main/java/sirius/biz/importer/SQLEntityImportHandler.java
src/main/java/sirius/biz/jobs/batch/file/XMLValidator.java
src/main/java/sirius/biz/process/ProcessContext.java
src/main/java/sirius/biz/process/logs/ProcessLog.java
src/main/java/sirius/biz/storage/layer3/VirtualFile.java
src/main/resources/biz_de.properties
src/main/resources/biz_en.properties

- Differentiate when providing keys or messages as hints to categorize process log entries
- On errors, categorizes entities under their labels in process logs
- Marks transactional entities automatically if a transaction is open
Fixes: OX-7331
Fixes: OX-7244

ProcessLog and ImportHandler improvements

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java

By standard, the redirect header should contain the url in ISO-8859-1;
But most browsers and a lot of other clients also support UTF-8 so some servers will use UTF-8. When UTF-8 is used, the wrongly interpreted symbols will always start with the character 'Ã'. As the chance for this symbol in uppercase to be used in a correct url is pretty low, and at this point of the code we are at our last resort anyway, we will re interpret the String as UTF-8 if we come across this character.

Fixes url after following wrongly encoded redirect headers

---

src/main/java/sirius/biz/jobs/batch/file/EntityImportJobFactory.java

needed when a job wants to customize the selectable values or provide another description.
Fixes: OX-7162

Allows a job to override the ImportMode parameter

---

src/main/resources/default/extensions/biz-menu/menu-jobs.html.pasta
src/main/resources/default/extensions/biz-menu/menu-protcols.html.pasta
src/main/resources/default/extensions/biz-menu/menu-vfs.html.pasta
src/main/resources/default/extensions/wondergem-page-menu/menu.html.pasta

Adds the newly introduced permissions `permission-view-processes`, `permission-view-audit-log` and `permission-view-files` to wondergem templates, so that they don't only work for tycho.

Add new permissions to wondergem templates

---

src/main/java/sirius/biz/web/BizController.java

As Property#transformValue in sirius-db will replace empty values by the default value of the property, we need to explicitly set the value to false if we have an empty checkbox. Otherwise we would never be able to uncheck a BooleanProperty with default value of true.

Correctly prepares unchecked checkboxes for transform

---

src/main/java/sirius/biz/jobs/batch/file/ArchiveImportJob.java
src/main/resources/biz_de.properties
src/main/resources/biz_en.properties

Optional files are logged as INFO and the messages are grouped under a single key
Fixes: OX-7404

Improves optional file logging in archive imports

---

src/main/resources/default/templates/biz/process/process-logs.html.pasta

Allows the browser to break long process log messages if necessary

---

src/main/resources/default/templates/biz/process/process-logs.html.pasta

Fixes the alignment of process logs after the last fix

---

pom.xml
src/main/resources/default/templates/biz/process/process-logs.html.pasta

Keeps intentional line breaks in log messages intact

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoVariant.java

Failed Variants are marked as "-" in the cache, this needs to be removed when they are deleted so new conversion attempts will be attempted

Also removes failed variants from cache after delete

---

src/main/java/sirius/biz/web/BizController.java

This fixes a bug where lists filled by checkboxes could not be properly be emptied.
We have to check for a BooleanProperty here, because checkboxes might also be used in templates with different values and the same name to let the user fill/unfill a ListProperty or BaseEntityRefListProperty - and these templates will also send markers for the given propertyName, so this lead to these lists be filled with a single entry 'false' when they were supposed to be empty.
Fixes: OX-7503

Bugfix: Only applies empty checkbox marker for boolean properties

---

pom.xml
src/main/java/sirius/biz/translations/MultiLanguageStringProperty.java

when fallback is set, and text exists for any language code but the standard text.
Needs: https://github.com/scireum/sirius-db/pull/466
Fixes: SIRI-446

Validates missing fallback text for multi-language strings

---

src/main/java/sirius/biz/storage/layer2/BlobContainer.java
src/main/java/sirius/biz/storage/layer2/BlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java

This can be used to attache _any_ (newly created) blob to a container
without caring about the filename itself.

Permits to attach temporary (unnamed) blobs to a BlobContainer.

---

src/main/java/sirius/biz/storage/layer3/VFSController.java
src/main/resources/default/assets/scripts/vfs-modals.js
src/main/resources/default/extensions/wondergem-page/storage-vfs-modals.html.pasta
src/main/resources/default/taglib/t/fileField.html.pasta
src/main/resources/default/taglib/w/filefield.html.pasta

In wondergem, this will only limit the files displayed.
In tycho, this will also restrict the upload box to the given file types.
We use a comma seperated list of file extensions, each prefixed with '.' so we can easily feed the list directly into the dropzone library, and we can easily convert the string into a list(stream) on the server.
Fixes: SIRI-469

Adds an optional file extension filter for file picker modal

---

src/main/java/sirius/biz/codelists/jdbc/DeleteSQLCodeListsTask.java
src/main/java/sirius/biz/codelists/mongo/DeleteMongoCodeListsTask.java
src/main/java/sirius/biz/jobs/presets/jdbc/DeleteSQLJobPresetsTask.java
src/main/java/sirius/biz/jobs/presets/mongo/DeleteMongoJobPresetsTask.java
src/main/java/sirius/biz/jobs/scheduler/jdbc/DeleteSQLSchedulerEntriesTask.java
src/main/java/sirius/biz/jobs/scheduler/mongo/DeleteMongoSchedulerEntriesTask.java
src/main/java/sirius/biz/tenants/jdbc/DeleteSQLEntitiesTask.java
src/main/java/sirius/biz/tenants/jdbc/DeleteSQLUserAccountsTask.java
src/main/java/sirius/biz/tenants/mongo/DeleteMongoEntitiesTask.java
src/main/java/sirius/biz/tenants/mongo/DeleteMongoUserAccountTask.java

**BREAKING:** It is advised to specify the generic types of custom delete tasks that inherit from `MongoEntityDeleteTask` or `SQLEntityDeleteTask`.
Fixes: OX-7558

Allows to intercept before/after deletion of tenant aware entities

---

pom.xml

DEROutputStream is accessed directly in NegTokenInit which is not possible anymore and thus throws an exception while accessing cifs mounts.

Update jcifs dependency 2.1.11 -> 2.1.27

---

src/main/resources/default/assets/javascript/blobreffield.js

The extensions parameter needs to be specified even if the files should not be filtered based on the extension.

Fixes the w:blobSoftRefField taglib

---

src/main/java/sirius/biz/analytics/events/UserData.java

This caused a problem where an event was logged during login (but before the login finished)
Fixes SE-11173

We should really not attempt to bind a user "only" for event logging

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLDirectory.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoDirectory.java
src/main/java/sirius/biz/storage/util/StorageUtils.java

Fixes SIRI-491
Normalizes to Unicode NFC Form when sanitizing a path. 
This effectively means that all lookups and therefore each new blob creation is normalized to the NFC form. This also means that existing NFD forms an no longer be found, even when querying for exactly the NFD form (as it will get normalized). Therefore all existing DB objects (MongoDirectory,Mongoblob, SQlBlob...) need to be normalized to NFC. An appropriate job for this task will be provided in the next commit.
Additionally sanitizes the filename in beforeSave of vfs db objects 
This makes sure that the data in the db is consistent with the actual names we search for, even if the file or directory was not created by findByPath.
This also means that in order for existing objects to be normalized we can use a simple …

Normalizes VFS to Unicode NFC Form

---

src/main/java/sirius/biz/tenants/BaseTenantAutoSetup.java

This fixes the initial system preset with saml initially activated. Beforehand, the problem was that the saml issuer name wasn't set and the SamlController didn't offer this profile to authenticate with while also not have been adding the standard system useraccount.

SAML initial system setup fix

---

src/main/java/sirius/biz/analytics/events/ClickhouseSizeChartJobFactory.java

Clickhouse fills some tables quite rigorously which often leads to
misaligned data.

Excludes system tables from the size calculations of the database.

---

src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImport.java
src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImportJob.java

BREAKING CHANGE: not in terms of required code changes, but modified behavior.
With this change, the parameter **Ignore empty values** / **Leere Werte ignorieren** will per default be set to `TRUE`
Fixes: SIRI-483

Changes the default for the ignore empty values parameter

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/BlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/L3Uplink.java
src/main/java/sirius/biz/storage/layer3/VirtualFileSystem.java

Now using Composables to attach the blob storage space to virtual files.
Existing files are handled in wrapBlob and wrapDirectory.
Non-existing files inherit the information from their parent (if exists).
In addition, we also detect if a virtual file is a work file using the `retentionDays` config, which controls how many days files are visible before being deleted automatically by the system.
Replaces https://github.com/scireum/sirius-biz/pull/1328
Fixes: SIRI-502

Marries VirtualFiles with BlobStorageSpace - Take 3

---

src/main/java/sirius/biz/jupiter/JupiterSync.java

In case of an error, we abort the whole sync instead of deleting all
files left in the repository.
Fixes: SIRI-506

Makes the Jupiter synchronization more resilient.

---

src/main/java/sirius/biz/jupiter/JupiterSync.java

- jupiter.automaticUpdate must be evaluated at startup and end of day task

Fixes automatic jupiter update deactivate by config

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java

SQLBlob & MongoBlob and SQLDirectory & MongoDirectory sanitize the filename and additionally lowercase it for the normalized filename in a @BeforeSave method.
Thus, when looking up a blob via its filename, it also has to be sanitized before the lookup, as no blob will be found otherwise in case the filename contains characters that are removed or replaced when sanitizing.
This issue occurred in a file export job where the file to be exported included the time that was formatted with colons (which are replaced by underscores during the sanitizing). This lead to the uniqueness check failing in `BasicBlobStorageSpace#isAttachedBlobUnique` and subsequently failing the job.
The bug was introduced in #1319
- Fixes: SIRI-519

Fixes Lookup of Blobs via Filename.

---

src/main/java/sirius/biz/process/ErrorContext.java

Exposes methods to only log an exception as either error or warning (haven't seen a case for info yet, can add as the need arise).
The current logic handles errors thrown nicely logging them under the current context, but this is not sufficient.
Many times we need to log a warning, respecting the current context but carry on with processing.
This way we expose 2 methods which can be used to simply log the HandledException given.
This way we also profit from the hints attached to the message, especially the ones used to limit the number of incidences to be logged.
Fixes: OX-8105

ErrorContext: permits to only log messages under the current context

---

src/main/java/sirius/biz/importer/ImportHandlerFactory.java
src/main/java/sirius/biz/storage/README.md
src/main/java/sirius/biz/storage/layer3/BlockwiseIterator.java
src/main/java/sirius/biz/storage/layer3/ChildProvider.java
src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java
src/main/java/sirius/biz/storage/layer3/FetchFromUrlMode.java
src/main/java/sirius/biz/storage/layer3/FileSearch.java
src/main/java/sirius/biz/storage/layer3/TmpRoot.java
src/main/java/sirius/biz/storage/layer3/Transfer.java
src/main/java/sirius/biz/storage/layer3/TreeVisitorBuilder.java
src/main/java/sirius/biz/storage/layer3/VirtualFile.java
src/main/java/sirius/biz/storage/layer3/VirtualFileSystem.java
src/main/java/sirius/biz/storage/layer3/VirtualFileWalker.java

If you want to move a directory from one root to another root folder - it fails with a NoSuchElementException.
Because the next() tries to enter the directory. If there is no children anymore it should not do the same again.
Moving over root-folders is handled as a transfer, but the delete-param is ignored for directories until now...
...and fixes x typos :)

SIRI-524 fix a bug on moving files in the vfs

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java

- this prevents an fk error on first parent deletion try in case of subdirectory/ files in directory
- removes an error message as previous implementation could delete on next loop run

Removes parent reference on deletion propagation of sql directories

---

src/main/java/sirius/biz/storage/layer3/downlink/ftp/FTPServer.java
src/main/resources/component-biz.conf

The default ist "TLS" which is commonly outdated. We settle for TLSv1.2
as default, as this is pretty common and widely supported (and not
obsolete yet).

Specifies a proper (and supported) TLS protocol to use for ftps.

---

src/main/java/sirius/biz/storage/layer2/BlobRefProperty.java

This is needed in case we want to export the file path instead of the blob key via custom EntityImportHandlerExtender#createExtractor.
- Fixes: SE-11355

Allows accessing the referenced Blobs a Property

---

src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplinksRoot.java
src/main/java/sirius/biz/storage/layer3/uplink/cifs/CIFSUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplinkConnectorConfig.java

this logic was changed on https://github.com/scireum/sirius-biz/commit/4ceef427cf47ebb875a918c5f04c352ec012cfda#diff-13c6ca1150f69873e9db7d8895f3f61af6bfd141f9dce2c4560dd35f6e832527R62 accidentially

restore logic for uplinkRoot to get correct name (and id only as fallback)

---

src/main/java/sirius/biz/storage/layer3/Transfer.java

This is done as the source directory should probably not (or even can't) be deleted and deleting the source directory at the source location can be accomplished via TransferMode#MOVE.
- Fixes: SE-11421

Does not delete source directory when transferring content.

---

pom.xml
src/main/java/sirius/biz/jdbc/ExportQueryResultJobFactory.java
src/main/java/sirius/biz/jobs/batch/file/EntityExportJob.java
src/main/java/sirius/biz/jobs/batch/file/ExportCSV.java
src/main/java/sirius/biz/jobs/batch/file/ExportXLSX.java
src/main/java/sirius/biz/jobs/batch/file/LineBasedExport.java
src/main/java/sirius/biz/process/ExportLogsAsFileTaskExecutor.java

We now explicitly distinguish addListRow and addArrayRow. As otherwise,
addRow could be called with a List - which is undefined / unexpected
behavior.
Fixes: OX-8240
Reuqires: https://github.com/scireum/sirius-web/pull/1004

Uses a more consistent naming for addRow.

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java

As they are already logged in tenant standby processes and the ConversionEvent

No longer logs conversion failures to storage log

---

develop.conf
pom.xml
src/test/resources/test.conf

Note: The default clickhouse user is now called "default" instead of being empty.
Fixes: SIRI-539

Upgrades clickhouse to version 0.2.6.

---

src/main/java/sirius/biz/storage/layer3/downlink/ssh/NoopShell.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/SSHServer.java

This is required by some SFTP clients, which first start a SSH
session and then switch over to SFTP.

Provides a NO-OP shell for our built-in SSH server.

---

src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
src/main/java/sirius/biz/jobs/batch/file/LineBasedArchiveImportJob.java
src/main/resources/biz_de.properties
src/main/resources/biz_en.properties

which behaves similar to the DictionaryBasedArchiveImportJob, but WITHOUT using dictionaries.
The first row is used to define the headers later found in the context. The header can be normalized by implementing jobs, eg: to convert case or map aliases to expected names.
The following validations occur:
- rows containing more columns than the header are skipped
- header with duplicated column names will abort the file. If the file is marked as required, the entire job aborts
Fixes: OX-8345

Creates a line-based archive import job class

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
src/main/java/sirius/biz/storage/layer2/URLBuilder.java

Calling `http://.../dasd/` leads to the expected 404 (Page not found), but `http://.../dasd` (without trailing slash) causes a StringIndexOutOfBoundsException exception.
Fixes: SIRI-541

Fixes a StringIndexOutOfBoundsException exception

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/s3/ObjectStore.java

This mainly happens when the user aborts the upload by closing the tab or navigating away from the upload
Fixes: SIRI-562
To consistently catch alle aborts this PR is needed:
- https://github.com/scireum/sirius-web/pull/1030

No longer logs Interruptions when uploading from stream

---

src/main/java/sirius/biz/tycho/kb/KnowledgeBaseArticle.java
src/main/resources/default/taglib/k/base.html.pasta

This makes it easier to see the structure the user is currently in and jumping to overarching chapters to gain further knowledge.
Before:
After:
Fixes: SIRI-568

Renders parent structure of current kb article as breadcrumbs

---

src/main/resources/default/templates/biz/process/process-output-table.html.pasta

To prevent long filenames to make the report wider than intended
Fixes: SIRI-569
Before
After

Adds text breaks to process output table cells

---

src/main/java/sirius/biz/analytics/flags/PerformanceData.java
src/main/java/sirius/biz/analytics/flags/jdbc/SQLPerformanceData.java
src/main/java/sirius/biz/analytics/flags/mongo/MongoPerformanceData.java

This is e.g. required when cloning / copying entities.

Permits to clear PerformanceData entirely.

---

src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJob.java

The parameter is parsed in the LineBasedImportJob but has been fully forgotten to be evaluated here.
Fixes: OX-8606

Uses the importAllSheets in the RelationEntityImportJob

---

src/main/java/sirius/biz/storage/layer2/BlobSoftRefProperty.java

If the blob cannot be obtained, calling blob.isTemporary runs into a NullPointerException.
Also improves the code readability with some early returns.
Fixes: OX-8698

Fixes an NPE when checking if a BlobSoftRef points to a temporary space

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPSUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPSUplinkConnectorConfig.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplinkConnectorConfig.java

To connect to an FTPS server successfully not the FTPClient has to be used but its subclass FTPSClient. To do this we extend the FTPUplink and FTPUplinkConnectorConfig and setup the new client internally.
Fixes: SIRI-584

Supports creating uplinks to FTPS servers

---

src/main/resources/default/taglib/k/lookupTableLink.html.pasta

Useful when the link is expected to be rendered inline. Note that the description is then discarded from the link.

Permits rendering plain lookup table links

---

src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/ConfigBasedUplinksRoot.java

This way, we prevent a premature translation of a value,
which is done on demand now, as otherwise we'd cache
the first translation and use this for all users.

Uses Extension::getRaw to configure ConfigBasedUplinks.

---

src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
src/main/java/sirius/biz/storage/layer2/BlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/URLBuilder.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
src/main/java/sirius/biz/storage/layer3/VirtualFile.java
src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
src/main/resources/component-biz.conf
src/main/resources/default/templates/biz/process/process.html.pasta

For large downloads via the Layer2 storage, we want to generate
/dasd/xxl/... URLs which can then be detected by a downstream
proxy like Varnish and permit to optimize cache behavior.
This way, such files can be piped through without allocating large
parts of the memory in the load balancer.
This has now been enabled for blob downloads via /fs and
also for process files within /ps.

Enables large file detection for /fs and /ps.

---

pom.xml
src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
src/main/resources/component-biz.conf

Also lowers the limit for the large file detection, as some downstream
proxies/caches have smaller buffers.
Requires:
* https://github.com/scireum/sirius-web/pull/1057

Enables automatic contention control when moving large objects.

---

src/main/resources/component-biz.conf

This mainly implies that the work directory becomes case
insensitive - which is normal to most users.

Normalizes files in the work directory.

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoVariant.java

In a rare case a variant would have no parent, the deletion will not fail attempting to delete the physical object.
Fixes: OX-8586

Fixes an NPE deleting variants

---

src/main/java/sirius/biz/storage/s3/ObjectStore.java

- currently we have not uploadable files
- new limit should be 10 * 1024 * 1024 *10000 bytes = 104,8576 gb
Fixes: SE-11869

Increases the max upload size a little

---

src/main/java/sirius/biz/tenants/jdbc/SQLTenantAutoSetup.java
src/main/java/sirius/biz/tenants/mongo/MongoTenantAutoSetup.java

Attention, this is a **breaking change:** Systems can no longer rely on `wasCreated()` or `isNew()` to determine the need for extended setup routines, for instance in `@AfterSave` routines. Implement a `TenantAutoSetupExtender` to perform setup tasks explicitly.

Auto-Creation of System Tenant with Correct ID

---

src/main/resources/default/taglib/k/link.html.pasta

This change allows the link tag to be used without a name and solely an icon.
Fixes: OX-8823

Adds an empty default value to the name argument

---

src/main/java/sirius/biz/storage/layer2/L3Uplink.java

This prevents an error that would occur when start > 1000
Fixes: SIRI-610

Uses the correct page size in attachment view

---

src/main/resources/default/templates/biz/jobs/interactive-job.html.pasta
src/main/resources/default/templates/biz/jobs/job-parameters-logic.html.pasta
src/main/resources/default/templates/biz/jobs/job.html.pasta

As the page is now wider, the additional metrics block is moved to its own column on the right in order to simplify the logic in the template as well as use the additional space instead of cramming it below the job parameters.
This change also comes with using the existing execute and back buttons used in other jobs instead of splitting them up like before. In case no parameters can be set, a back button will be inserted below the graph.
Note, that the column width of the graph in the middle is defined manually instead of relying on the bootstrap framework by simply using "col-md", as some graphs like the bar chart do not calculate a correct width otherwise.
Examples including one with multiple parameters, showing that splitting the display into 3 columns keeps the page height low and …

SIRI-615: Moves Interactive Jobs Pages to Tycho.

---

src/main/java/sirius/biz/storage/layer2/ProcessBlobChangesLoop.java

to **10 min** and so avoiding a warning that the loop exceeded its runtime.
When processing a large amount of changes (eg. deleting a directory with several files), the loop might take a while to run as it fires the deletion of the physical file in the target storage.
Fixes: [SIRI-613](https://scireum.myjetbrains.com/youtrack/issue/SIRI-613)

Increases the max runtime for blob changes

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java

Upon receiving a redirect response, the response might include cookies which must be forwarded to the new redirect URL.
Fixes: [OX-8968](https://scireum.myjetbrains.com/youtrack/issue/OX-8968)

Sets a cookie manager when downloading files

---

src/main/java/sirius/biz/jobs/JobConfigData.java

The job name in this context is the visible label of the job, not its internal identifier, as this is already set in the "job" field of the entity.
Existing entities can be fixed by resaving the entities.

SIRI-619: Fixes setting the job name.

---

pom.xml
src/main/java/sirius/biz/process/ProcessController.java
src/main/resources/default/templates/biz/process/process-logs.html.pasta
src/main/resources/default/templates/biz/process/process.html.pasta

The reimplementation was necessary due to the filter options which were also added to the url, based on whatever option was chosen within the process view on the left side panel.
Fixes: [SIRI-608](https://scireum.myjetbrains.com/youtrack/issue/SIRI-608/Process-Refresh-gn%C3%A4diger-machen)

Reimplements the enable/disable functionality in pure js

---

src/main/resources/default/templates/biz/jobs/barchart.html.pasta
src/main/resources/default/templates/biz/jobs/dougnutchart.html.pasta
src/main/resources/default/templates/biz/jobs/linechart.html.pasta
src/main/resources/default/templates/biz/jobs/polarareachart.html.pasta

Previously, the set height of 180 was already ignored and instead, the chart was defined by the columns width.
This however now far exceeds the displayed height of the website.
Example:

SIRI-615: Properly limits the height of Doughnut Charts.

---

src/main/java/sirius/biz/jobs/interactive/DougnutChartJobFactory.java
src/main/java/sirius/biz/jobs/interactive/PolarAreaChartJobFactory.java

The naming convention changed with Font Awesome 5.
In addition, the icon is declared as solid ("fas") to be inline with other interactive jobs.

SIRI-627: Fixes Icons for Pie Chart Jobs.

---

src/main/java/sirius/biz/jobs/JobFactory.java
src/main/java/sirius/biz/jobs/batch/file/LineBasedExportJobFactory.java
src/main/java/sirius/biz/jobs/batch/file/LineBasedImportJobFactory.java
src/main/resources/default/taglib/w/jobs.html.pasta

We still use the w:jobs templates which links pages to capable jobs, and there the icons have gone mad, especially when they no longer match the naming, eg: fa-file -> fa fa-file works, but fa-file-excel-o is no longer found.
Note that we cannot mark this method as deprecated as biz would refuse to compile and will remove this with a future ticket.
Fixes: [OX-9090](https://scireum.myjetbrains.com/youtrack/issue/OX-9090)

Displays job icons correctly in wondergem

---

src/main/java/sirius/biz/jobs/params/FileParameter.java

- was broken in refactoring
- now, with a fileparameter accepting files and directories, it will be enough to have an existing parent directory, and the file will be created if missing
- see former implementation here: https://github.com/scireum/sirius-biz/blob/13b2fea363a58d9aa395748b4a00eae3886ceed6/src/main/java/sirius/biz/storage/layer3/FileOrDirectoryParameter.java
Fixes: https://scireum.myjetbrains.com/youtrack/issue/SE-12064

Restores fileparameter creating file logic

---

src/main/resources/component-biz.conf

When merging multiple config files, HOCON does merge objects, but not arrays. When you specify an array for e.g. security.roles in another component-<sth>.conf file, it is randomly chosen which one is loaded first. So: If a value was already loaded, we should merge it, instead of overriding it.

Don't override security config arrays from other conf files

---

src/main/java/sirius/biz/jdbc/DatabaseController.java

SQL Arrays don't recognize as real native Arrays in Java so we have to handle them separately. This will print out array fields in ClickHouse Events properly.
Fixes: SIRI-637

ClickHouse: Properly formats SQL Arrays in SQL Query Tool

---

src/main/java/sirius/biz/process/ProcessEnvironment.java

- their, the message count from previous executions in the same process might already exist
- but still we need to know the limit to generate the limit reached message at the end

Initializes limits in standby processes

---

src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java

This is _cloning_ the existing approach used by the XMLImportJob.
By default, `collectImportFiles()` functions as before and provides a list of files to collect.
If desired though, several stages can be defined, each loading a different set of files. For example: a header file is processed first and based on its contents, a different set will be processed later.
Fixes: [OX-9070](https://scireum.myjetbrains.com/youtrack/issue/OX-9070)

Permits to load groups of CSV files in stages

---

pom.xml

`WARNING [com.amazonaws.util.Base64 - com.amazonaws.log.CommonsLog] JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency.`
Fixes: [OX-9206](https://scireum.myjetbrains.com/youtrack/issue/OX-9206)

Adds suggested dependency to suppress a warning

---

src/main/java/sirius/biz/util/ArchiveExtractor.java

Up to now there are no `.so` native libs created for M1 macs (and the ARM64 Linux ones do not work n Mac M1)

Ignores 7-Zip SEVERE warning on M1 Macs

---

src/main/resources/default/extensions/tycho-page-menu/footer.html.pasta
src/main/resources/default/templates/biz/protocol/audit_logs.html.pasta
src/main/resources/default/templates/biz/protocol/entity_protocol.html.pasta
src/main/resources/default/templates/biz/protocol/errors.html.pasta
src/main/resources/default/templates/biz/protocol/logs.html.pasta
src/main/resources/default/templates/biz/protocol/mails.html.pasta
src/main/resources/default/templates/biz/protocol/protocol.html.pasta
src/main/resources/default/templates/biz/tycho/page-footer-help.html.pasta

before:
after: 
long exception-paths break now to not have a scollbar without header. The Footer is consistent for all widths without the small border before
relates to https://github.com/scireum/sirius-web/pull/1118

some cosmetics in log & footer for tycho

---

src/main/java/sirius/biz/storage/s3/ObjectStore.java

It is possible to load 0-byte files, but not using a multipart upload, which cannot be completed if no eTags were generated for each chunk loaded.
Fixes: [SIRI-651](https://scireum.myjetbrains.com/youtrack/issue/SIRI-651)

Handles uploading input streams with no contents

---

pom.xml
src/main/java/sirius/biz/protocol/LoggedMessage.java
src/main/resources/default/assets/scripts/lookup-tables.js.pasta
src/main/resources/default/templates/biz/model/schema.html.pasta
src/main/resources/default/templates/biz/process/process-logs.html.pasta
src/main/resources/default/templates/biz/process/process-output-logs.html.pasta
src/main/resources/default/templates/biz/protocol/audit_logs.html.pasta
src/main/resources/default/templates/biz/protocol/logs.html.pasta
src/main/resources/default/templates/biz/protocol/mails.html.pasta

Since border-sirius colors are now `!important`, in some combinations they overwrite other borders unintentionally, e.g. in logs:
Solves this issue by using the new left-border color styles from https://github.com/scireum/sirius-web/pull/1124:

Fixes falsely altered border colors in logs

---

src/main/resources/default/assets/scripts/images.js

Considering the entire file, I believe that the method invocation should not include the `sirius` namespace.

Method Namespace

---

src/main/java/sirius/biz/process/ExportLogsAsFileTaskExecutor.java
src/main/java/sirius/biz/process/Processes.java
src/main/resources/biz_de.properties

**Replaces #1533**
> [SIRI-645](https://scireum.myjetbrains.com/youtrack/issue/SIRI-645)
When exporting the job log, the previously `TERMINATED` process is restarted. This causes the machine serving the request to update the process state to `ACTIVE` again. This change takes some time, at most two seconds, to propagate to all connected machines. (Eventual consistency.) During that time, via Redis, execution of the export task may already be triggered on a second machine. This one checks whether the task is really marked `ACTIVE` — which may not be the case yet, leading to no further activity. The new delay is long enough to make sure that all Elastic changes have propagated before execution is even attempted.

Possible Fix: Freezing Log Export (SIRI-645)

---

src/main/java/sirius/biz/tenants/metrics/NumberOfUserInteractionsChart.java

Fixes: [OX-9339](https://scireum.myjetbrains.com/youtrack/issue/OX-9339/DataExplorer-Verf%C3%BCgbare-Charts-unklar)

Fixes permission for 'system-wide user interaction chart'

---

src/main/resources/default/templates/biz/jobs/linechart.html.pasta

These are overwritten when multiple datasets are present. Which is not possible with a const variable for obvious reasons.
Fixes: [SIRI-668](https://scireum.myjetbrains.com/youtrack/issue/SIRI-668)

Corrects variable type of line chart datasets

---

src/main/java/sirius/biz/jobs/batch/BatchProcessJobFactory.java

In cases where the job is not interactive startable we don't want to guide the user towards the form UI of the job.
Fixes: [SIRI-667](https://scireum.myjetbrains.com/youtrack/issue/SIRI-667)

Only links to job in process when job can be started via UI

---

src/main/java/sirius/biz/storage/layer1/replication/ReplicationTaskStorage.java
src/main/java/sirius/biz/storage/layer1/replication/jdbc/SQLReplicationTaskStorage.java
src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java
src/main/java/sirius/biz/storage/util/StorageMetrics.java

This metric is not really necessary as those are already represented by the difference between the total number of tasks and the number of executable tasks. But it helps to further explain that a high number of total tasks may be expected as delete tasks are delayed for a set number of days. These are not actual replications (like backing up an uploaded file) but rather deletions of the backed up file after a file is deleted in the main storage space.
Fixes: SIRI-672

Adds separate metric for number of delayed replication tasks

---

src/main/java/sirius/biz/importer/txn/ImportTransactionHelper.java

Until we better clarify how to go with this, we restore the previous functionality. The source can be set but has not effect on deletion.
Fixes: [OX-9388](https://scireum.myjetbrains.com/youtrack/issue/OX-9388)

Removes constrain for transaction source

---

src/main/java/sirius/biz/analytics/metrics/jdbc/Fact.java
src/main/java/sirius/biz/analytics/metrics/mongo/Fact.java

In most cases, 50 characters are enough as the field mostly contains fixed size strings for a given entity type and id. In special cases however, an entity might have multiple statistics of the same type, but for specific "sub categories". The name then consists of type + identifier of the "sub category". If the sub category doesn't have an ID and is instead only identifiable by a label or name of some sort, the total name may exceed the 50 character limit.
Performance: On a system with 136990 monthly metrics, the change of the field length took 1.265 seconds.

SIRI-678: Increases the size of the 'name' column for Facts.

---

src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeFileSystemAccessor.java

- default implementation using java.io file api doesn't work for our virtualfiles
Fixes: SE-12330

Makes SFTP downlink support file renaming

---

pom.xml
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPSUplinkConnectorConfig.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplinkConnectorConfig.java

Prior to Apache Commons Net 3.9.0, Net's FTP client trusts the host from PASV response by default. A malicious server can redirect the Commons Net code to use a different host, but the user has to connect to the malicious server in the first place. This may lead to leakage of information about services running on the private network of the client. The default in version 3.9.0 is now false to ignore such hosts, as cURL does.
See https://issues.apache.org/jira/browse/NET-711.

Updates to the latest commons-net to mitigate a CVE.

---

src/main/java/sirius/biz/process/ProcessEnvironment.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplink.java
src/main/java/sirius/biz/storage/util/StorageUtils.java
src/main/java/sirius/biz/storage/util/WatchableInputStream.java
src/main/java/sirius/biz/storage/util/WatchableOutputStream.java

Currently, WatchableInputStream and WatchableOutputStream use a future for the completion handling. The futures are fulfilled, once the stream is closed. Unfortunately, our Futures swallow exceptions that happen during completion handling.
The FTPClient that FTPUplink uses, mandates to check the reply code after data transmissions. If the code is an error code, the transmission wasn't successful. In order to have any chance of handling these transmission errors, we need to throw an exception.
This replaces each future with two simple completion handlers. This change is breaking as any exception that was only logged away before, is now propagated.
Replace `stream.getCompletionFuture().onSuccess(...)` with `stream.onSuccess(...)`
Fixes: …

Doesn't swallow exceptions in the completion handling of watchable streams

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java

Updating the RAW file under a Blob was not causing the BlobCreatedRenamedHandler to execute, since this only triggered if the file name changed.
Loading a new file on top of an existing blob will generate a new physicalObjectKey.
Fixes: [OX-9285](https://scireum.myjetbrains.com/youtrack/issue/OX-9285)

Invokes BlobCreatedRenamedHandler when updating the raw file

---

src/main/resources/default/taglib/t/blobImage.html.pasta

This argument determines the additional style to apply to the img object.
Fixes: [OX-9384](https://scireum.myjetbrains.com/youtrack/issue/OX-9384/Video-Modernisierung-Backend-User-Interface-Teil-1-Ubersicht)

Tycho: Allows to overwrite the image style of the blobImage tag

---

src/main/java/sirius/biz/analytics/metrics/jdbc/SQLBestEffortDailyScheduler.java
src/main/java/sirius/biz/analytics/metrics/jdbc/SQLGuaranteedDailyMetricScheduler.java
src/main/java/sirius/biz/analytics/metrics/jdbc/SQLGuaranteedMonthlyScheduler.java
src/main/java/sirius/biz/analytics/metrics/jdbc/SQLMonthlyLargeMetricsScheduler.java
src/main/java/sirius/biz/analytics/metrics/mongo/MongoBestEffortDailyScheduler.java
src/main/java/sirius/biz/analytics/metrics/mongo/MongoGuaranteedDailyMetricScheduler.java
src/main/java/sirius/biz/analytics/metrics/mongo/MongoGuaranteedMonthlyScheduler.java
src/main/java/sirius/biz/analytics/metrics/mongo/MongoMonthlyLargeMetricsScheduler.java

Schedulers are disabled if not needed anyway. We must not disable them generally, as e.g. the ProcessesDailyMetrics are registered as SQLDailyGlobalMetricComputer but should even work in Mongo environments as the underlying entities are stored in Elastic (which doesn't have its own computer and scheduler).

Always makes all metric schedulers visible

---

src/main/java/sirius/biz/storage/layer2/BlobContentUpdatedHandler.java
src/main/java/sirius/biz/storage/layer2/BlobCreatedHandler.java
src/main/java/sirius/biz/storage/layer2/BlobRenamedHandler.java
src/main/java/sirius/biz/storage/layer2/ProcessBlobChangesLoop.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoProcessBlobChangesLoop.java

- Deletes the `BlobCreatedOrRenamedHandler`
- Adds the `BlobCreatedHandler` -> triggered for new Blobs and only **after** a physical object has been set
- Adds the `BlobRenamedHandler` -> triggered for existing Blobs with renamed file name
- Adds the `BlobContentUpdatedHandler` -> triggered for existing Blobs which physical object has been replaced
We also make the whole logic more robust and guarantee that the `BlobCreatedHandler` runs before other handlers.
1. Implement the new Handlers if `BlobCreatedOrRenamedHandler` were previously used.
2. If necessary set one or more of the new flags (created, renamed, contentUpdated) for records with createdOrRenamed = true
3. Drop the obsolete column:
- Mongo: `db.mongoblob.updateMany({}, {$unset: {createdOrRenamed:1}})`
- SQL: `ALTER TABLE …

BREAKING: better handle blob changes

---

src/main/java/sirius/biz/jupiter/Jupiter.java
src/main/java/sirius/biz/jupiter/JupiterConnector.java

We used this to properly track the ram usage. However, it turned out, that the reported ram usage is incomplete (e.g. as C libraries still malloc).
See:
* https://github.com/scireum/jupiter/pull/16

Removes jemalloc as main allocator in Jupiter

---

src/main/java/sirius/biz/model/QueryController.java

Without this, in not-productive systems the system/query/api spams the log for amounts

properly output amountProperty in system/query/api

---

src/main/java/sirius/biz/analytics/scheduler/AnalyticsSchedulerExecutor.java
src/main/java/sirius/biz/analytics/scheduler/BaseAnalyticalTaskScheduler.java
src/main/java/sirius/biz/analytics/scheduler/MongoAnalyticalTaskScheduler.java
src/main/java/sirius/biz/analytics/scheduler/SQLAnalyticalTaskScheduler.java

For global metric tasks, we used abstract classes like MongoEntity or SQLEntity and created a "fake" batch which was empty otherwise. Additionally, in some cases - namely 1) in case of an exception and 2) in case of no entities present at all - no batch was generated at all.
However, having multiple levels we actually rely on at least one batch being present, so that we can add the LAST_BATCH marker and thus scheduler the next
level. So, for global runs, we now no longer use an completely empty batch description, but one with a special flag being set. Additionally, in the cases named above, we emit a completely empty batch - which is used to forward the LAST_BATCH marker but is then safely discarded.

Changes the way global "batches" are executed.

---

src/main/java/sirius/biz/jobs/params/StringParameter.java

This basically restores the previous behavior. If no default was returned, and the parameter is empty (either not in context or provided blank) we want to return a null string. Reason for that is that the output is often used in DB queries where null is expected instead of an empty string.
Fixes: [SIRI-713](https://scireum.myjetbrains.com/youtrack/issue/SIRI-713)

Returns null for empty StringParameter

---

src/main/resources/default/assets/scripts/vfs-dropzone-and-modals.js

- on "drop" and "dragend", the progress-div is not yet initialized, so we hide it before the upload even starts
- on "sending" the progress div IS initialized, so we use this event instead
- on "reset" we probably need to hide the dropzone altogether.

Improve dropzone progress bar

---

src/main/java/sirius/biz/storage/layer2/L3Uplink.java

We changed the display/fetch logic in the VFS controller to use the default zone, so we have to use the default zone here too. Otherwise these can be different resulting in time offsets when displaying the dates (e.g. uploaded 5 mins ago -> displayed as uploaded in 55 mins)

VFS: Uses the correct timezone for outputting blob modified dates

---

src/main/resources/default/assets/javascript/multiLanguageField.js
src/main/resources/default/assets/scripts/multi-language-field.js
src/main/resources/default/assets/styles/multiLanguageField.scss
src/main/resources/default/assets/stylesheets/multiLanguageField.scss
src/main/resources/default/taglib/t/multiLanguageTextArea.html.pasta
src/main/resources/default/taglib/w/multiLanguageTextArea.html.pasta

Fixes: [SIRI-696](https://scireum.myjetbrains.com/youtrack/issue/SIRI-696)
The existing styles for `max-height` and `overflow` were not properly applied.
Tycho:
Wondergem:
More compact selection in modal:

MLS Text Area: Fixes layout of language selection

---

src/main/java/sirius/biz/tenants/mongo/MongoTenantGlobalMetricComputer.java

This explains why the chart is completely empty :)
Fixes: [SIRI-657](https://scireum.myjetbrains.com/youtrack/issue/SIRI-657)

Metrics: Queries the correct class for mongo user metrics

---

src/main/resources/default/templates/biz/protocol/error.html.pasta

Allows error messages to wrap in details view

---

src/main/resources/default/templates/biz/protocol/error.html.pasta

The previous attempt to optimize the error message layout (see commit 4068508a5111d0ecbe2f714f7c7cfe015554be05) was flawed, as it destroyed the helpful formatting of Tagliatelle error messages. We now go for a pre-wrap formatting which combines the best of both worlds.
Before:
After:

Preserves the intentional use of whitespace for formatting in tagliatelle errors

---

src/main/resources/default/assets/styles/menu.scss

increased the fa search-icon size in the header on big widths and decreased the icon size of skip and the system-view on small widths. also removed destroying left padding and border on small width and move the breakpoint (see screenshot)
before:
after:

adjust css for menu size on small widths

---

src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
src/main/java/sirius/biz/storage/layer2/L3Uplink.java
src/main/java/sirius/biz/storage/layer2/URLBuilder.java

Replace `.asDownload(String)` calls by `.withFileName(String).asDownload()`
Fixes: [SIRI-749](https://scireum.myjetbrains.com/youtrack/issue/SIRI-749/URLBuilder-Inline-Download-handling-ermoglichen)

BREAKING: Improves the download with filename functionality by splitting the filename from the download in order to allow inline downloads

---

src/main/java/sirius/biz/jupiter/JupiterConfigUpdater.java
src/main/java/sirius/biz/jupiter/JupiterConnector.java
src/main/java/sirius/biz/jupiter/JupiterSync.java
src/main/java/sirius/biz/jupiter/LRUCacheConfigUpdater.java
src/main/java/sirius/biz/jupiter/RepositoryConfigUpdater.java
src/main/resources/component-biz.conf

We now utilize multiple repositories which are fed from different sources. Also, a repository can be ignored completely if none of the relevant namespaces is turned on.

Permits Jupiter to sync against multiple S3 repositories (buckets)

---

src/main/java/sirius/biz/web/BizController.java

S2 has entities which are both referenced via CASCADE and REJECT delete modes. If we delete one of these entities using `deleteEntity`, this would spawn a new process, which would immediately fail. This PR invokes the REJECT delete handlers before spawning the process.
Requires: https://github.com/scireum/sirius-db/pull/557
Fixes: [SE-12557](https://scireum.myjetbrains.com/youtrack/issue/SE-12557)

Rejects deletions early when deleting complex-delete entities

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java

Since only a few blobs are temporary, having this columns early in the index yields a much better performance.
So this change is not breaking, the updated index has been renamed, so the framework will insert a new index. As a patch task, the previous index shall be dropped.
- Mongo: `db.mongoblob.drop("blob_delete_old_temporary_loop")`
- SQL: `DROP INDEX IF EXISTS blob_delete_old_temporary_loop ON sqlblob NOWAIT`
Fixes: [SIRI-771](https://scireum.myjetbrains.com/youtrack/issue/SIRI-771)

Increases performance deleting temporary blobs

---

src/main/resources/default/templates/biz/jobs/job.html.pasta

long names now will be truncated with ... and buttons only displayed as icon on small screen

adjust styling for job-preset-list on job page

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java

- in case of blob changes, we need to cleanup all relevant caches
- unfortunately, the blobByPathCache works with paths that are not available at some layer 2 methods, so we cannot determine the cache keys
- so we use removal by filename as a good compromise to remove all required, but not to much. null value entries get removed as well
Fixes: SIRI-776

Fixes and improves blob cache invalidation

---

src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta

Fixes: [SIRI-777](https://scireum.myjetbrains.com/youtrack/issue/SIRI-777)
Whenever an image was already present and the VFS was opened, an incorrect path was passed along with it. As a result, no image could be uploaded until another folder was selected in the VFS. 
This PR corrects the path and now always searches for the parent directory of the image and then passes this.

Corrects the path for the VFS

---

src/main/java/sirius/biz/jobs/BasicJobFactory.java
src/main/java/sirius/biz/jobs/batch/file/EntityExportJobFactory.java
src/main/java/sirius/biz/jobs/batch/file/EntityImportJobFactory.java
src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJobFactory.java
src/main/java/sirius/biz/jobs/infos/CardInfo.java
src/main/java/sirius/biz/jobs/infos/JobInfoCollector.java
src/main/resources/default/taglib/t/report.html.pasta
src/main/resources/default/templates/biz/jobs/infos.html.pasta
src/main/resources/default/templates/biz/jobs/infos/card.html.pasta
src/main/resources/default/templates/biz/jobs/infos/heading.html.pasta
src/main/resources/default/templates/biz/jobs/infos/report.html.pasta
src/main/resources/default/templates/biz/jobs/infos/well.html.pasta

BREAKING: 
addWell & addTranslatedWell are renamed to addCard & addTranslatedCard
Wherever used something like this, rename the method from addWell to addCard
`protected void collectJobInfos(JobInfoCollector collector) {
collector.addWell(getDetailDescription());
}`
Example:
- fixes: SIRI-774

Brings job-documentation to Tycho

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/Blob.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java
src/main/java/sirius/biz/storage/layer2/variants/ConversionProcess.java

This is very useful in jobs already holding a physical file which can be used as source to generate several variants, without having to download the original file each time for every conversion.
Fixes: [SIRI-768](https://scireum.myjetbrains.com/youtrack/issue/SIRI-768)

Permits to start conversions from a local file

---

src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgeFileSystemProvider.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/sftp/BridgeFileSystemAccessor.java

PR #1554 implemented `renameFile` to fix renaming of files via SFTP. Unfortunately, that change broke moving them, as both are the same operation in POSIX. The default implementation uses `Files#move`, which triggers `BridgeFileSystemProvider#move`, so it makes sense to handle both cases there.
Some clients (mainly CLI) can move and rename at the same time, but implementing this increases the complexity quite a bit because our framework views both as separate operations. We keep it simple and only support one at a time. For most clients and use-cases this should be fine.
Fixes: [SIRI-775](https://scireum.myjetbrains.com/youtrack/issue/SIRI-775)

Fixes moving of files via SFTP

---

src/main/java/sirius/biz/storage/layer1/FSObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer1/FileHandle.java
src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer2/variants/ConversionProcess.java
src/main/java/sirius/biz/storage/s3/ObjectStore.java

Determines the effective file name to use for conversions.
This is necessary as the file extension is often validated as a pre-condition if a file is valid as input format. 
When `ConversionProcess.withInputFile` is used #1672, we need to know this file name instead, BUT, if the file has a `.tmp` extension we fall back to the blob's name. This very likely represents a fresh downloaded file.
**Side-Note**: the perfect solution would be to allow downloads to write a suffix to the temporary files, but that change is not so easily implemented, not without possible breaking changes.
Fixes: [OX-9819](https://scireum.myjetbrains.com/youtrack/issue/OX-9819)

Computes the effective file name to convert

---

src/main/resources/biz_de.properties
src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta

- Hides reload action
- Turns add chart action to button with text
**Before:**
**After:**
- This PR fixes or works on following ticket(s): [SIRI-787](https://scireum.myjetbrains.com/youtrack/issue/SIRI-787)

Data-Explorer: Improves Header Actions

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java
src/test/java/sirius/biz/storage/layer3/VirtualFileTest.java

- Extends VirtualFile's capability of parsing a path from a URL by giving the possibility to define a predicate to select a query string parameter that contains the path.
- This PR fixes or works on following ticket(s): [SE-12654](https://scireum.myjetbrains.com/youtrack/issue/SE-12654)

Enhances the parsing of a VirtualFile's path from a given URI

---

src/main/java/sirius/biz/protocol/Protocols.java
src/main/resources/component-biz.conf

ES < 8.7.0 has a bug were it wrongfully raises an error for  fields longer than 32766 that are not indexed in lucene (see https://github.com/elastic/elasticsearch/pull/93299).
This PR introduces a temporary limit on the length of some commonly long fields of logging entities and lowers the configured default length of LoggedMessage. We use 30k instead of 32766 as ES checks the byte length and not the character count. 30k should be good enough as the number of non-ASCII characters should be quite low.
Fixes: [SIRI-786](https://scireum.myjetbrains.com/youtrack/issue/SIRI-786)

Temporarily reduce the length of logged incidences, mails, and messages

---

src/main/java/sirius/biz/analytics/explorer/ChartFactory.java
src/main/java/sirius/biz/analytics/explorer/DataExplorerController.java
src/main/java/sirius/biz/analytics/explorer/TimeSeriesChartFactory.java

- Fixes comparison period not showing up.
- Also fixes current period values always zero.
This was caused due to two problems.
- 1st: The TimeSeries.comparisonSeries method has to be called after the dataConsumer has been registered!
- 2nd: The executeComputers method has to be called before converting a TimeSeriesData into a Dataset, since the TimeSeriesData is not set until the computers have been executed. Thus, when calling toDataset to early only zero values will be copied into the Dataset.
Fixes: SIRI-788

Fixes the export feature of the DataExplorer: now values are being exported properly

---

src/main/java/sirius/biz/tycho/UserAssistant.java

Most notably, if an invalid query string is present which only uses & and no ? we skip these paths, as TypeSafe-Config crashes on them.

Only attempts to perform a lookup for sane / plausible / working paths.

---

src/main/java/sirius/biz/analytics/explorer/DataExplorerController.java

The DataExplorer explicitely loads charts async and supports longer running computations. Therefore we must also disable the timeout of the WebServer.
Fixes: [OX-9875](https://scireum.myjetbrains.com/youtrack/issue/OX-9875/Data-Explorer-Chart-ladt-nicht)

Permits DataExplorer charts to take their time when computing a chart.

---

src/main/resources/default/templates/biz/storage/list.html.pasta

This is caused due to the single quote character breaking the string constructed within the template.
Fixes: [SIRI-720](https://scireum.myjetbrains.com/youtrack/issue/SIRI-720/Unterverzeichnis-im-Medienpool-nicht-verschiebbar-umbenennbar-wenn-es-mit-beginnt)

Fixes the rename, move and copy to clipboard feature not working for the case that the filename contains a single quote character

---

src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java

The unhandled exception prevented the fail-code-path of the doConversion/performConversion method to be working (since result.fail was never called, and therefore no onFailure handler).
For a more detailed explanation please refere to the ticket.
Fixes: [SIRI-704](https://scireum.myjetbrains.com/youtrack/issue/SIRI-704/UrlBuilder-Failed-Img-einbauen-welches-signalisiert-das-kein-Vorschaubild-da-ist-weil-ein-Fehler-aufgetreten-ist-bzw-keins)

Fixes an unhandled exception within the ConversionEngine by adding a tenant id check

---

src/main/java/sirius/biz/model/AddressData.java
src/main/java/sirius/biz/model/InternationalAddressData.java
src/main/java/sirius/biz/model/LoginData.java
src/main/java/sirius/biz/model/PersonData.java
src/main/java/sirius/biz/model/QueryController.java
src/main/java/sirius/biz/tenants/AdditionalRolesProvider.java
src/main/java/sirius/biz/tenants/ProfileController.java
src/main/java/sirius/biz/tenants/TenantUserManager.java
src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java

On switched tenant we lost the personalized icon man/woman and fallback to skip. So we copy the salutation to keep the icon.
- fixes: SIRI-796

copy salutation for resolving correct user-icon on tenant-switching

---

src/main/java/sirius/biz/storage/layer1/replication/ReplicationBackgroundLoop.java
src/main/java/sirius/biz/storage/layer2/ProcessBlobChangesLoop.java
src/main/java/sirius/biz/storage/layer2/TouchWritebackLoop.java

to cope with the growth in blobs and query times when the DB is under higher loads
Fixes: [OX-9920](https://scireum.myjetbrains.com/youtrack/issue/OX-9920)

Increases the max runtime for some loops

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java

Why? - The conversion is now usually performed in a standby-process which logs any occurring errors.
Fixes: [SIRI-743](https://scireum.myjetbrains.com/youtrack/issue/SIRI-743/Promise-failHandler-Umbauen-so-dass-man-das-logging-ins-Fehlerprotokoll-auch-ausschalten-kann)

Removes the re-throwing of the exception within the invokeConversionPipelineAsync method since it is not needed anymore

---

src/main/resources/biz_de.properties
src/main/resources/default/templates/biz/tenants/profile.html.pasta
src/main/resources/default/templates/biz/tenants/tenant-details-fields.html.pasta
src/main/resources/default/templates/biz/tenants/tenant-details.html.pasta
src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta

A previous rename from `lang` to `language` did not consider the Model.lang key, so all renamed fields without explicitly translation are left without label.
This adds a second key, maintaining compatibility to entities in product with no field renamed.

Adds Model.language in parallel to Model.lang

---

src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java

Replaces PartCollection by List in order to get rid of the warning caused by it

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java

Example from the UI, but validation occurs anywhere we attempt to get into the file's output stream.
Fixes: [SIRI-805](https://scireum.myjetbrains.com/youtrack/issue/SIRI-805)

Impedes updating contents of read-only files

---

src/main/java/sirius/biz/tenants/BaseTenantAutoSetup.java

Avoiding this startup warning:
`[2023-05-31T15:15:10.726] WARNING [di - ConfigValueAnnotationProcessor.java:43] Cannot fill security.system-saml.externalLoginIntervalDays of sirius.biz.tenants.BaseTenantAutoSetup with the config value 'externalLoginIntervalDays'. Add a Nullable annotation if this is expected, in order to suppress this warning.`

Marks a config value as nullable

---

src/main/java/sirius/biz/jobs/batch/file/FileImportJob.java

Without this fix, the importer would not get closed and subsequently the handler would not get closed and so e.g. batch queries would not get commited.

Calls super method to run required framework code

---

src/main/java/sirius/biz/storage/layer3/uplink/cifs/CIFSUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/fs/LocalDirectoryUplink.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplink.java

especially for non-existing files. 
Use case is e.g. a copy operation, where the destination file is often non existing

Fixes readonly changes in uplinks

---

src/main/java/sirius/biz/storage/layer3/uplink/cifs/CIFSUplink.java

- move changes directory, name stays the same
- name must not be set to root directory name
Fixes: SIRI-805

Uses appropriate filename in cifs fast move

---

src/main/java/sirius/biz/tenants/TenantUserManager.java
src/main/java/sirius/biz/tenants/jdbc/SQLUserAccount.java
src/main/java/sirius/biz/tenants/mongo/MongoUserAccount.java

We only copied the UserAccount entities when the current user became / spied on another user. We now use the framework to ensure that all fields are copied properly.

Remembers user-preferences even when having switched to another tenant.

---

src/main/java/sirius/biz/analytics/events/EventRecorder.java

Note that a Syntax error is thrown trying to use a bind-variable as in `SELECT SUM(${foo}) AS ...`.
But since the value added here comes from a Mapping's name, only a _programmer_ would be able to inject bad code here.
Fixes: [OX-10023](https://scireum.myjetbrains.com/youtrack/issue/OX-10023)

Permits to sum events over the provided mapping

---

src/main/java/sirius/biz/tenants/mongo/MongoTenantController.java
src/main/resources/biz_de.properties

Also moves all package specific filters to the end as the might grow quite large.
Fixes: SIRI-828

Adds PackageData.ADDITIONAL_PERMISSIONS as extra filter in the tenants view.

---

src/main/java/sirius/biz/analytics/explorer/ChartFactory.java

When computing matching charts, an access check has previously been missing. In order to do that, we need to actually resolve the target object and deal with an empty optional or exceptions. Returning `null` in such cases leads to links being omitted from `<t:charts…>`.
OX-10015

Statistics: Access Check

---

src/main/java/sirius/biz/tenants/TenantData.java
src/main/java/sirius/biz/tenants/UserAccountController.java
src/main/java/sirius/biz/tenants/UserAccountData.java
src/main/resources/component-biz.conf
src/main/resources/default/templates/biz/tenants/profile.html.pasta
src/main/resources/default/templates/biz/tenants/select-tenant.html.pasta
src/main/resources/default/templates/biz/tenants/select-user-account.html.pasta
src/main/resources/default/templates/biz/tenants/tenant.html.pasta
src/main/resources/default/templates/biz/tenants/tenants.html.pasta
src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta
src/main/resources/default/templates/biz/tenants/user-account-details.html.pasta
src/main/resources/default/templates/biz/tenants/user-account.html.pasta
src/main/resources/default/templates/biz/tenants/user-accounts.html.pasta

Tenants List:
"Select Tenant". "Select User" and "User Accounts List" use the same layout with images.
Also extracts user account details to a separate template for reusability, as was also done with tenant details in commit [1201d1914b429743fa053000466099af03a2238d](https://github.com/scireum/sirius-biz/pull/1723/commits/1201d1914b429743fa053000466099af03a2238d).
Fixes: [OX-8902](https://scireum.myjetbrains.com/youtrack/issue/OX-8902), [SIRI-606](https://scireum.myjetbrains.com/youtrack/issue/SIRI-606)
Due to the changed image variant configuration, these steps need to be performed for `TenantData` and `UserAccountData` when upgrading to this version:
- replace previous calls of `fetchSmallUrl` with `fetchMediumUrl` and `fetchMediumUrl` with `fetchLargeUrl`
- replace previous usages of …

Provides images in tenants an user accounts lists

---

src/main/java/sirius/biz/mongo/SortField.java

This can for example be used in comparators when wanting to sort a list of entities with a SortField on their lexicographic order.
Fixes: [OX-10128](https://scireum.myjetbrains.com/youtrack/issue/OX-10128)

Add getter for value of sort field

---

src/main/java/sirius/biz/tenants/TenantUserManager.java

We prefer checking the password, as we're trying to migrate away from API tokens. Therefore we monitor the logs for "AuditLog.apiTokenLogin" and place these API tokens as properly encrypted and protected password.
Once a system no longer receives these messages, we can disable the support for api tokens entirely.

Changes the order in which passwords and API-Tokens are checked

---

src/main/resources/default/templates/biz/tenants/user-account-details-fields.html.pasta

By replacing the inner `label` tag with a `span` tag, similar to the setup used in `t:checkbox`.
Fixes: [OX-8902](https://scireum.myjetbrains.com/youtrack/issue/OX-8902)

Makes roles checkbox labels clickable

---

src/main/java/sirius/biz/translations/MultiLanguageString.java

Disabled multi-language strings (depending on conditions/permissions) saves its data to the fallback key, and reading should prioritize the same.
This can be the case if a permission gets revoked and data already exists for specific languages.
In the event of dirty data, where only a language key would exist, we fallback to the language as last resort. Note that this is actually bad data, as every multi-language field depending on permissions/conditions must be declared with fallback.
Fixes: [OX-9958](https://scireum.myjetbrains.com/youtrack/issue/OX-9958)

Prioritize the fallback value reading from disabled multi-language strings

---

src/main/resources/default/templates/biz/tenants/select-tenant.html.pasta

Previously, jumping from "/tenants/select" to the second page would jump to "/tenants?start=26", which is wrong and not all users have access to it.

SIRI-837: Fix Pagination on Tenant Select Page

---

src/main/java/sirius/biz/storage/layer3/downlink/ftp/BridgeFile.java

- checks readonly state of non-existing file at parent
Fixes: SIRI-839

Fixes ftp upload

---

src/main/java/sirius/biz/translations/MultiLanguageString.java

> [OX-10242](https://scireum.myjetbrains.com/youtrack/issue/OX-10242)
This commit reverts 78eec2eae0f5e0af06a4980e8d4be6549cd6bbec. It caused users without the `content-i18n` permission to lose access to translated strings. This was particularly problematic in the OX Frontend where content is resolved for the `(public)` user who happens not to have this permission. That lead to OX delivering non-translated content.

Read-Out of Multi-Language-Strings for All Users (OX-10242)

---

src/main/java/sirius/biz/codelists/LookupTable.java

We have some cases where we need to output language or country names for example, which are not necessarily tied to LookupValue fields of entities.
Fixes: [OX-9736](https://scireum.myjetbrains.com/youtrack/issue/OX-9736)

LookupTables: Adds method to force resolve the name

---

src/main/java/sirius/biz/storage/layer3/uplink/sftp/SFTPUplink.java

- org.apache.sshd.sftp.client.impl.SftpInputStreamAsync#read(byte[], int, int) sometimes behaves incorrectly when reading a length of 0 by returning -1 whilst the actual buffer does not hit EOF yet
- see https://github.com/apache/mina-sshd/issues/398 for details
- the BufferedInputStream is a workaround, as it early returns 0 when requesting length 0

Fixes sftp inputstream reads

---

src/main/java/sirius/biz/translations/MultiLanguageString.java

This restores 9488d6b40c1d403275812545c815c7c2d61a99df (https://github.com/scireum/sirius-biz/pull/1783).

Restores Fix for `MultiLanguageString` that has been "unfixed" in OX HF2

---

src/main/java/sirius/biz/jdbc/DatabaseController.java
src/main/java/sirius/biz/jdbc/DatabaseDisplayUtils.java
src/main/java/sirius/biz/jdbc/ExportQueryResultJobFactory.java

Previously, for Clickhouse queries, the exported data would not be formatted correctly. See screenshot:
Now, the data displayed on the page and the exported data will match.

SIRI-814: Fix Exporting SQL Results

---

src/main/java/sirius/biz/analytics/metrics/MetricQuery.java

Adds a method which calculates the cumulative sum of metrics, commencing from the specified startDate and continuing until the untilDate is reached

---

src/main/java/sirius/biz/analytics/explorer/EntityChartObjectResolver.java
src/main/java/sirius/biz/jupiter/JupiterSync.java
src/main/java/sirius/biz/jupiter/JupiterSyncSystemTenantSupplier.java
src/main/java/sirius/biz/tenants/flags/CustomizationFlags.java

Enables products that do not use the _Tenants_ framework to use Jupiter by providing the system tenant differently.

Jupiter: Usability for Products without the Tenant Framework

---

src/main/resources/default/taglib/k/section.html.pasta

This renders a button in the header of a section when an anchor is given as parameter. When the button is clicked the signed URL (valid for 30 days) is expanded by the anchor, which opens the article directly at the given section.
This works for sections with and without a heading. When no anchor is given no button is rendered.

KB: Allows to easily copy the deeplink of an article section

---

src/main/resources/default/templates/biz/tenants/saml.html.pasta

enhance css on saml-login-page - now the whole card is clickable

---

src/main/java/sirius/biz/tycho/kb/OpenKbaLogHandler.java

This new log handler allows to specify a KBA ID for a ProcessLog message that is rendered as a link below the message. The link is only rendered when the user can access the article and has the title of the article as link text (like the KB message expander).
Fixes: [OX-10350](https://scireum.myjetbrains.com/youtrack/issue/OX-10350)

Processes: Allows to attach kba link to a log message

---

src/main/java/sirius/biz/process/DeleteExpiredProcessesTask.java
src/main/java/sirius/biz/process/Process.java
src/main/java/sirius/biz/process/Processes.java
src/main/java/sirius/biz/process/logs/ProcessLog.java

Drastically improves process deletion performance for processes with too many logs.
Recalculates the expiration date (needed for deletion) if the persistence is changed.
For the latter, the following script can be used to detect and optionally correct the date:
```js
let elastic = part(Elastic.class);
let tenants = part(Tenants.class);
let correct = false;
tenants.runAsAdminProcess("Check process expires", |process| {
elastic.select(Process.class).iterateAll(|proc| {
if (proc.getExpires() == null || proc.getCompleted() == null || proc.getPersistencePeriod() == null) {
return;
}
let expectedExpires = proc.getPersistencePeriod().plus(proc.getCompleted().toLocalDate());
if (expectedExpires != proc.getExpires()) {
log(proc.getId() + " - expected: " + expectedExpires + ", has: " + …
```

Improves process deletion and persistence changes

---

src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta

t:blobHardRefImage: uses the high-res default image from URLBuilder.IMAGE_FALLBACK_URI

---

src/main/java/sirius/biz/tenants/UserAccountController.java
src/main/resources/default/templates/biz/tenants/user-accounts-list.html.pasta

- saving user routes to user instead of overview
- user image centered
- long mail addresses are shortened and don't result in a line break anymore 
-> made changes in web necessary (datacard.html.pasta), the layout of other datacards isn't affected by this as far as I 
can see but if anyone has a better solution which doesn't involve web tell me:)
-> see https://github.com/scireum/sirius-web/pull/1270
fixes: OX-10216

Optimizes user UI

---

src/main/java/sirius/biz/storage/layer1/FSObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/Blob.java
src/main/java/sirius/biz/storage/layer2/BlobDuplicator.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
src/main/java/sirius/biz/storage/s3/ObjectStore.java

Used to clone a blob. This method delivers a BlobDuplicator class which collects parameters for the copy, such as variants to clone with or a new target storage space.
The new blob created is temporary and must be handled after creation (for example, attaching it to an actual BlobHardRef), otherwise it will be deleted from the system after a while.
Under the hood, it can handle copies from/to different stores.
In case of S3, a server-side copy can be performed if possible, falling back to regular download/upload when a straight copy cannot be performed.
Fixes: [SIRI-851](https://scireum.myjetbrains.com/youtrack/issue/SIRI-851)

Introduces the Blob.duplicate() method

---

src/main/java/sirius/biz/storage/layer3/VirtualFileWalker.java

1. Entering a directory should not be dependent on whether the directory has an adjacent file/directory. Thus, the 'children.hasNext()' check should be removed.
2. When leaving a directory, it can not be assumed that the parent directory has a next file/directory. Thus, 'prepareNext()' must be called recursively after setting the 'children' iterator to the next in the stack..
Fixes: SE-12943

Fixes Iterating a Virtual File Directory

---

src/main/java/sirius/biz/storage/layer3/VirtualFile.java
src/main/resources/component-biz.conf

Some systems may deal with fetching files from external servers that may require a while to respond with a valid file (e.g. when an image variant must be generated first).
Fixes: SE-12943

SE-12943: Allows Configuring a Custom Number of retries for 503 Responses

---

src/main/java/sirius/biz/protocol/IncidentController.java
src/main/resources/default/templates/biz/protocol/errors.html.pasta

This will work in all modern browsers, which should be enough as this is an internal view. Also the fallback behavior for non-supported browsers is just the previous behavior without the improvement.
The full message can always be viewed in the details page of the incident.
**Before:**
**After:**

StoredIncidents: Limits errors messages in incident list to 5 lines

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java

This was caused by a limit inside the 'mark as deleted' loop. The limit was set to 256 entities. Also, the loop was only executed once per day. This was problematic since we create over 1000 paperclips a day which resulted in a big yam, and it looked like we are not deleting files past their retention date.
Removing the limit should be safe since we only switch a flag/update each entity. The actual deletion is performed in another task which has a limit. The limit here is not a problem since the actual deletion task is executed "constantly" in a loop with other tasks.
Fixes: [SIRI-785](https://scireum.myjetbrains.com/youtrack/issue/SIRI-785)

Fixes an issue where paperclip files have not been deleted from the S3 storage, although they were older than the retention date

---

src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta

Previously the data explorer messed with the tycho history and did not handle reloads and back navigation very well.
Now the data explorer writes his own states and tries to apply the state of the URL when navigating in the history.
This includes showing the overview, adding charts and removing charts.
For this to work some methods had to be expanded by a silent parameter, which skips the URL and history update. These are used whenever the page load or history state handling are calling the methods. Only the UI elements should update the URL and history state. Otherwise reloads, etc. would introduce multiple duplicate entries in the browser history.
Fixes: [SIRI-791](https://scireum.myjetbrains.com/youtrack/issue/SIRI-791)

Data Explorer: Improves History Handling

---

src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java

Normally this class has a mechanism that deletes previous tasks when a new task is created. Regardless this failed for a few files and an update task existed even though a deletion also existed. This means the update task cant succeed as the file is already removed from the main storage. To reduce the amount of scary error messages in such cases we check whether a equivalent deletion task exists when an update task fails. If that is the case we only output a warning (so its still traceable if noticed). Also we mark the task as failed to prevent the loop from re-trying the update.
Fixes: [SIRI-878](https://scireum.myjetbrains.com/youtrack/issue/SIRI-878)

Storage: Only warns about a failing update task when deletion is queued

---

src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta

This lead to problems when customers created folders with single ticks (') in their names. Which is quite common in some languages.
Fixes: [SIRI-807](https://scireum.myjetbrains.com/youtrack/issue/SIRI-807)

Tycho: Escapes single ticks in the dropzone upload URLs

---

src/main/resources/component-biz.conf
src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta

This is actually the only converter that is registered by default. All other (more complex) converters have to be implemented by users of sirius.
Fixes: [SIRI-887](https://scireum.myjetbrains.com/youtrack/issue/SIRI-887)

Tenants: Uses identity converter for tenant and user images

---

src/main/resources/default/templates/biz/process/process-output-table.html.pasta

**Before:**
**After:**
Fixes: [OX-10473](https://scireum.myjetbrains.com/youtrack/issue/OX-10473)

Allows extensive process tables to scroll horizontally

---

src/main/java/sirius/biz/web/BizController.java

The dash is not necessary for production use, but for tests.

Referer Regex

---

pom.xml
src/main/java/sirius/biz/importer/format/BaseFieldDefinitionTransformer.java

We already do that when adding aliases defined by `importer.aliases.<entity>.<field>`, but not for the fields itself.
**Before**
**After**
- This PR fixes or works on following ticket(s): [SIRI-866](https://scireum.myjetbrains.com/youtrack/issue/SIRI-866)
- This PR is related to PR: https://github.com/scireum/sirius-db/pull/599

Translates field when generating job documentation pages

---

pom.xml
src/main/resources/default/extensions/tycho-page-menu/menu.html.pasta
src/main/resources/default/taglib/t/actions.html.pasta
src/main/resources/default/templates/biz/model/query-header.html.pasta
src/main/resources/default/templates/biz/model/redis.html.pasta
src/main/resources/default/templates/biz/model/sql.html.pasta
src/main/resources/default/templates/biz/password/password-tycho.html.pasta
src/main/resources/default/templates/biz/tycho/analytics/data-explorer.html.pasta
src/main/resources/default/templates/biz/tycho/search/search.html.pasta

fields are automatically autofocused via primary-autofocus-js so extra autofocus on input has to be removed.
- This PR is related to PR: 
- https://github.com/scireum/sirius-web/pull/1311

correct autofocus for pages with useful autofocus

---

pom.xml
src/main/resources/default/taglib/k/article.html.pasta
src/main/resources/default/taglib/k/base.html.pasta

* By default no sidebar is rendered in an article or any kb page which uses the kb base as long as there is no sidebar block with content.
* An article must have a `<i:block name="sidebar">` block with actual content in order for the sidebar to show up.
-> Therefore, every article and part of the kb should behave as before.
- This PR fixes or works on following ticket(s): [SIRI-890](https://scireum.myjetbrains.com/youtrack/issue/SIRI-890)

Adds a sidebar to the base of the kb and enables it in the kb articles

---

src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java

as the unhandled exception exists the job execution thus skipping proper handling of the source file's read-only flag.
- This PR fixes or works on following ticket(s): [SIRI-899](https://scireum.myjetbrains.com/youtrack/issue/SIRI-899)

Unlocks files when extraction fails

---

src/main/java/sirius/biz/tenants/Tenants.java

The previous implementation used `tenants.getCurrentUser()` which resolves a database object. However, if we use synthetic users (as we do, for instance, in `tenants.runAsAdminOfTenant(…)`), there is no database entry, and this method always returned **null**. A `UserInfo` object on the other hand can always be resolved, and along with it a tenant object.

Fix: Current Tenant from `UserInfo`

---

src/main/java/sirius/biz/cluster/work/DistributedTasks.java
src/main/java/sirius/biz/jobs/Jobs.java
src/main/java/sirius/biz/jobs/JobsRoot.java
src/main/java/sirius/biz/jobs/batch/BatchProcessTaskExecutor.java
src/main/java/sirius/biz/process/ProcessEnvironment.java
src/main/java/sirius/biz/process/Processes.java
src/main/java/sirius/biz/tenants/Tenant.java
src/main/java/sirius/biz/tenants/Tenants.java
src/main/java/sirius/biz/tenants/UserAccountData.java

Previously, synthetic admin users were not restored when launching a process, as the `ADMIN` identifier does not belong to an actual database entity. Therefore, like in `Tenants.asAdminOfTenant(…)`, we need to initialise a new synthetic user with all respective permissions.
- `ProcessEnvironment.getUserId()` → `ProcessEnvironment.fetchUserId()`
- `ProcessEnvironment.getTenantId()` → `ProcessEnvironment.fetchTenantId()`
- This PR is related to PR: https://github.com/scireum/sirius-web/pull/1327

Fix: Restores Synthetic Administrator User in Processes

---

src/main/java/sirius/biz/process/Processes.java

Makes existing "setter" for process persistence publicly visible. This enables process to change their default persistence, depending on the outcome.

Process Persistence

---

src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
src/main/java/sirius/biz/storage/layer2/URLBuilder.java
src/main/java/sirius/biz/storage/util/StorageUtils.java
src/main/java/sirius/biz/tenants/TenantData.java
src/main/java/sirius/biz/tenants/UserAccountData.java
src/main/resources/component-070-biz.conf

- The return of `StorageUtils.verifyHash` has changed from boolean to Optional<Integer>. This method is unlikely called by products directly but if so, an empty optional means `false`.
- Kills `URLBuilder.reusable()`. Technically speaking this is the same as `.delayResolved().eternallyValid()`
- Re-Introduces `URLBuilder.eternallyValid()` which solely dictates URL validity, independent on URL type (virtual x physical)
- Ties the cache of a generated URL to its validity. Eg: if an URL in only valid 30 days, its Cache-Control & Expires headers will react so.
- Increases the validity of RAW tenant and user-account files to 30 days
- Makes variant URLs of tenants and user-accounts eternally valid
- This PR fixes or works on following ticket(s): …

Revamps Storage URLs validity and caching

---

src/test/kotlin/sirius/biz/storage/layer1/ReplicationTest.kt

jUnit: Migrate ReplicationTest to Kotlin

---

src/main/java/sirius/biz/codelists/LookupTables.java

- in the past the 'lookup-tables' extension 'name' was used as fallback using a Strings#firstFilled
- this was broken in https://github.com/scireum/sirius-biz/commit/6e23dfb39d94fb8f380f701d842e649b7eefa1ef as by now, only a configured code list in the 'lookup-tables' extension field 'codeList' does lead to the usage of the code list implementation
- as this break did not cause major damage, lets stay with the current behavior
- so by now, configuration of lookup-tables.XYZ.codeList.XYZ will remain mandatory for code lists
- and the code gets cleaned for clarity
- 
- This PR fixes or works on following ticket(s): [SIRI-908](https://scireum.myjetbrains.com/youtrack/issue/SIRI-908)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/1784

Clarifies priority of lookup table fallbacks

---

src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java

When redirecting from a eternally valid virtual URL into a physical one, we want it to be eternally valid as well. Otherwise it will have the default validity as defined by the storage space. 
- This PR fixes or works on following ticket(s): [OX-10300](https://scireum.myjetbrains.com/youtrack/issue/OX-10300)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/1880

Propagates the eternally valid information from virtual to physical URLs

---

src/main/java/sirius/biz/codelists/LookupValueProperty.java

Otherwise, `EntityDescription.isChanged` always reports empty LookupValueProperty as changed since they hold an empty string, opposed to `null` as persisted in the DB.
Drive-By: typo fix
- This PR fixes or works on following ticket(s): [OX-10597](https://scireum.myjetbrains.com/youtrack/issue/OX-10597)

LookupValueProperty: Considers empty strings as null

---

src/main/java/sirius/biz/util/ReportUnusedNLSKeysJob.java

This removed all keys from the missing keys set, as toString on a text node wraps the text into "", resulting in ""Key"" which is not contained in the initial set.
- This PR fixes or works on following ticket(s): [SIRI-901](https://scireum.myjetbrains.com/youtrack/issue/SIRI-901)

Parses unused NLS keys from other nodes correctly

---

src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgeFileSystem.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgePath.java

- Problem since library version upgrade
- We need to support some more bridge filesystem logic
- The need for this was introduced by new check in https://github.com/apache/mina-sshd/commit/a61e93035f06bff8fc622ad94870fb773d48b9f0
- This PR fixes or works on following ticket(s): [SIRI-913](https://scireum.myjetbrains.com/youtrack/issue/SIRI-913)

Fixes sftp deletion of files

---

src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgeFileSystem.java
src/main/java/sirius/biz/storage/layer3/downlink/ssh/BridgePath.java

- with S3, the new apache mina root directory symlink check behaves a little different than with local filesystems, thus we need to implement more methods at BridgePath
- also we need to remove the restriction at BridgeFileSystem
- Note: Removing the restriction would be enough to fix this specific bug, but it does not feel good to have the apache mina library work on invalid paths. So the BridgePath do fix this as well
- This PR fixes or works on following ticket(s): [SIRI-913](https://scireum.myjetbrains.com/youtrack/issue/SIRI-913)

Fixes sftp deletion on S3 backed filesystems

---

src/main/java/sirius/biz/model/QueryController.java

Enhances the suggestion filtering algorithm used in the entity dropdown of the Query Tool.
This allows to more easily search for sub-texts of the entity names.
Examples:

Fuzzy matches entity names in Query Tool

---

src/main/resources/default/templates/biz/packages/additional-and-revoked-permissions.html.pasta

Before:
After:
- This PR fixes or works on following ticket(s): [OX-10622](https://scireum.myjetbrains.com/youtrack/issue/OX-10622)

Fixes alignment for tenant permission table in safari

---

src/main/java/sirius/biz/tycho/kb/KnowledgeBaseController.java

This is a common mistake (by me) when quickly trying to open the Knowledge Base.

Redirects to the correct KB entry point on typo

---

src/main/java/sirius/biz/locks/LocksCommand.java

Extends the `locks` console command to reset all locks at once.

Locks Command

---

src/main/java/sirius/biz/storage/layer2/L3Uplink.java

After:
- This PR fixes or works on following ticket(s): [OX-10635](https://scireum.myjetbrains.com/youtrack/issue/OX-10635)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/1901

Fetches total count for blobs in VFS-UI

---

pom.xml
src/main/java/sirius/biz/process/DeleteExpiredProcessesTask.java
src/main/java/sirius/biz/storage/layer1/replication/jdbc/SQLReplicationTaskStorage.java
src/main/java/sirius/biz/storage/layer1/replication/mongo/MongoReplicationTaskStorage.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlobStorageSpace.java
src/main/java/sirius/biz/tenants/jdbc/DeleteSQLEntitiesTask.java
src/main/java/sirius/biz/tenants/mongo/DeleteMongoEntitiesTask.java

To avoid database-connection-timeouts we use streamBlockwise insted of iterate/iterateAll on deletions
- This PR fixes or works on following ticket(s): [SIRI-915](https://scireum.myjetbrains.com/youtrack/issue/SIRI-915)

streamBlockwise deletions SIRI-915

---

src/main/java/sirius/biz/storage/layer3/MutableVirtualFile.java
src/main/java/sirius/biz/storage/layer3/VirtualFile.java
src/main/resources/default/templates/biz/storage/list.html.pasta

Before:
After:
- This PR fixes or works on following ticket(s): [OX-10603](https://scireum.myjetbrains.com/youtrack/issue/OX-10603)
- This PR is related to PR: https://github.com/scireum/oxomi/pull/10773

Encased description in raw to implement HTML formatting in /fs

---

src/main/java/sirius/biz/codelists/CustomLookupTable.java

This is needed to "override"  base defined entries in a custom file and not duplicate it in the system (where the difference is not easily visible)

Filter out duplicated defined custom-entries and only take the custom one

---

src/main/java/sirius/biz/storage/layer3/VirtualFileSystem.java
src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
src/main/resources/component-070-biz.conf
src/main/resources/default/templates/biz/storage/list.html.pasta

The new permission `permission-unlock-files` is now used to allow a user to unlock files, which the goal to customized roles to support this action.
Sys admins have the permission by default, thus non-breaking.
- This PR fixes or works on following ticket(s): [SIRI-927](https://scireum.myjetbrains.com/youtrack/issue/SIRI-927)

Defines a new permission for unlocking files

---

src/main/resources/default/templates/biz/cluster/locks.html.pasta

Redefining the locals inside is a workaround for locals seemingly not being passed into a block.
- This PR fixes or works on following ticket(s): [SIRI-928](https://scireum.myjetbrains.com/youtrack/issue/SIRI-928)

Allows to unlock all locks at once

---

src/main/java/sirius/biz/tenants/metrics/computers/UserAccountAcademyMetricComputer.java

The onboarding videos have no history like event, therefore counts are only valid in the current period of interest.
- This PR fixes or works on following ticket(s): [OX-10593](https://scireum.myjetbrains.com/youtrack/issue/OX-10593)

Avoids computing metrics for user education

---

src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java

- Handles a kind of rare error seen in our systems: `Premature end of Content-Length`
- Logs missing objects as warning and not a useless stack trace.
- This PR fixes or works on following ticket(s): [SIRI-922](https://scireum.myjetbrains.com/youtrack/issue/SIRI-922)
- This PR fixes or works on following ticket(s): [SIRI-923](https://scireum.myjetbrains.com/youtrack/issue/SIRI-923)

Improvements handling S3 responses

---

docker-compose.yml
src/test/resources/docker-compose.yml

- This PR fixes or works on following ticket(s): [DO-139](https://scireum.myjetbrains.com/youtrack/issue/DO-139)
```js
db.adminCommand( { getParameter: 1, featureCompatibilityVersion: 1 } )
db.adminCommand( { setFeatureCompatibilityVersion: "6.0" } )
```

Upgrades the mongo container to 6.0.13

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLProcessBlobChangesLoop.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoProcessBlobChangesLoop.java

when a directory is deleted, we mark all children as deleted as well. For this, we also provide the **spaceName** and **deleted** fields in the constraint in order to hit an index.
Children of a directory NEVER BELONGS to a different space than its parent.
You can temporarily mitigate this issue by adding a temporary index to `[MongoBlob|Sql]Blob.parent`
- This PR fixes or works on following ticket(s): [SIRI-932](https://scireum.myjetbrains.com/youtrack/issue/SIRI-932)

Improves query performance when directories are deleted

---

src/main/resources/default/templates/biz/model/query-results.html.pasta

This makes it actually possible to distinguish between values that are read from DB and values that are filled via the default value in the Java-Entity because the field is empty in the DB.
**Example:**
This field is actually not filled with the current date and time, but rather it is empty in the Database.
- This PR fixes or works on following ticket(s): [SIRI-935](https://scireum.myjetbrains.com/youtrack/issue/SIRI-935)

Query Tool: Marks fields that are actually empty in DB

---

src/main/java/sirius/biz/importer/format/ImportDictionary.java

Sometimes we have enhanced dictionaries where labels with the same name will be added and always an exception due to a doubled alias will be thrown. With this approach we suffix the labels with the name to ensure uniqueness. Example: WEIGHT and NET_WEIGHT both are translated with "Gewicht" and added to the same import-dictionary will result in "Gewicht" and "Gewicht_NET_WEIGHT" now. (see Screenshots)
- fixes: SE-13234
- This PR fixes or works on following ticket(s): [SIRI-](https://scireum.myjetbrains.com/youtrack/issue/SIRI-)

ensure unique labels in import-dictionaries

---

src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java

Kinda rare, since a ClosedChannelException is usually the exception by disconnection, but research in out haproxy logs shows client-disconnects when this exception is thrown.
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/1928

S3 Storage stream: Ignores SocketException

---

.github/workflows/enforce-pr-label.yml

- The required labels are used for auto-categorizing GA release notes
- The forbidden labels are used to prevent accidentally merging unfinished PRs

Adds an GH action which controls the PR labels before merging

---

src/main/java/sirius/biz/analytics/scheduler/BaseEntityBatchEmitter.java

By using streamBlockwise instead of interateAll.
Although batches are emitted to only 250 entities by default (can be overwritten), for each entity, all relevant computers are called, causing the cursor to remain open for quite a long time.
We've seen a MongoCursorNotFoundException at a productive MongoDB instance.
**BREAKING**: Note that mongo queries shall not provide sorting, which is incompatible with streamBlockwise.

Avoids cursor exception processing analytic computers

---

src/main/java/sirius/biz/storage/util/StorageUtils.java

in case of only illegal characters or e.g. single / \ | %,... we allowed the renaming and it could crash the file system
- fixes: SE-13427
- This PR fixes or works on following ticket(s): [SE-13427](https://scireum.myjetbrains.com/youtrack/issue/SE-13427)

fix rare case of sanitizing file names with illegal characters

---

pom.xml
src/main/resources/default/templates/biz/tenants/tenant-saml.html.pasta

- This PR fixes or works on following ticket(s): [OX-10835](https://scireum.myjetbrains.com/youtrack/issue/OX-10835)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/1940

Changes to use input pattern for SAML fingerprint instead of js script tag

---

src/main/java/sirius/biz/tycho/kb/KnowledgeBaseMessageExpander.java

Example: `See kba:22MEJ#information-types for possible values.`
- This PR fixes or works on following ticket(s): [OX-10861](https://scireum.myjetbrains.com/youtrack/issue/OX-10861)

Enhance KBA message expander to support linking to section via anchor

---

src/main/java/sirius/biz/codelists/CodeListController.java
src/main/java/sirius/biz/codelists/jdbc/SQLCodeListController.java
src/main/java/sirius/biz/codelists/mongo/MongoCodeListController.java
src/main/resources/default/taglib/t/multiLanguageTextField.html.pasta
src/main/resources/default/templates/biz/codelists/code-list-entries.html.pasta
src/main/resources/default/templates/biz/codelists/code-list-entry.html.pasta

Due to changes of Bootstrap5 we set the code to disabled to have correct css. disabled field won't be sent in the request, so we change the route and include the id in the route. This also unifies the behaviour to many other routes, where /entity/new is the route to create a new entity and /entity/:1 will show the editor as well for entry with given id.
BREAKING - Changed behaviour: - if you create a new code-list-entry with an existing code we now no more edit the existing one (which was also kindly unintuitive until now) and will throw an error instead..
Occurrences of route-calling of `/code-list/:1/entry` must be changed to `/code-list/:1/entry/:2`
- This PR fixes or works on following ticket(s): [SIRI-942](https://scireum.myjetbrains.com/youtrack/issue/SIRI-942)
- This PR is related …

SIRI-942 revamp saving of code-list-entries

---

src/main/java/sirius/biz/process/Processes.java

- when running on an empty db, autosetup might create a system tenant
- we require the tenant's name at process creation, so wait a little longer before evaluating the supplier
- this might be relevant in test scenarios where empty databases are used frequently
- This PR fixes or works on following ticket(s): [SIRI-939](https://scireum.myjetbrains.com/youtrack/issue/SIRI-939)

Relaxes race condition with autosetup a little

---

src/main/java/sirius/biz/jobs/batch/file/ArchiveImportJob.java

- Streaming: The new method wraps an already existing interface accepting a pointer to a consumer. The stream object allows for more readable filtering and processing.
- Error Handling: Refactoring the creation of exceptions into a helper method allows use in `Optional.orElseThrow(…)`, leading to shorter and more elegant code.
- This PR fixes or works on following ticket(s): [OX-10756](https://scireum.myjetbrains.com/youtrack/issue/OX-10756)

`ArchiveImportJob`: Improvements

---

src/main/java/sirius/biz/tycho/kb/KnowledgeBaseEntry.java

Before https://github.com/scireum/sirius-db/pull/647 the framework did not enforce this on Elasticentities. Now we must annotate the fields properly. 
- This PR fixes or works on following ticket(s): [SIRI-939](https://scireum.myjetbrains.com/youtrack/issue/SIRI-939)
- This PR is related to PR: https://github.com/scireum/sirius-db/pull/647

Properly marks field as nullable

---

src/main/java/sirius/biz/tycho/kb/SynchronizeArticlesTask.java

A simple log statement is enough here, previous exception handling was already handled without logging
- This PR fixes or works on following ticket(s): [SIRI-939](https://scireum.myjetbrains.com/youtrack/issue/SIRI-939)
- This PR is related to PR: https://github.com/scireum/sirius-db/pull/647

Properly logs errors at KB sync task

---

src/main/resources/default/templates/biz/login.html.pasta

In order to route back to the originally intended site after a SAML login, the login site stores the original URL in the local storage. This is done by passing the URL to the Pasta template and rendering the string as part of a respective JavaScript snippet. If a URL contains characters with significance in HTML such as `&`, though, the Pasta string renderer converts these to HTML entities unless everything is placed within `<i:raw>`.
- This PR fixes or works on following ticket(s): [SIRI-937](https://scireum.myjetbrains.com/youtrack/issue/SIRI-937)

SAML: Redirect Fix

---

src/main/java/sirius/biz/jobs/batch/ImportBatchProcessFactory.java
src/main/java/sirius/biz/scripting/TypedScriptableEvent.java
src/main/resources/component-070-biz.conf

Permits quickly access to the ErrorContext, saving the need to type `sirius.biz.process.ErrorContext.get()...` in the script.
This is useful to log messages using the current import context. 
```js
log(event.getErrorContext().enhanceMessage("Leere Produktbeschreibung übersprungen"))
```
```
Leere Produktbeschreibung übersprungen (Produkt: 411061, Text: DESCRIPTION_PLAIN)
```

Tenant Scripting enhancements

---

src/main/resources/default/kb/en/user/noodle.html.pasta
src/main/resources/default/kb/en/user/tagliatelle.html.pasta

- This PR fixes or works on following ticket(s): [OX-10926](https://scireum.myjetbrains.com/youtrack/issue/OX-10926)

KBA: Fixes links not opening in new tab in OXOMI KBAs

---

src/main/java/sirius/biz/jobs/batch/ImportBatchProcessFactory.java

The parameter is required and should only be present if we have available scripts.
- This PR fixes or works on following ticket(s): [OX-10898](https://scireum.myjetbrains.com/youtrack/issue/OX-10898)

Do not collect the dispatcher parameter when no scripts exist

---

pom.xml
src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlob.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoBlob.java

Mark blob lowercased fields with sirius db annotation. The actual lowercasing cannot be removed, as it gets called within some additional logic and from other places
- This PR fixes or works on following ticket(s): [SIRI-951](https://scireum.myjetbrains.com/youtrack/issue/SIRI-951)

Mark blob lowercased fields with sirius db annotation

---

src/main/java/sirius/biz/storage/layer2/jdbc/SQLBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/jdbc/SQLDirectory.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoDirectory.java

When querying for the lowercased filename field of an directory, query terms containing upper case characters make no sense and will be lower cased. 
Note: For MongoDB no changes are required, as it already works due to case insensitive prefix queries. 
- This PR fixes or works on following ticket(s): [SIRI-951](https://scireum.myjetbrains.com/youtrack/issue/SIRI-951)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/1968

SQLdirectory query lowercasing

---

src/main/java/sirius/biz/storage/layer2/BlobHardRef.java
src/main/java/sirius/biz/storage/layer2/BlobSoftRef.java

This allows some more methods of BlobSoftRef and BlobHardRef in the noodle sandbox.
- This PR fixes or works on following ticket(s): [SE-13581](https://scireum.myjetbrains.com/youtrack/issue/SE-13581)

Add some additional sandbox annotations for blob refs

---

src/main/java/sirius/biz/tycho/kb/KnowledgeBaseMessageExpander.java

SonarQube warns about these regex patterns being a potential risk of a DoS attack because of the default greedy behaviour of the included quantifiers. This can cause performance problems because of so called catastrophic backtracking situations. By switching problematic quantifiers
to being possessive or reluctant these problems can no longer occur.
- This PR fixes or works on following ticket(s): [OX-9946](https://scireum.myjetbrains.com/youtrack/issue/OX-9946)

SonarQube - Increase safeness of regexes by making quantifiers possessive/reluctant

---

src/main/java/sirius/biz/tenants/TenantSearchProvider.java
src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java

This was caused by missing opening quotes of the href attribute.
Without it the closing quotes were added to the ID of the select link, breaking its functionality.
- This PR fixes or works on following ticket(s): [SIRI-957](https://scireum.myjetbrains.com/youtrack/issue/SIRI-957)

Open Search - Ensure select link in user and tenant search results works

---

src/main/java/sirius/biz/jobs/params/SelectStringParameter.java

Modifies the SelectStringParameter.getValues() method to use fetchEntriesMap() only one single time.
- This PR fixes or works on following ticket(s): [DH-240](https://scireum.myjetbrains.com/youtrack/issue/DH-240)

DH-240: Fix the SelectStringParameter.getValues() method. 

---

src/main/java/sirius/biz/tenants/TenantUserManager.java
src/main/resources/component-070-biz.conf

API tokens have already been deprecated for some time. Still some legacy systems need to support this approach. However, some systems now at least only rely in hashed tokens, which are way more secure as simply accepting a plaintext token which is also stored as plaintext in the DB.
Therefore, we now permit a more fine grained control over how kind of API tokens and authentication can be used.
Within the system config, next to "accept-api-tokens" one can also specify "accept-hashed-api-tokens". The former controls whether plaintext API keys can be used "just like a password" and the latter controls if a properly hashed version of the token is accepted. These two flags operate independently of each other.
NOTE: If "accept-api-tokens" was / is enabled, please review carefully, if now …

Permits to only support login via hashed API tokens

---

src/main/java/sirius/biz/protocol/StoredIncident.java

- This PR fixes or works on following ticket(s): [SIRI-960](https://scireum.myjetbrains.com/youtrack/issue/SIRI-960)

Limits the maximum length of a error message to 16k

---

src/main/java/sirius/biz/importer/BaseImportHandler.java
src/main/java/sirius/biz/importer/ImportHandler.java
src/main/java/sirius/biz/importer/Importer.java
src/main/java/sirius/biz/importer/MongoEntityImportHandler.java
src/main/java/sirius/biz/importer/SQLEntityImportHandler.java
src/main/java/sirius/biz/jobs/batch/file/EntityImportJob.java
src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJob.java
src/main/java/sirius/biz/scripting/ScriptableEvent.java
src/main/java/sirius/biz/scripting/TypedScriptableEvent.java

Until now we were able to manipulate the context and/or entity being processed, but we did not have a way to fully skip an entity.
Now, events can call an `.abort()` method to abort the operations further down the line, example:
```js
registry.registerTypedHandler(sirius.biz.importer.BeforeFindEvent.class, Attachment.class, |event| {
let context = event.getContext();
if (context.getValue("type").equals("INSTALLATION_MANUAL")) {
event.abort();
log(event.getErrorContext().enhanceMessage("Skipped Installation Manual " + context.get("filePath")));
}
});
```
- calling it in a BeforeFindEvent skips the entire lookup, load and upsert.
- calling it in a BeforeLoadEvent skips the load and upsert.
- calling it in an AfterLoadEvent or BeforeCreateOrUpdateEvent skips the upsert.
**This should be a …

Allow scripting events to fully skip entities

---

src/main/java/sirius/biz/jobs/scheduler/JobSchedulerLoop.java
src/main/java/sirius/biz/jobs/scheduler/ScheduledEntryExecution.java
src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java
src/main/resources/biz_de.properties
src/main/resources/default/templates/biz/jobs/scheduler/entries.html.pasta

This PR introduces a button on the scheduled entries overview page, that allows to directly execute a selected scheduled entry.
- This PR fixes or works on following ticket(s): [SIRI-941](https://scireum.myjetbrains.com/youtrack/issue/SIRI-941)

Makes scheduled entries directly executable from overview page

---

src/main/java/sirius/biz/jobs/batch/file/RelationalEntityImportJob.java

Removes wrongly placed condition. We only skip a deletion if we had no entity at all. Mode check is done elsewhere.
- This PR fixes or works on following ticket(s): [SIRI-953](https://scireum.myjetbrains.com/youtrack/issue/SIRI-953)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/1988

Fixes skipped entities properly

---

src/main/java/sirius/biz/importer/BeforeCreateOrUpdateEvent.java

- BeforeCreateOrUpdateEvent.getEntity()
- BeforeCreateOrUpdateEvent.getImporterContext()
- This PR fixes or works on following ticket(s): [SIRI-953](https://scireum.myjetbrains.com/youtrack/issue/SIRI-953)

Permits to call methods via noodle scripts

---

src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta

this is implemented similar to t:blobImageSoftRefField
- This PR fixes or works on following ticket(s): [SE-13626](https://scireum.myjetbrains.com/youtrack/issue/SE-13626)

add file-extension icon to t:blobImageHardRefField

---

src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java

Previously an IllegalArgumentException aborted the unarchive process if a path cannot be converted to a sanitized target path.
Now we log it and keep going.

ExtractArchiveJob: Handles unresolvable paths

---

src/main/java/sirius/biz/tenants/TenantSearchProvider.java
src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java
src/main/java/sirius/biz/tycho/search/OpenSearchController.java
src/main/java/sirius/biz/tycho/search/OpenSearchResult.java
src/main/resources/component-070-biz.conf
src/main/resources/default/extensions/tycho-page-menu/menu.html.pasta
src/main/resources/default/extensions/wondergem-page-menu/menu.html.pasta
src/main/resources/default/templates/biz/tycho/kb/welcome.html.pasta
src/main/resources/default/templates/biz/tycho/kb/welcome_de.html.pasta
src/main/resources/default/templates/biz/tycho/search/search.html.pasta

- add category-links to templates
- fix security-sandbox restrictions
- fix texts in /kb welcome page and adjust them with the new permission
- switch order of user-accounts and tenants in search-results
- This PR fixes or works on following ticket(s): [SE-13658](https://scireum.myjetbrains.com/youtrack/issue/SE-13658)

Introduce new permission to use the open-search and fix some related problems

---

src/main/java/sirius/biz/scripting/mongo/MongoCustomEventDispatcherRepository.java
src/main/java/sirius/biz/scripting/mongo/MongoCustomScriptController.java

Since the creation of tenant-scripts are not open for end-customer, we detach them from sandboxed environments until we decide to open that functionality, where the whole sandboxing must be reviewed.
Reason being that many events are now not useful, if we cannot access methods from obtained objects. For example: the `AfterLoadEvent.getEntity()` will successfully return the entity being loaded, but from there no method can be called but a few such as `getIdAsString()`.
- This PR fixes or works on following ticket(s): [OX-11008](https://scireum.myjetbrains.com/youtrack/issue/OX-11008)

Detaches tenant scripting from sandbox

---

pom.xml
src/main/java/sirius/biz/protocol/Protocols.java

Since we removed the error messages from the stack trace we are moving the error messages of the incident to its designated field.
The added method makes sure that we do not exceed the total maxMessageLength by splitting the available characters between all messages.
Example:
...
...
and the corresponding stack trace:
-> This way we can make sure that we have only a limited amount of chars saved in the es entity and have a meaningfull and easy to understand stacktrace
- https://github.com/scireum/sirius-kernel/pull/525
- https://github.com/scireum/sirius-kernel/pull/526
- This PR fixes or works on following ticket(s): [SIRI-960](https://scireum.myjetbrains.com/youtrack/issue/SIRI-960)

Concatenates all error messages of an incident

---

pom.xml
src/main/resources/default/taglib/t/blobImageHardRefField.html.pasta
src/main/resources/default/taglib/t/blobImageSoftRefField.html.pasta
src/test/kotlin/sirius/biz/pagehelper/ElasticPageHelperTest.kt
src/test/kotlin/sirius/biz/pagehelper/MongoPageHelperTest.kt

Breaking due to changes in https://github.com/scireum/sirius-web/commit/70a8dedbd68441233c964bad95621a986e2957de 
- This PR fixes or works on following ticket(s): [SIRI-965](https://scireum.myjetbrains.com/youtrack/issue/SIRI-965)
- This PR is related to PR: https://github.com/scireum/sirius-web/pull/1423

SIRI-965: remove double methods and move to sirius-web and use them

---

src/main/java/sirius/biz/analytics/explorer/EventTimeSeriesComputer.java

- This PR fixes or works on following ticket(s): [OX-11019](https://scireum.myjetbrains.com/youtrack/issue/OX-11019)
- This PR is related to PR: https://github.com/scireum/oxomi/pull/11214

Adds comment for results on SQL-performance regarding countIf- and GROUPBY-queries to framework

---

src/main/java/sirius/biz/jdbc/DatabaseController.java
src/main/resources/default/templates/biz/model/sql.html.pasta

And also move it to above the list, to make it more accessible.

SQL: Show num rows and limit as info

---

src/main/resources/default/taglib/t/lookupValue.html.pasta
src/main/resources/default/taglib/t/lookupValues.html.pasta

Read-only `<t:lookupValue>` and `<t:lookupValues>` can currently by modified via the bolt icon and the following selection dialog. This PR suppresses this modification and also introduces a `showSelectionButton` in `<t:lookupValues>` that is already present in `<t:lookupValue>`.

Makes Read-Only `<t:lookupValue>` and `<t:lookupValues>` Actually Read-Only

---

src/main/java/sirius/biz/process/Processes.java
src/main/java/sirius/biz/storage/layer3/ExtractArchiveJob.java

Before:
Still unpacking:
After unpacking:
After fixes:
- This PR fixes or works on following ticket(s): [SIRI-972](https://scireum.myjetbrains.com/youtrack/issue/SIRI-972)

ExtractArchiveJob: Fixes job not stopping when cancelled by user, also changes state to use "cancelled" instead of "terminated"

---

src/main/resources/default/assets/scripts/lookup-tables.js.pasta

by clicking on the < > arrows or the area between the arrow-arms, the event is not the link, but the svg or the inner path. So the link is not working properly. Therefore using the element itself for setting data-attribute now to make clicking work on the whole button.

fix not working lookup-tables modal pagination

---

src/main/java/sirius/biz/protocol/Protocols.java

Sometimes we have to handle exceptions that are wrapped in other exceptions. Hopefully these wrapper-exceptions give us information about its wrapped exceptions in the message. Unfortunately, some of them does not. So we can try to catch the missing information from the overriden toString()-method that includes this information e.g. com.lowagie.text.ExceptionConverter
- This PR fixes or works on following ticket(s): [SIRI-985](https://scireum.myjetbrains.com/youtrack/issue/SIRI-985)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/1997

Shows more information for wrapped exceptions

---

src/main/java/sirius/biz/codelists/CodeListLookupTable.java
src/main/java/sirius/biz/codelists/ConfigLookupTable.java
src/main/java/sirius/biz/codelists/CustomLookupTable.java
src/main/java/sirius/biz/codelists/IDBFilteredLookupTable.java
src/main/java/sirius/biz/codelists/IDBLookupTable.java
src/main/java/sirius/biz/codelists/LookupTable.java
src/main/java/sirius/biz/codelists/LookupTableController.java
src/main/resources/default/taglib/t/lookupValue.html.pasta
src/main/resources/default/taglib/t/lookupValues.html.pasta
src/main/resources/default/taglib/w/lookupValue.html.pasta
src/main/resources/default/taglib/w/lookupValues.html.pasta

The autocomplete route already filtered out deprecated values. The implementations of LookupTable also filtered out deprecated values when using LookupTable#suggest with a filled search term. However LookupTable#scan and LookupTable#suggest without a search term wouldn't filter out deprecated values as it used the #scan method, thus introducing inconsistencies in handling deprecated values.
Whether or not deprecated values should be considered is now handled at low level to prevent:
- Filtering deprecated values multiple times
- Not filtering out deprecated values when no search term is present ("scan" method is used then), but filtering them once the user typed something (e.g. in case a custom autocomplete route is used).
- Limiting the stream of entities before filtering some of them …

SIRI-975: Uniformly take deprecated Lookup Entries into account or not

---

src/main/java/sirius/biz/storage/s3/ObjectStores.java
src/main/resources/component-070-biz.conf

By enabling the customization of the socket timeout, connection timeout, connection pool size and connection TTL.
The initialization is using the very same default values as before, so this change is no breaking.
- This PR fixes or works on following ticket(s): [SIRI-988](https://scireum.myjetbrains.com/youtrack/issue/SIRI-988)

Permits to fine tune S3 connections

---

src/main/java/sirius/biz/storage/layer2/L3Uplink.java

If directories are present, the total count can't just be calculated based on the number of SQLBlob / MongoBlob entities. While fixing this, a second bug emerged: The last file of a page is also listed as the first file of the next one.
- This PR fixes or works on following ticket(s): [SIRI-989](https://scireum.myjetbrains.com/youtrack/issue/SIRI-989)

SIRI-989: File Storage – Fix Duplicate Listing of Files and incorrect Total Count for Pagination

---

src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java

We only handled a sub-class of this exception type so client errors were not properly handled nor properly logged.
- This PR fixes or works on following ticket(s): [SIRI-988](https://scireum.myjetbrains.com/youtrack/issue/SIRI-988)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/2019

Handles AmazonClientException properly

---

src/main/java/sirius/biz/jobs/FixProcessTypes.java
src/main/java/sirius/biz/jobs/batch/BatchProcessJobFactory.java
src/main/java/sirius/biz/process/ProcessController.java

until now we always stored getClass().getSimpleName() + ".label" = MyJobFactory.label in the processType field on processes. For overridden implementations of e.g. abstract jobs this leads to not make the processes filterable on /ps. Now we will use the job#getName and store it as the processType. So the filtering url no longer is `/ps?processType=BmecatImportJobFactory.label` but `/ps?processType=import-bmecat`
To migrate existing values we implement a temporary job which resolves all available jobs and resolves the correct new type.
Patch-Task: Execute the job in simulation-mode (e.g. on a staging-system) and maybe adjust missing NLS-Keys.
Then execute it with simulation: no to fix all existing values.
BREAKING: If the job isn't executed - old jobs are not visible filterable by type
- …

BREAKING: change the way saving processTypes.

---

src/main/resources/default/kb/00000.html.pasta
src/main/resources/default/kb/en/user/noodle.html.pasta
src/main/resources/default/kb/en/user/tagliatelle.html.pasta
src/main/resources/default/taglib/k/base.html.pasta
src/main/resources/default/taglib/k/chapter.html.pasta
src/main/resources/default/templates/biz/tycho/kb/welcome.html.pasta
src/main/resources/default/templates/biz/tycho/kb/welcome_de.html.pasta

The `name` attribute has been deprecated earlier in commit a5f4a410156dc2078c474f7aafdc83b6c2e43cd6, thus leading to unwanted warnings when running `eod synchronize-knowledgebase`.
- This PR fixes or works on following ticket(s): [OX-11128](https://scireum.myjetbrains.com/youtrack/issue/OX-11128)

Fix: Deprecated Attributes (OX-11128)

---

src/main/java/sirius/biz/protocol/CustomJournalProvider.java
src/main/java/sirius/biz/protocol/JournalData.java

This can be added to a BaseEntity in order to write custom journal info. For example, changes to serialized data, or Nested properties can be logged in a more readable manner.
- This PR fixes or works on following ticket(s): [SIRI-1007](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1007)

SIRI-1007 Allow entities to supply custom journal info

---

src/main/java/sirius/biz/tycho/academy/jdbc/SQLOnboardingEngine.java
src/main/java/sirius/biz/tycho/academy/mongo/MongoOnboardingEngine.java

Already deleted videos (deleted = true) don't need to be marked again. This might cause the following error if the video has not been physically deleted yet when the recompute loops run:
```
Ein Fehler ist aufgetreten: Tried to update the changed entity MONGOACADEMYVIDEO-2HB7AN57L814PM709QGAFBDDFO (2HB7AN57L814PM709QGAFBDDFO), but actually nothing was changed in the database! There might be an error in one of its properties' transform or equals methods, as the framework indicated a changed property. The following properties are considered changed: academyVideoData_lastUpdated
```

Skips deleted onboarding videos from deletion marking

---

pom.xml
src/main/java/sirius/biz/web/BlobPdfReplaceHandler.java

Improves embedding blob content into PDFs via the `blob://` protocol by:
- Supporting physical keys
- Detecting and converting plain HTTP links pointing to blobs
- This PR fixes or works on following ticket(s): [OX-10783](https://scireum.myjetbrains.com/youtrack/issue/OX-10783)

PDF Rendering: Blobs

---

src/main/java/sirius/biz/storage/layer2/URLBuilder.java

Removes a method that has been introduced while working on OXOMI's new PDF datasheet renderer. In the meantime, the PDF generator now supports direct use of plain URLs. We no longer need to manually output special URLs, and the deleted method is now unused. S2 apparently never used the method at all. The PR is thus only _mildly breaking_. 😇
- This PR fixes or works on following ticket(s): [OX-10783](https://scireum.myjetbrains.com/youtrack/issue/OX-10783)

Maintenance: Unused Method (OX-10783)

---

src/main/java/sirius/biz/storage/layer2/L3Uplink.java

if there was a query to search for, the counter was "1-3 of 4" on 4 elements but only 3 hits.
- This PR fixes or works on following ticket(s): [SIRI-1021](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1021)
- This PR is related to PR: #2020

Fix bug in pagination in /fs with active query.

---

src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java
src/main/resources/biz_de.properties
src/main/resources/default/taglib/t/smartValue.html.pasta
src/main/resources/default/templates/biz/tenants/user-accounts-list.html.pasta

After:
https://github.com/user-attachments/assets/66343e26-547d-4c1c-b842-d9ac3ec165f1
https://github.com/user-attachments/assets/5957cfd8-0177-477a-9c33-7f71aec005ce
User accounts:
Open Search:
- This PR fixes or works on following ticket(s): [SIRI-1020](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1020)

User Accounts - Extends user account cards and open search results by the option to jump to a tenant if the user has the support role

---

src/main/resources/default/taglib/t/lookupValue.html.pasta

This is needed for the coming ability to define sub-properties of a property.
- This PR fixes or works on following ticket(s): [OX-11245](https://scireum.myjetbrains.com/youtrack/issue/OX-11245)

Permits to override the suggestion uri in t:lookupValue

---

src/main/java/sirius/biz/tycho/smart/TenantSmartValueProvider.java
src/main/java/sirius/biz/tycho/smart/UserAccountSmartValueProvider.java

The edit option should be presented independently of whether the tenant is already the current tenant or not.
- This PR fixes or works on following ticket(s): [SIRI-1020](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1020)

Smart Value - Show edit option in tenant smart value even when tenant is already selected

---

src/main/java/sirius/biz/importer/AfterLineLoadEvent.java
src/main/java/sirius/biz/importer/AfterNodeLoadEvent.java
src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedImportJob.java
src/main/java/sirius/biz/jobs/batch/file/LineBasedArchiveImportJob.java
src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java

We need access to the data read right after a file is processed, either the `Context` for line-based files or the `StructuredNode` for XML, where data can be manipulated before any handler access the data.
Note that for XML this is called for every registered *stage*, so the script needs to take care of child nodes if necessary.
- This PR fixes or works on following ticket(s): [OX-11624](https://scireum.myjetbrains.com/youtrack/issue/OX-11624)

Introduces new customer-scripting events

---

src/main/java/sirius/biz/web/MongoPageHelper.java

- This PR fixes or works on following ticket(s): [OX-11093](https://scireum.myjetbrains.com/youtrack/issue/OX-11093)

Introduces addEnumTermAggregation which builds an automatic filter facet

---

src/main/java/sirius/biz/jobs/batch/file/XMLImportJob.java

With the introduction of customer-scripting when loading XML files, we add a custom handler to process the events before calling the original handler, but unfortunately did not check if the original node handler was configured to ignore its contents (sub-tree). A use case for this: reading BMEcat's version from the root element, without having to load the entire file.
This change not only correctly cope with this case, but won't create this unnecessary handler if scripting is not active at all.
- This PR fixes or works on following ticket(s): [OX-11723](https://scireum.myjetbrains.com/youtrack/issue/OX-11723)

Solves an issue where importing an XML file causes large portions of the file to be loaded in RAM

---

src/main/resources/default/templates/biz/login.html.pasta

Makes password visible by clicking the eye-icon and also prevent spellcheckers to get usernames/passwords and give a required hint to not send empty username/password
- This PR fixes or works on following ticket(s): [SIRI-1035](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1035)

SIRI-1035 password-field optimizations

---

pom.xml
src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java

VirtualDelivery URLs were marked to be cached very long. When the underlying file changed a new URL would redirect there, but external sources (varnish, browsers and so on) would have already cached the URL and will be calling the old redirected URL.
This change ensures that:
1. Once a physical URL exists, we will always redirect
2. The redirected URL will either be not cached at all, or cached to a maximum of 1h.
Note that physical URLs are not affected by this change and respect the caching times defined by the call or its storage space definitions.
**Examples**
- Physical URL is indefinitely cached
```
> GET /dasd/p/tenants/74dd32864152cce6e57fde4f014f617f/M7CELNNL7JDT9UE7PHJ9GU2OD4/P0930KVRLNPL105N66RNCPAH2O HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
> 
* …
```

Ensure better caching of redirected Blob URLs

---

src/main/java/sirius/biz/jobs/batch/BatchProcessTaskExecutor.java
src/main/java/sirius/biz/process/Process.java
src/main/java/sirius/biz/process/ProcessContext.java
src/main/java/sirius/biz/process/ProcessEnvironment.java
src/main/java/sirius/biz/process/ProcessState.java
src/main/java/sirius/biz/process/Processes.java
src/main/resources/biz_de.properties
src/main/resources/default/templates/biz/process/process.html.pasta
src/main/resources/default/templates/biz/process/processes.html.pasta

This will indicate a process that is created but not yet actively processed. This may be the case when the maximum number of parallel processes in the queue of the processes is currently execeeded.
- This PR fixes or works on following ticket(s): [SIRI-681](https://scireum.myjetbrains.com/youtrack/issue/SIRI-681)

Processes - Waiting State

---

pom.xml
src/main/java/sirius/biz/jobs/batch/file/ArchiveImportJob.java
src/main/java/sirius/biz/jobs/batch/file/DictionaryBasedArchiveImportJob.java
src/main/java/sirius/biz/storage/layer3/VirtualFileSystemController.java
src/main/java/sirius/biz/storage/s3/ObjectStore.java
src/main/java/sirius/biz/util/ArchiveExtractor.java
src/main/java/sirius/biz/util/LocalArchiveExtractCallback.java

- This PR fixes or works on following ticket(s): [SIRI-1028](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1028)
- This PR depends on https://github.com/scireum/sirius-kernel/pull/544

Fixes system-files not being ignored by ZIP-native extractor when executing an import-job

---

src/main/java/sirius/biz/analytics/events/EventRecorder.java
src/main/java/sirius/biz/analytics/events/EventSpliterator.java
src/main/java/sirius/biz/analytics/events/PageImpressionEvent.java
src/main/java/sirius/biz/analytics/events/UserActivityEvent.java
src/main/java/sirius/biz/analytics/events/UserEvent.java
src/main/java/sirius/biz/tycho/updates/UpdateClickEvent.java
src/main/java/sirius/biz/util/SOAPCallEvent.java

Adds support for blockwise events fetching to allow fetching possibly larger number of events without having to keep database connections open.
As Events have no distinct fields by default (they do not have an ID), callers must provide a so called "duplicate preventer" that adjusts the query before fetching each block based on the result of the last block.
As events often have UserData fields, a default duplicate preventer is provided by introducing a new interface "UserEvent". The preventer assumes that users do not trigger events of the same type twice at the same time.
- This PR fixes or works on following ticket(s): [SE-14230](https://scireum.myjetbrains.com/youtrack/issue/SE-14230)

EventRecorder - Adds Blockwise Event Fetching

---

pom.xml
src/main/java/sirius/biz/storage/layer2/jdbc/SQLVariant.java
src/main/java/sirius/biz/storage/layer2/mongo/MongoVariant.java
src/main/java/sirius/biz/storage/legacy/VersionManager.java
src/main/java/sirius/biz/storage/legacy/VirtualObjectVersion.java
src/main/java/sirius/biz/tenants/SAMLController.java
src/main/java/sirius/biz/tenants/TenantController.java
src/main/java/sirius/biz/tenants/TenantUserManager.java
src/main/java/sirius/biz/tenants/Tenants.java
src/main/java/sirius/biz/tenants/UserAccountData.java
src/main/java/sirius/biz/tenants/UserAccountSearchProvider.java
src/main/resources/default/templates/biz/tenants/tenant-extended.html.pasta

Marking as BREAKING since this applies a breaking change from sirius-biz.
- This PR fixes or works on following ticket(s): [SIRI-1039](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1039)
- This PR is related to PR: https://github.com/scireum/sirius-db/pull/668
- This PR replaces: https://github.com/scireum/sirius-biz/pull/2064

Bumps sirius libs and applies breaking changes

---

src/main/java/sirius/biz/jobs/params/LocalDateTimeParameter.java
src/main/java/sirius/biz/storage/layer3/DeleteFilesJob.java
src/main/resources/default/templates/biz/jobs/params/date-time.html.pasta

This is based on the `LocalDateParameter` and the relatively new `t:localDateTime` tag.
Also uses the new parameter in the `DeleteFilesJob`.
- This PR fixes or works on following ticket(s): [SIRI-929](https://scireum.myjetbrains.com/youtrack/issue/SIRI-929)

Jobs Add a new parameter for setting local date times

---

src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java

1. defines an overall limit as it makes no sense to cache those too long
2. no caching if a conversion will be attempted
- This PR fixes or works on following ticket(s): [OX-11230](https://scireum.myjetbrains.com/youtrack/issue/OX-11230)

Improves caching of virtual URLs

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java

When converting "virtual" blob information into physical keys, the framework generally distinguishes between blocking and non-blocking operation. In the former case, if a variant does not exist yet, the node is required to have conversion enabled as an exception would be thrown else. In the latter case of non-blocking operation, even on nodes with conversion enabled, no conversion would be attempted. This requires the invoker to explicitly deal with the case when conversion is required.
Before, the `download` method simply used a blocking call, obviously assuming that it would return a `null` object in case conversion is disabled. This assumption is wrong. We need to make sure that the current node has conversion enabled before invoking a blocking call. For nodes without conversion, we …

Blob Download and Conversion (SIRI-1022)

---

src/main/java/sirius/biz/isenguard/Isenguard.java
src/main/java/sirius/biz/isenguard/IsenguardFirewall.java
src/main/java/sirius/biz/isenguard/Limiter.java
src/main/java/sirius/biz/isenguard/NOOPLimiter.java
src/main/java/sirius/biz/isenguard/RedisLimiter.java
src/main/java/sirius/biz/isenguard/SmartLimiter.java
src/test/kotlin/sirius/biz/isenguard/IsenguardTest.kt

Improves Rate Limiting:
- `Isenguard` now provides methods for checking the limit without affecting the state
- Methods have been renamed, as some names have been misleading – This is a *breaking change*!
- `Limiter.isIPBLacklisted(…)` → `Limiter.isIPBlacklisted(…)` (typo)
- `Limiter.readLimit(…)` → `Limiter.readCallCount(…)` (misleading name, the method returns the call count)
- `Limiter.increaseAndCheckLimit(…)` → `Limiter.registerCallAndCheckLimit(…)` (harmonised naming to indicate purpose more obviously)
- `Isenguard. isRateLimitReached(…)` → `Isenguard.registerCallAndCheckRateLimitReached(…)` (misleading name, the method has side effects as it increases the call count)
- Further typo fixes and documentation improvements
- This PR fixes or works on following ticket(s): …

Rate Limiting: Miscellaneous Improvements

---

pom.xml

This is included via org.apache.ftpserver, but has a Critical Vulnerability: https://osv.dev/vulnerability/GHSA-76h9-2vwh-w278 (CVE-2024-52046)

Adds apache-mina as directly dependency

---

pom.xml
src/main/java/sirius/biz/tenants/HttpsUrlValidator.java
src/main/resources/biz_de.properties

Adds a property validator that enforces a valid HTTPS URL.
Note that the entire property validation framework may be subject to some maintenance soon in order to improve integration with Tycho (and file structure). See [SIRI-1050](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1050).
- This PR fixes or works on following ticket(s): [OX-11244](https://scireum.myjetbrains.com/youtrack/issue/OX-11244)
- This PR is related to PR: https://github.com/scireum/sirius-kernel/pull/546

HTTPS URL Property Validator

---

src/main/resources/default/templates/biz/login.html.pasta

We do not want the second "make password visible" button as it is quite quirky.

hide quirky show-password field in edge - we have our own one.

---

src/main/java/sirius/biz/tycho/updates/UpdatesController.java
src/main/java/sirius/biz/tycho/updates/UpdatesReport.java
src/main/resources/default/templates/biz/tycho/dashboard-news.html.pasta

Use Strings#isHttpUrl for displaying the links in the update report instead of checking it in an extra method.
on some systems some bots have inserted guids like 
`(select(0)from(select(sleep(15)))v)/*'+(select(0)from(select(sleep(15)))v)+...`
or other hacky values. They will cause an IllegalArgumentException and so the whole report was broken here.
@ all Maybe we should check valid URLs on the event-recording - or should `/hallo` be a valid path?
see sirius.biz.tycho.updates.UpdatesController#markUpdatesAsSeen

fix update report for hacky values

---

src/main/java/sirius/biz/importer/format/EnumPropertyTransformer.java
src/main/java/sirius/biz/importer/format/FieldDefinition.java

For BooleanProperty this is already done in sirius.biz.importer.format.BooleanPropertyTransformer#customizeField but if you add one via FieldDefinition.booleanField we also want to add the translated value.
For Enum Values we also already import the translated value like in the export, so we simply also add it to the docu.
This only adds the current language version in allowed values, maybe the translated values could also be added for all other possible active languages like in the headlines?
- This PR fixes or works on following ticket(s): [SIRI-1047](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1047)

SIRI-1047 List Yes, No or Ja, Nein for allowed boolean values in job-docu, also translated enum values

---

src/main/java/sirius/biz/tenants/EmailAddressValidator.java
src/main/java/sirius/biz/tenants/HttpsUrlValidator.java
src/main/java/sirius/biz/tenants/PhoneNumberValidator.java

Previously just a error message banner was displayed at the top of the form, but the field was not marked accordingly like when other field constraints are breached.
Jakob also suggested moving the validators to sirius-db, but only 2 of the 3 could be moved, as the `EmailAddressValidator` uses the `Mails` Part for validation, which resides in sirius-web.
- This PR fixes or works on following ticket(s): [SIRI-1050](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1050)

Mark erroneous field in form when validator triggers

---

src/main/java/sirius/biz/web/BizController.java

This has two effects:
- The process is filterable via the state "running" while it runs
- The process is filterable via the "started" time filter

Processes - Mark complex delete as running when it is started

---

src/main/java/sirius/biz/scripting/JobTaskContextAdapter.java
src/main/java/sirius/biz/tenants/Tenants.java

Our KBA already mentions a way to cancel scripts. This however only worked for scripts which created a process. Now it also works for e.g. database queries executed directly inside the scripts environment.
Plus a small drive-by for marking admin processes as running.
- This PR fixes or works on following ticket(s): [SIRI-1053](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1053)

Allows Canceling the TaskContext of Scripts

---

src/main/java/sirius/biz/web/BasePageHelper.java

the existent method already does this, but if you already have a page, the filter-facet would be applied doubled. So we simply duplicate the method but without applying the facets and for usages where the facets are needed, now a change is needed.
Patch-Task: change buildUnderlyingQuery to buildUnderlyingQueryWithFacets where facets needed.
- This PR fixes or works on following ticket(s): [SIRI-1054](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1054)

BREAKING: introduce method to buildUnderlyingQueryWithFacets

---

docker-compose.yml
src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
src/main/java/sirius/biz/storage/layer2/BlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/README.md
src/main/java/sirius/biz/storage/layer2/URLBuilder.java
src/main/java/sirius/biz/web/BlobPdfReplaceHandler.java
src/main/resources/component-070-biz.conf
src/test/resources/docker-compose.yml

The main purpose of this PR is to:
- permit several hard-coded settings such as retry delay and number of attempts to be customized (same values used as before, so the standard config is non-breaking)
- permits to wait longer for a conversion to finish. Previously we would return a HTTP 503 after around 2s for any successful conversion which could take longer than that. Now we support the `/dasd/...?waitLonger=true` parameter to makes the server retry a few more times (obviously customizable). Defaulting to 3x the normal amount.
One use case for this ALREADY IMPLEMENTED is the conversion for embedding in PDF (BlobPdfReplaceHandler).
To achieve this, the BlobStorageSpace has been refactored (thus BREAKING), in order to remove a *god* method which based on a single flag took various complex …

Permits to wait longer for a variant conversion

---

pom.xml
src/main/java/sirius/biz/storage/layer3/downlink/ftp/FTPServer.java

* mariadb-java-client: 3.4.1 -> 3.5.2
* httpclient5: 5.4 -> 5.4.2
* ftpserver-core: 1.2.0 -> 1.2.1
* bcprov-jdk18on: 1.78.1 -> 1.80
* commons-net: 3.11.0 -> 3.11.1
* snakeyaml: 2.2. -> 2.4
ClickHouse Driver also has a version upgrade available but will be done in a separate ticket, as historically these upgrade tend to cause problems.
Batik is removed from dependencies, as it is already defined in sirius-web. Web will be upgraded to include a version upgrade.
- This PR fixes or works on following ticket(s): [SIRI-1071](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1071)

Update libraries to latest versions and link to change logs

---

pom.xml
src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java

We set a header to search engines will not cache storage URLs, which is pointless since most of the time they have a limited lifetime. For sure not every bot respects that but the big players like Google do.
- This PR fixes or works on following ticket(s): [SIRI-1049](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1049)
- This PR is related to PR: https://github.com/scireum/sirius-web/pull/1505

Hides /dasd URLs from SEO

---

src/main/resources/default/templates/biz/storage/list.html.pasta

Fixes: 
Before:
After:
- This PR fixes or works on following ticket(s): [OX-11700](https://scireum.myjetbrains.com/youtrack/issue/OX-11700)

File Explorer - Fixes folder descriptions from being inlined 

---

pom.xml
src/main/java/sirius/biz/jobs/params/IntParameter.java
src/main/java/sirius/biz/storage/layer1/FSObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer1/ObjectStorageSpace.java
src/main/java/sirius/biz/storage/layer1/S3ObjectStorageSpace.java
src/main/java/sirius/biz/storage/util/MissingBlobObjectCheckJob.java
src/main/java/sirius/biz/storage/util/MissingMongoBlobObjectCheckJob.java
src/main/java/sirius/biz/storage/util/MissingSqlBlobObjectCheckJob.java
src/main/resources/component-070-biz.conf

Over time, we have seen many blobs in the system pointing to non-existing physical objects. These could have been generated by previous bugs already fixed or still unknown ones.
Therefore as the first step we would like to list all blobs in such situation. This PR introduces an admin job responsible to scan that and attach a ZIP containing a CSV in the job itself (logging as process logs can potentially generate too many entries for large systems).
Later on, either this job will be enhanced to perform the actual clean-up or a new one which will parse the generated files.
- compatible with Mongo and SQL Frameworks
- re-startable (although rudimentary)
- parallelism
- check variants
- check the replication space (if configured)
```csv …
```

Adds an admin job to scan for missing storage objects

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/URLBuilder.java

A blob which a variant exhausted the conversion attempts were causing a rendering error in `t:blobImage`.
Now we properly deter this and display the "broken image" placeholder.
- This PR fixes or works on following ticket(s): [SIRI-1090](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1090)

Fixes handling and rendering of blobs which ultimately failed conversion

---

src/main/java/sirius/biz/analytics/reports/Cells.java
src/main/java/sirius/biz/analytics/reports/LinesCellFormat.java

Adds a simple cell format that we need in our case for addresses.
Example in a table with heading and test data:
- This PR fixes or works on following ticket(s): [SE-14365](https://scireum.myjetbrains.com/youtrack/issue/SE-14365)

Adds a cell format for displaying lines of data (e.g. addresses).

---

pom.xml
src/main/java/sirius/biz/storage/layer3/HeadRequestFileResolver.java

Refactors `HeadRequestFileResolver` such that:
- `Outcall` objects are created using a joint helper before specialisation
- `GET` requests also evaluate the last URL for a file name in case the `Content-Disposition` header is empty
- This PR fixes or works on following ticket(s): [OX-11816](https://scireum.myjetbrains.com/youtrack/issue/OX-11816)

Cleanup of HeadRequestFileResolver

---

src/main/resources/default/taglib/k/previewImage.html.pasta

The previous solution did not work as expected, as sirius CSS is not loaded in the backend (at least not on pages without an OXOMI integration), so `sci-object-fit-contain` had no effect.
**Before:**
**After:**

KBA - Use correct object fit mode for preview images in articles

---

pom.xml
src/main/resources/component-070-biz.conf

This prevents a problem mentioned in scireum/sirius-db#679 where jupiter seems to struggle with the way jedis sets up the connection when client info is enabled.
- This PR fixes or works on following ticket(s): [SIRI-971](https://scireum.myjetbrains.com/youtrack/issue/SIRI-971)
- This PR is related to PR: https://github.com/scireum/sirius-db/pull/679

Jupiter - Disable sending redis client info to jupiter server

---

src/main/java/sirius/biz/jobs/Jobs.java
src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java
src/main/resources/default/templates/biz/jobs/scheduler/entry.html.pasta

When creating a new job scheduler entry, a GET-parameter is now supported that preselects the job, like `/jobs/scheduler/entry/new?selectedJob=whatever-job-name`

Job Scheduler: Job Preselection

---

src/main/java/sirius/biz/jobs/scheduler/SchedulerController.java

Displays an error and redirects to the overview of scheduled jobs if an unknown or inaccessible job is passed as preset.
- This PR fixes or works on following ticket(s): [SIRI-1097](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1097)

Job Scheduling: Error Handling (SIRI-1097)

---

docker-compose.yml
src/test/resources/docker-compose.yml

- Redis: 7.4.2 -> 7.4.3
- ElasticSearch: via [Ticket](https://scireum.myjetbrains.com/youtrack/issue/DO-353)
- ClickHouse: via [Ticket](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1086)
- MariaDB: Ticket should be created for Upgrade to 11.7.2 if desired. Current LTS version is 11.4.x
- This PR fixes or works on following ticket(s): [SIRI-1077](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1077)

Update Docker containers to latest versions

---

src/main/java/sirius/biz/process/ProcessEnvironment.java

As they can be provided as $SomeKeyName which are resolved from the translated resources (note that getMessage already compile the message which might come from a text or keys as well)
- This PR fixes or works on following ticket(s): [OX-11992](https://scireum.myjetbrains.com/youtrack/issue/OX-11992)

Smart get the message type when logging them to the process log files

---

src/main/resources/default/taglib/t/blobImage.html.pasta

- This PR fixes or works on following ticket(s): [OX-12040](https://scireum.myjetbrains.com/youtrack/issue/OX-12040)
- This PR is related to PR: https://github.com/scireum/oxomi/pull/12297

t:blobImage - Implements additional attribute `alt` to be able to pass an alt text to the images

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/README.md

The handlers were sometimes called prematurely after the first failed or timed out conversion. These should only be called after all attempts exhausted.
- This PR fixes or works on following ticket(s): [OX-11942](https://scireum.myjetbrains.com/youtrack/issue/OX-11942)

Only call conversion failed handlers after all attempts were made

---

src/main/java/sirius/biz/importer/BaseImportHandler.java
src/main/java/sirius/biz/importer/BeforeLoadEvent.java

This event was not consistently called across all load events. In this particular one, used to query an entity from the DB, changing a context's key via script field would not have any effect and the entity would be queried with the unmodified value.
- This PR fixes or works on following ticket(s): [OX-12091](https://scireum.myjetbrains.com/youtrack/issue/OX-12091)

Invokes the BeforeLoadEvent in another load method

---

src/main/java/sirius/biz/storage/layer2/BasicBlobStorageSpace.java
src/main/java/sirius/biz/storage/layer2/BlobDispatcher.java
src/main/java/sirius/biz/storage/layer2/URLBuilder.java
src/main/java/sirius/biz/storage/layer2/variants/ConversionEngine.java

- Only invoke failed handlers when really converting. They were called also when just checking if a variant exists.
- Fixes an issue where every call to `throwExhaustedConversionAttemptsException` prematurely logged errors (most of them were already caught by the caller)
- Improves the URL builder to not fail when a file cannot be converted, but delivers the fallback or empty result instead
- Delivers a 404 when attempting to redirect a virtual URL to a physical which cannot be converted
- This PR fixes or works on following ticket(s): [SIRI-1036](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1036)

Improves handling of the ultimately failed conversion

---

src/main/java/sirius/biz/storage/layer2/URLBuilder.java
src/main/resources/default/assets/scripts/images.js

- Fixes an issue where lazily loaded images would not react to a 404 response and keep trying
- Restores the "broken image" symbol which was no longer shown since the related fix
- This PR fixes or works on following ticket(s): [SIRI-1136](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1136)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/2169

Fixes the broken image symbol and not necessary retries

---

src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPSUplinkConnectorConfig.java
src/main/java/sirius/biz/storage/layer3/uplink/ftp/FTPUplinkConnectorConfig.java
src/main/resources/component-070-biz.conf

Some server implementations of TLS 1.3 are incompatible with Apache MINA. This allows specifying the protocol to use.
- This PR fixes or works on following ticket(s): [SE-14786](https://scireum.myjetbrains.com/youtrack/issue/SE-14786)
- Maybe someday java is going to fix the not required by standard usage of user_canceled with ticket: https://bugs.openjdk.org/browse/JDK-8323517

SE-14786 Allow setting the SSL protocol in the FTPS uplink
